### ISSUE TITLE
The keywords are highlighted in italic bold on the page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1008]
Steps to reproduce:
1. Open the Library https://library-staging.mindlogger.org/
2. Start typing Keywords  in the search field (e.g. Al)
3. Look at the result 

Actual result: The keywords are highlighted in italic bold on the page
Expected result: The keywords are highlighted in bold on the page

Environment:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by binaryExDev** [comment]
@WorldImpex @sergeysemenuta Do you think that I need to remove Italic?
I'm asking as I added italic on purpose to make it better.

**Comment by WorldImpex** [comment]
Yes Please @binaryExDev

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2021-05-20_15-28-51.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/1258f695-2942-4e32-8917-dec3c5268ba9)
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
