### ISSUE TITLE
The user is navigated to the empty builder after trying to transfer an item which is a part of activity with conditional logic  

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1013]
**Preconditions:**
The applet contains: conditional logic  and shared with the library
**Steps to reproduce:**
1. Open the library and log in  https://library-staging.mindlogger.org/
2. Choose the applet 'transfer an item  to the builder'
3. Mark one item from the activity and add to the basket
4. Go to the basket
5. Checkout that item to the existing applet
6. Look at the result
**Actual result:** The user is navigated to the empty builder after trying to transfer an item which is a part of activity with conditional logic  
**Video:** https://www.screencast.com/t/WNqhQr9AV3c
**Expected result:** The user should navigate to the existing applet .All content should be available for that applet and an activity with selected item should be added

**Environment:**
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by natalia-muzyka** [comment]
Not reproduced
https://www.screencast.com/t/1fZL4SPMKlTY

Environment:
https://library-staging.mindlogger.org/ 
https://admin-staging.mindlogger.org/ 
Win 10 // Chrome Version 91.0.4472.101

Applets: 
EDUCATE EMA applet
DBT Applet 1
Healthy Brain Network (NIMH content) v0.30 
Conditional logic
