### ISSUE TITLE
There is a wrong path for a copied link to share an applet with others

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1014]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/# snakessqa@gmail.com // 123456
2. Choose an an applet that are shared with the Library
3. Click the globe icon
4. Click the " Copy link to share with others " link
5. Paste that link outside of ML
6. Look at the URL

**Actual result:**  There is a wrong path(localhost:8081/applets/60a7c7a23dab1e660f94f3ee) for a copied link to share an applet with others
![2021-05-21_17-09-30.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c49bde6c-8454-4183-8474-eee7737ac4c7)
**Expected result:** The copied link should take the user to the detail page on applet library in staging environment

**Environment:**
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by sergeysemenuta** [comment]
The issue still reproduces. 
Video: https://www.screencast.com/t/5BKzaR20

Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91

**Comment by natalia-muzyka** [comment]
**Additional info:**
There is different behavior after copying the link via:
- context menu - gives the https://admin-staging.mindlogger.org/
- clicking the " Copy link to share with others " link - gives the latest copied info from the buffer
https://www.screencast.com/t/AfzhGU8wxsy

**Comment by natalia-muzyka** [comment]
**The copied link provides to the main library page, not to the applet detail page**
(for logged in and non-logged in user)

Copying link with context menu still gives the https://admin-staging.mindlogger.org/
https://www.screencast.com/t/u8UQ29GS

**Environment**
https://admin-staging.mindlogger.org/#
Win 10 // Chrome 91.0.4472.77

**Comment by natalia-muzyka** [comment]
**The issue is still reproducible.**

There is different behavior after copying the link via:
- context menu - gives the https://admin-staging.mindlogger.org/
- clicking the " Copy link to share with others " link - gives the latest copied info from the buffer
Video: https://www.screencast.com/t/iYLeM5Etq

Environment
https://admin-staging.mindlogger.org/#
Win 10 // Chrome 91

**Comment by natalia-muzyka** [comment]
@devbtech 
The copied link/link copied via context menu provides to the main library page, not to the applet detail page
(for logged in and non-logged in user). The copied link doesn't match the url that displayed after clicking the "See applet detail page".

https://www.screencast.com/t/prtAncxfAe
https://www.screencast.com/t/U7jXzxRyp4

**Environment**
https://admin-staging.mindlogger.org/# 
snakessqa@gmail.com // 123456

**Comment by natalia-muzyka** [comment]
@devbtech  
The copied from the dashboard link still redirects to the main library page
https://www.screencast.com/t/R3IwPuTO

Here are differences between the url after clicking the "see applet detail" button and the link copied from the dashboard
https://www.screencast.com/t/Xdy3qDIwe3A

Environment
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91

**Comment by natalia-muzyka** [comment]
Verified as fixed

Environment
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
