### ISSUE TITLE
The confirmation message  "Are you sure you want to delete " Applet Name " from your basket?" is not shown after unselecting the last selection in an applet 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1019]
**Preconditions:**
-The applet  is in the basket
- The applet/activities/items are checked
**Steps to reproduce:**
1. Unselect the the last selection in an applet 
2. Look at the result

**Actual result:** The confirmation message  "Are you sure you want to delete " Applet Name " from your basket?" is not shown after unselecting the last selection in an applet 
**Expected result:** The confirmation message  "Are you sure you want to delete " Applet Name " from your basket?" is shown after unselecting the last selection in an applet 
![2021-05-24_18-03-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/bf2b4097-0dfa-45f7-93b7-1d16c6746a2b)
**Video:** https://www.screencast.com/t/J2KpQR0nl9
**Environment:**
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by natalia-muzyka** [comment]
A confirmation message is shown after unselecting the last selection in an applet

**Issue**
For logged-in and non-logged in user there are different confirmation messages:
1. Logged in: 
"Are you sure you want to delete from your basket?"
2. Not logged in: 
"Are you sure you want to delete *Applet name* from your cart"

**Expected result:**
The confirmation message "Are you sure you want to delete " Applet Name " from your basket?" is shown after unselecting the last selection in an applet

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.77
Attachment:
![confirmation message.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/26f037a0-e364-4041-ba1d-729c8f9185f5)

**Comment by natalia-muzyka** [comment]
**The applet name is skipped in the confirmation message for logged-in user**
https://www.screencast.com/t/cNIZLO6Pp

**Expected result:**
The confirmation message "Are you sure you want to delete " Applet Name " from your basket?" is shown after unselecting the last selection in an applet

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.77
@jj105 @binaryExDev

**Comment by natalia-muzyka** [comment]
The issue is fixed
https://www.screencast.com/t/HZMQHuzmV

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91

**Comment by natalia-muzyka** [comment]
The issue is reproducible again for authorized and non-authorized user
https://www.screencast.com/t/z52WltI4p

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/hnnazSmQOi

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
