### ISSUE TITLE
Nothing happens after clicking the "Download Schema" button in when editing an existing applet

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1024]
**Steps to reproduce:**
1. Log in to the admin panel  https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Choose any applet and got to edit that applet
3. Click the  "Download Schema" button in the top bar
4. Look at the result
**Actual result:** Nothing happens after clicking the "Download Schema" button in when editing an existing applet
**Video:** https://www.screencast.com/t/HdEUF5StC5
**Expected result:** A zip file is downloaded after clicking the "Download Schema" button in when editing an existing applet
**Note:** Works as expected when creating an new applet using the builder
**Environment:**
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by natalia-muzyka** [comment]
Still reproducible on https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124

**Comment by WorldImpex** [comment]
dupe https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/593
