### ISSUE TITLE
The "Remove Applet from folder " button is available outside of the folder

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1027]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Hover over an applet
3. Look at the buttons 

**Actual result:** The "Remove Applet from folder " button is available outside of the folder. Clicking on it shows the popup to delete an applet
![2021-05-26_9-48-35.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/237d4187-d8ed-4963-9b65-21529c3d7183)
**Expected result**: The "Remove Applet from folder " button is available within the folder. Clicking on it shows the popup to delete an applet form the folder
**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by natalia-muzyka** [comment]
The issue is fixed
https://www.screencast.com/t/0M1WBcXF4Wv

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90
