### ISSUE TITLE
Draw Item: Does not Export any Media 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1028]
Draw does not store in the db and export media

**Comment by natalia-muzyka** [comment]
The issue is still reproduced
No media is exported for drawing

**Environment**
https://admin-staging.mindlogger.org/
ML v 0.16.25 (Staging environments)
iPhone XR // iOS 14.3
Samsung Galaxy S7 Edge // Android 8.1

Account: snakessqa@gmail.com
Applet: "Media"

**Comment by natalia-muzyka** [comment]
Drawing export works with an existing applet and with new as well
The result is a separate SVG file
If the drawing option has a background image or draw image - these pictures aren't exported with related svg files, but at least, files have a naming according to the screen.
https://www.screencast.com/t/8HjQgjInIP

Exported folder
[https://app.zenhub.com/files/189080374/1915a794-0f9c-40c6-8a90-c634528349dd/download](https://app.zenhub.com/files/189080374/1915a794-0f9c-40c6-8a90-c634528349dd/download)
