### ISSUE TITLE
The latest score calculation for the checkbox item is broken on the data viz dashboard

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1029]
**Preconditions:**
-The applet with subscales, lookup tables is uploaded to the admin panel
-The User has taken the activity ion that applet
**Steps to reproduce:**
1. Log in to the admin panel logan@ss.com // 123456
2. Select the TO check Scoring applet
3. Go to users page
4. Select the owner and navigate to the data screen (Applet password:Qwe123!!!)
5. Look at the second subscale

**Actual result:** The latest score calculation for the checkbox item is broken on the data viz dashboard. Latest score:0
![2021-05-26_17-17-37.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/b0509cda-6114-4453-917e-2417799c4867)
**Expected result:** The latest score calculation for the checkbox item is not broken on the data viz dashboard
**Environment:**
https://admin-staging.mindlogger.org/
Win 10//  Chrome 91

**Comment by natalia-muzyka** [comment]
The issue is fixed
The latest score calculation for the checkbox item is displayed as expected on the data viz dashboard
https://www.screencast.com/t/ozMFJmYq
https://www.screencast.com/t/5hAqKsdh5

Environment
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91
