### ISSUE TITLE
I want to manage roles of an applet - Organizers

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#103]
As an owner or manager, I want to manage the organizers that have access to an applet so that the right users are given access to what they need to accomplish the user's task 

Requirements: 

Admin Panel
1. Have each role in a separate tab on the dashboard. 
2. If a user is an editor and a reviewer then that user would show up on both tabs 

Owner/ Manager 

1. Give the owner/ manager the ability to edit an organizer's access to the applet they are managing. I.e.: Changing an editor's permission to the reviewer, etc 
2. Give the owner/manager the ability to revoke access to any role type an applet
3. Any types of roles that is not a user can have the user type changed from the admin dashboard (does not need a new invitation) 
4. Editors, Coordinators, and Reviewers can have multiple combinations of access. (One account could be a reviewer and an editor or all three, etc) 
5. Owners/ Managers can revoke one permission type and leave the rest
6. Owners/ Managers can add and remove users from a reviewer's permissions 

![Organizer Mgmt (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/70919c92-f941-4759-a859-9a8c0f4caf18)

[Here is the different permission levels ](https://docs.google.com/spreadsheets/d/1ZmrEy9dTlrM400Uw4SS89n8Q8LoqB3pIejNfq0XojAY/edit?usp=sharing)

Relates to #39

**Comment by shnizzedy** [comment]
To clarify some things I think are unclear in the flowchart above:

1. Currently a single user account can have any number of [roles](https://github.com/ChildMindInstitute/mindlogger-app-backend#roles) in an applet. The strings under the heading "Account Type" are examples of roles. While the flowchart shows different `ID`s for `Ben Thonet: Editor` and  `Ben Thonet: Reviewer`, those `ID`s would be the same unless there are two Bens or Ben has different accounts for different roles in the same applet.
1. The data in the `ID`s column of the `Active Users` table should be [profile](https://github.com/ChildMindInstitute/mindlogger-app-backend#profile) `ID`s (so the same user would have the same `ID` within the same applet, as in the point above, but would have a different `ID` for a different applet using the same account).

[![relationships between users and content](https://user-images.githubusercontent.com/5974438/74166557-be98a680-4bf4-11ea-94b7-03c70a44a28e.png)](https://github.com/ChildMindInstitute/mindlogger-app-backend/wiki/images/profiles.dia)

**Comment by WorldImpex** [comment]
34 35 13

**Comment by sergeysemenuta** [comment]
Works as expected on the current version of the admin panel 
 Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85
Closing this ticket out
