### ISSUE TITLE
Show Cumulative Score Results on Data visualization 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1030]
As an admin, I want to see the cumulative score table at the top of a user's data visualization so that I understand what thresholds were or were not met. 

- Exactly what is shown on mobile should be positioned above the first response option on data visualization 

![mindlogger-admin (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/07a75e0c-5f0c-443d-8223-8433185e8547)

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8a7d9061-096e-4f26-a29a-79ea9de57ae7)

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/3cd27af6-f998-458d-8a4a-4dae9b5a44ed)

**Comment by natalia-muzyka** [comment]
Update 04/08 

Issues: 

**Fixed:** 
The cumulative score message on the DataViz is not based on the user's score [#1159](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1159)

The markdown text is displayed raw(code) on the DataViz (cumulative score message) [#1163](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1163)

**New:**
[The Summary(calculation) block is missing for the pediatric screener on DataViz #1176](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1176)

As the #1176 is moved to the backlog, and all the other requirements are met, the ticket is verified and closed.
