### ISSUE TITLE
The header image URL is shown on the subscale panels on the Data Viz dashboard

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1033]
**Preconditions:**
-The applet with subscales is uploaded to the dashboard
-Radio, checkbox, slider items have header images
- The User completed the activities on the app
**Steps to reproduce:**
1. Log in to the admin panel https://admin.mindlogger.org/ (logan@ss.com // 123456)
2. Select the "TO check Scoring" applet and navigate to the users page
3. Select the  owner in the manager tab and navigate to the Data viz dashboard (Applet password:Qwe123!!!)
4. Expand the subscales panels
5. Look at the result

**Actual result:** The header image URL is shown on the  subscale panels on the Data Viz dashboard
![2021-05-27_15-58-26.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c0b4c428-251f-4128-91b3-85c8174bcb9b)
**Expected result:** The header image URL should be hidden on the  subscale panels on the Data Viz dashboard

**Environment:**
https://admin-staging.mindlogger.org/ (Win 10 // Chrome 91 )

**Comment by natalia-muzyka** [comment]
The issue is fixed
The header image URL is not shown on the subscale panels on the Data Viz dashboard
https://www.screencast.com/t/B95CZLqDfhaL

Environment:
https://admin-staging.mindlogger.org/ (Win 10 // Chrome 91 )
