### ISSUE TITLE
The unnecessary element is shown at the bottom of the calendar picker in the "REVIEW" tab

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1034]
**Steps to reproduce:**
1. Log into the admin panel https://admin-staging.mindlogger.org/ (loganss@gmail.com // 123456)
2. Select the DBT1 applet and go to the users page
3. Select a user and navigate to the data viz dashboard (Applet password: Qwe123!!!)
4. Click the the "REVIEW" tab
5. Open the calendar 
6. Look at the result

**Actual result:** The unnecessary element is shown at the bottom of the calendar picker in the "REVIEW" tab
![2021-05-27_18-34-00.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/1ecb290d-1c9b-4c19-83c7-89aa53eebb5f)
**Expected result:** The unnecessary element is not shown at the bottom of the calendar picker in the "REVIEW" tab

**Environment:**
https://admin-staging.mindlogger.org/ (Win 10 // Chrome 91 )

**Comment by natalia-muzyka** [comment]
The issue is fixed
https://www.screencast.com/t/ONseu0WbEMu1

Environment:
https://admin-staging.mindlogger.org/ (Win 10 // Chrome 91 )
