### ISSUE TITLE
The header image URL is displayed on the  items in the applet Library

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1035]
**Preconditions:**
The NIMH applet is shared with the library
**Steps to reproduce:**
1. Open the applet Library https://library-staging.mindlogger.org/
2. Find the HIMH applet
3. Expand the applet activity level
4. Look at the items

**Actual result:** The header image URL is displayed on the items in the applet Library
![2021-05-28_10-15-24.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/30ed5096-bb67-41ce-801d-6790019ac24b)
**Expected result:** The header image URL is not displayed on the  items in the applet Library. Only question text should be shown

**Environment:**
https://library-staging.mindlogger.org/#/?lang=en_US
Win 10//  Chrome 91

**Comment by natalia-muzyka** [comment]
The issue is fixed
https://www.screencast.com/t/iat3JTk4

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.77
