### ISSUE TITLE
The applet with transferred from library activities can't be saved on the admin panel

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1041]
**Preconditions**
The user is not logged in to the applet library/admin panel

**Steps to reproduce**
1. Open a site http://library-staging.mindlogger.org/
2. Add any applet to the cart
3. Proceed to the cart page
4. Click the "Add to applet builder" btn
5. Log in (geria.test1@yahoo.com // 7clCm7D5)  
6. Select add to the existing applet
7. Save the applet on the admin panel with the "Save to dashboard" button
8. Observe the result

**Actual result**
The applet with transferred from library activities can't be saved on the admin panel
Reproducibility 3/5

**Expected result**
The user can add selected activities to the existing applet and save it successfully as per requirements
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/85

**Video**
https://images.zenhubusercontent.com/189080374/b63c753c-459b-40b8-8dee-e5a629fd88d6/non_auth_both_dont_save_add_to_existing.mp4

**Note**
Reproduced also with previously logged in on the applet library user 
geria.test1@yahoo.com // 7clCm7D5
geria.test@gmail.com // 123456

**Environment**
https://admin-staging.mindlogger.org/
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.77

**Comment by natalia-muzyka** [comment]
**The issue is reproducible with applet "Applet_sub_scale"**
**If I manually delete the subscale from the  "Applet_sub_scale" in the applet builder then I can save an applet to the dashboard.**

Video: https://www.screencast.com/t/fsI1BAlz

Not reproduced with "A a nice applet"
Accounts:
geria.test1@yahoo.com // 7clCm7D5
qatl.customer@protonmail.com // 3FuuFz60

**Comment by Sshetty2** [comment]
https://github.com/ChildMindInstitute/mindlogger-applet-builder/pull/385

**Comment by natalia-muzyka** [comment]
The issue is fixed
https://www.screencast.com/t/GTj52mxOHH

Environment:
geria.test1@yahoo.com // 7clCm7D5
qatl.customer@protonmail.com // 3FuuFz60
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.77
