### ISSUE TITLE
Update "MRN" Row in export to "Secret User ID" 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1042]
Update "MRN" Row in export to "Secret User ID" 
Applet Library Items - Update "Question" to "Prompt"

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/0fab1511-b738-47af-a4b1-986f3b585cf9)

**Comment by natalia-muzyka** [comment]
1) MRN row is replaced by secret_user_id as expected
2) For the transferred Applet Library applet the "Question" isn't updated to "Prompt"
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a0392cd2-3e31-490b-ac73-3ed907228aa0)
Video: https://www.screencast.com/t/tKF012Jk39

**Comment by natalia-muzyka** [comment]
Fixed: For the transferred Applet Library applet, the "Question" is updated to "Prompt"
https://www.screencast.com/t/TXzPflrjPV

Environment
https://admin-staging.mindlogger.org/
