### ISSUE TITLE
Draw Coordinates Time Stamp

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1043]
As an admin, I want to see the timestamp of every line the user drew so that I can measure how long it took a user to draw from point A to point B

Requirements 
- Once the user presses on the screen, the system should start recording on a per pixel level: 
1. X coordinate 
2. Y coordinate 
3. Timestamp 
- These fields should be added to the admin panel export for each user's data set each field should be a row 
- Draw item on mobile should recognize taps. Right now the user needs to move slightly to 'dot a i" 
- Collect screen pressure data from apple pen and iPhone 6s or higher

**Comment by WorldImpex** [comment]
Export x, y, timestamp and line_number in admin panel is completed already

**Comment by natalia-muzyka** [comment]
**Issues:**
Fixed - The SVG file (drawing response) is missing in the data export [#1284](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1284)
Fixed - Draw item on mobile doesn't recognize taps [#1991](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1991)

**Comment by natalia-muzyka** [comment]
Video: https://www.screencast.com/t/G9RNpTvl
Screenshot: ![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/53372379-7c05-4022-a6b3-36083b6867bd)

Verified on:
ML v0.17.51 (staging)
Pixel 2 // Android 11
Pixel 3 XL // Android 10
iPhone 6s // iOS 14.4
iPhone 8 Plus // iOS 14.3
iPhone XS // iOS 15
Samsung Galaxy Tab S6 SM-T865 // Android 9.0 + S Pen
iPhone 8 // iOS 12.3.1 
iPhone SE (2020) // iOS 14.2
Samsung Galaxy S7 // Android 8.0
Samsung Galaxy S20 // Android 11

@WorldImpex @devbtech could you clarify, please, is this a correct timestamp format?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/aa8aa0e5-059f-41a1-b8be-a0c34818e22b)

**Comment by natalia-muzyka** [comment]
@devbtech could you clarify, please, is this a correct timestamp format?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/aa8aa0e5-059f-41a1-b8be-a0c34818e22b)

**Comment by natalia-muzyka** [comment]
Timestamp format: Verified as fixed:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/836ed0d2-9824-462e-b84c-31731f82c58e)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 95.0.4638.54 
macOS 11.0 // Chrome 95.0.4638.54 // Safari 14.0.1
ML v0.17.57 (staging)
iPhone 8 // iOS 14
Samsung S7 // Android 8
Samsung S9 // Android 9
