### ISSUE TITLE
The message on cumulative screen is based on the score value instead of the percentage value after the "Percentage correct" option was selected on admin panel

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1058]
**Preconditions**
The admin panel is opened https://admin-staging.mindlogger.org/
The user is logged in snakessqa@gmail.com // 123456
The applet builder is opened (creating a new applet)
The mobile application is installed and launched, the user is logged in

**Steps to reproduce**
1. Create a new activity with at least one item that has an option scores
2. Create a new Cumulative Score item and set: 
- "at or above" options,
- "Percentage Correct" output type,
- "Good" Message at or above
- "Bad" Message out of range
3. Set a positive whole number score
4. [mobile app]: Start an assessment, select options scores so that the
- percentage value will be higher than the entered score value on the admin panel,
- options score(sum) will be lower than the entered score value on the admin panel
5. Complete the assessment 
6. Pay attention to the message displayed on the summary screen

**Actual result**
The message on the cumulative screen is based on the score value instead of the percentage value after the "Percentage correct" option was selected on the admin panel

**Expected result**
The message on the cumulative screen is displayed according to the selected "Output type" + "Score" option on the admin panel

**Attachment**
Video: https://www.screencast.com/t/5EOYM7zyeg
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ac2c2e9c-39ac-472a-b4e4-9b639c04d77a)

**Environment**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91
ML v 0.16.26 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3

Accounts:
snakessqa@gmail.com // 123456
geria.test@yahoo.com // 3FuuFz60

**Comment by Sshetty2** [comment]
https://github.com/ChildMindInstitute/mindlogger-app/pull/1814

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/zPeEmIrSVfUy

ML v0.17.3 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 6 Plus // iOS 12.3.1
