### ISSUE TITLE
Textbox isn't appropriate for Keywords 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1060]
Steps to recreate 
1. Sign into admin on staging (wavanauken+13@gmail.com/ abcd123) 
2. Try to publish an applet 
3. See Results

Expected: Textbox to enter keywords. Ghost text in textbox shows "Keywords:" 
Actual: The textbox functionality works as expected but there is a expand/ collapse button. Ghost text should be "Enter Keywords" 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/91544c01-c984-4c8e-8d61-79d8967c125c)

**Comment by natalia-muzyka** [comment]
The issue is fixed
https://www.screencast.com/t/fOO6rfs5q8

Environment
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91
