### ISSUE TITLE
The compliance chart dots within the same date(short time period) are overlapped each other

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1065]
**Preconditions**
The mobile app is installed and launched
The user is logged in to geria.test@yahoo.com // 3FuuFz60

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in to geria.test@yahoo.com // 3FuuFz60
3. In the mobile app complete the same assessment twice
4. On admin panel proceed to the user's DataViz
5. Pay attention to the screen

**Actual result**
The compliance chart dots within the same date are overlapped each other

**Expected result**
The compliance chart dots within the same date aren't overlapped each other and displayed separately

**Attachment**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ebff22d9-987c-4195-8bde-42eb0820d11a)
 ![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e9e8027c-4612-412e-8e2e-b1cbf3b382ed)

**Environment**
https://admin-staging.mindlogger.org/
Account: geria.test@yahoo.com // 3FuuFz60
Applet: Retest subscale 2 (Applet password: Qwe123!!!)

**Comment by Matchdev120** [comment]
@natalia-muzyka I'm not sure if this is a real issue.

We built the chart with response date and time. If user completed the same activity twice at 8:10 am and 8:12 am, then the 1st dot would be very close to the 2nd dot.

**Comment by natalia-muzyka** [comment]
@Matchdev120 
They are still overlapped because I can't set start + end time within the same day.
https://www.screencast.com/t/rItkGWf88d
Was there any decision about what is the shortest period of time that the user can set?

**Comment by natalia-muzyka** [comment]
@Matchdev120 could you help me, please? 
Dots are still overlapped because I can't set start + end time within the same day.
Was there any decision about what is the shortest period of time that the user can set?

**Comment by natalia-muzyka** [comment]
@Matchdev120 @WorldImpex 
Dots are still overlapped because I can't set start + end time within the same day.
Was there any decision about what is the shortest period of time that the user can set?

**Comment by WorldImpex** [comment]
@natalia-muzyka No the time range was only supposed to be for same-day date ranges in order to better show the overlaps so I think this should be kicked back to sprint backlog

**Comment by natalia-muzyka** [comment]
Works as expected now.
There is the ability to set a time range within the same day and UI works correctly.
https://www.screencast.com/t/PtpiPWdSVL

Environment
https://admin-staging.mindlogger.org/
Account: geria.test@yahoo.com // 3FuuFz60
Applet: Retest subscale 2 (Applet password: Qwe123!!!)
