### ISSUE TITLE
After selecting the "Show Subscale Results" all the results are shown instead of the results from the selected data entry point

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1066]
**Preconditions**
The mobile app is installed and launched
The user is logged in to geria.test@yahoo.com // 3FuuFz60
The user has taken the same assessment at least twice.

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in to geria.test@yahoo.com // 3FuuFz60
3. On the admin panel proceed to the user's DataViz
4. Click one of the compliance dots
5. Click the "Show Subscale Results"
6. Pay attention to the screen

**Actual result**
After selecting the "Show Subscale Results" all the results are shown instead of the results from the selected data entry point

**Expected result**
If the user selects "Show Subscale Results" then update the subscale tables to show the results from that data entry point.

**Attachment**
https://images.zenhubusercontent.com/103405139/6edf979c-d812-48cb-b418-84483ac753de/show_subsc_res.mp4

**Environment**
https://admin-staging.mindlogger.org/
Account: geria.test@yahoo.com // 3FuuFz60
Applet: Retest subscale 2 (Applet password: Qwe123!!!)

**Comment by natalia-muzyka** [comment]
@mtg137 
Displaying in the "Subscale Scores" changes, but subscale responses (dots) are still displayed for all entries
https://www.screencast.com/t/fdkj9dlR

@WorldImpex could you clarify, please, am I right with the expected result? Dots(responses) that aren't related to particular data entry should be hidden and only the related responses should be displayed?

Environment
https://admin-staging.mindlogger.org/
Account: geria.test@yahoo.com // 3FuuFz60
Applet: Retest subscale 2 (Applet password: Qwe123!!!)

**Comment by WorldImpex** [comment]
@natalia-muzyka Yes the dots on the compliance chart should always been shown so the user can try different points in time but the response data should be filtered to the selected compliance dot

**Comment by techdev137** [comment]
subscale table needs to be shown from selected data entry point.
but we can show all responses in item tables ( ex: slider item ).

https://images.zenhubusercontent.com/189080374/0641256f-de09-4b02-a7e4-c194489450fc/record.mov

**Comment by natalia-muzyka** [comment]
@mtg137 but we should display only the responses that related to the selected compliance chart dot, as Wil mentioned in the comment above

**Comment by WorldImpex** [comment]
@natalia-muzyka For MVP, I think we can leave the response options shown over the time

**Comment by natalia-muzyka** [comment]
ok, thank you both,
I'll close this ticket
