### ISSUE TITLE
Record Start, Next and End Events in Data Export

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1067]
As an admin, I want to see when a user started an activity, when the user hit next for each item and when the user ended the activity so that I can better understand timing as the user responded to the activity 

Requirements
- In the data export, show the start, end and everytime the user hit next with a timestamp

**Comment by natalia-muzyka** [comment]
The new "hit_next_time" column in the CSV report is empty after completing the existing or newly created activity:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/28468304-e955-4ad0-9b39-eff98ce49d8e)

Environment:
ML v0.17.33 (staging)
https://admin-staging.mindlogger.org/
alyssia_ml@protonmail.com	// qwertyuio
applet: start, next, end events data
loui_ml@protonmail.com // 12345678
applet: based on cumulative score
applets password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
**Issues:**
Fixed - The "hit_next_time" timestamp isn't reflected in the CSV report if user completed the activity on webapp Fixed - [#1286](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1286)
Fixed - The "hit_next_time" timestamp is displayed in a different timezone and format that the "activity_start_time" and "activity_end_time" [#1287](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1287)

**Comment by natalia-muzyka** [comment]
Works as expected.
Verified on:
Samsung S7 // Android 8.0	
Samsung S9 // Android 9	
iPhone 6 Plus // iPhone 8 // iOS 12.4	
iPhone SE (2020) // iOS 14.2
iPhone XS // iOS 15.0"
Win 10 // Chrome 95.0.4638.54 
macOS 11.0 // Chrome 95.0.4638.54 // Safari 14.0.1
