### ISSUE TITLE
[UI] DataViz issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1089]
1) The version number overlays the items block (left) after selecting start time + end time within a day
https://www.screencast.com/t/8vSg6E05
https://www.screencast.com/t/1UUIj0zFtGo
https://www.screencast.com/t/TYoWByeMCBS

2) The versions numbers are overlapping each other
https://www.screencast.com/t/xodOZSIU

3) The hint with an activity title isn't shown after hovering if the activity name is too long for displaying (no ability to see the whole activity name)
https://www.screencast.com/t/FS7d5lI2

4) The dots (responses) aren't displayed in the right timeline (the context menu and hints are displayed shifted away from these dots)
https://www.screencast.com/t/qPzDpVVVB

5) The clicking on the dot automatically expands/collapse the activity instead of showing up a context menu with options Review and Show subscale results
https://www.screencast.com/t/qcZ9vCgN5M

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91
macOS Big Sur 11.0 // Chrome 91 // Safari

account: 
geria.test@yahoo.com // 3FuuFz60
Applet: retest subscale 2 (1)
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Fixed:
#1 https://www.screencast.com/t/qW7s72rxk
#2 (as there is an ability to set a time range within the same day)
#3 https://www.screencast.com/t/rIkWxat6aGUq
#4 https://www.screencast.com/t/qv7FpFuh7Gps
#5 in the scope of this issue, @mtg137 could you add, please an automatically expand action after clicking the "Show subscale results" option if the box is collapsed(look at the video)? https://www.screencast.com/t/O35aXxUm7z

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91
macOS Big Sur 11.0 // Chrome 91 // Safari

account:
geria.test@yahoo.com // 3FuuFz60
Applet: retest subscale 2 (1)
Applet password: Qwe123!!!

**Comment by techdev137** [comment]
sure, I'll make it to be expanded automatically.

**Comment by natalia-muzyka** [comment]
@mtg137 

1) expand/collapse works well except for the latest item. It is automatically collapsed right after displaying:
https://www.screencast.com/t/nGxxdE8p5jdk
Can we fix this?

2) one more thing that would be great to fix in the scope of this ticket:
To show 3 decimals instead of 10 for the score value
https://www.screencast.com/t/AugAEbV3

Win 10 // Chrome 91.0.4472.124

**Comment by techdev137** [comment]
@natalia-muzyka could you please let me know your account info?

**Comment by natalia-muzyka** [comment]
@mtg137 
both issues from my last comment are reproducible on this account:
geria.test@gmail.com // 123456
applet: check subscale
activity: average test
applet password: Qwe123!!!

**Comment by techdev137** [comment]
ok. thanks.

**Comment by natalia-muzyka** [comment]
1) expand/collapse fixed

2) decimals:
- for the latest score there are still 10 characters instead of 3 
https://www.screencast.com/t/9rMhahRLm0r
- for the natural number (score), there are unnecessary decimals "000"
https://www.screencast.com/t/KM02E7zRk3

geria.test@gmail.com // 123456
applet: check subscale
activity: average test
applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/Qyex0bjD
