### ISSUE TITLE
Keep protocol on the app when downloaded

### ISSUE THREAD

**Issue by satra** [ChildMindInstitute/mindlogger-admin-OLD-Vue#109]
As an editor, I want to download the protocol without the builder resetting so that I can sample what I have created in-app and make changes in the builder at the same time. 

Requirements: 
* Allow the user to download the protocol without the builder resetting itself 

** Below is original ask for reference** 

Currently the protocol disappears when one hits the download button. It would be great if:

a. the protocol could remain in the app
b. there was an open protocol option where the downloaded protocol could be uploaded and re-edited. (Being developed in #201 & #121)

**Comment by WorldImpex** [comment]
@satra Could you provide a screen record of what you are describing? I am having trouble understanding. Thanks!

**Comment by henryrossiter** [comment]
I believe @satra is referring to the Protocol Builder. When a user clicks 'Download Schema', the builder resets.
