### ISSUE TITLE
invalid translation files

### ISSUE THREAD

**Issue by peterpeterparker** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1097]
### Issue

The translation files, `en_US.js` and `fr_FR.js`, are invalid JavaScript files because they contain multiple duplicate declarations.

For example, two times `days: 'days'` or `frequency: 'Frequency',` etc.

<img width="1512" alt="Capture d’écran 2021-07-01 à 09 16 50" src="https://user-images.githubusercontent.com/16886711/124082525-1be10200-da4d-11eb-9fbb-5a048b012dc0.png">

**Comment by natalia-muzyka** [comment]
@jj105 @WorldImpex could anyone help me with checking this ticket?

**Comment by WorldImpex** [comment]
@devbtech Please check this and confirm production has been updated

**Comment by devbtech** [comment]
@WorldImpex I just confirmed, this is fixed.
