### ISSUE TITLE
Show Lazy Loader when Exporting Large Response Data 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1102]
When exporting large files of response data it can take 10 seconds or so, we should show a lazy loader to the user with the message "Please wait. This could take up to 1 minute to download."

**Comment by natalia-muzyka** [comment]
The lazy loader is hidden before the ZIP is downloaded, waiting for deploy with fix
https://www.screencast.com/t/tScVrr2T

**Comment by natalia-muzyka** [comment]
works as expected
https://www.screencast.com/t/dLgPq49JI

Environment:
Win 10 // Chrome 92.0.4515.107 
https://admin-staging.mindlogger.org/
