### ISSUE TITLE
The prize activity builder is presented after an attempt to open the activity that was created after the token prizes were added

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1105]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in geria2.test@gmail.com // McgzF127
3. Create a new applet
4. Create an activity with token prizes
5. Add a new activity in the same builder
6. Click the edit button on the newly created activity
7. Pay attention to the screen

**Actual result**
The prize activity builder is presented after an attempt to open the activity that was created after the token prizes were created.

**Expected result**
The selected activity builder is displayed after clicking the edit button. The PrizeActivity shouldn't be presented in the applet builder and on the dataviz.

**Video:** https://www.screencast.com/t/ZxNj7a7T

**Environment**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124

**Comment by Matchdev120** [comment]
@natalia-muzyka Just tested your account but `Drawing Item` activity is a normal activity and not a prize activity.

Prize activity is always not visible at all.

**Comment by natalia-muzyka** [comment]
@Matchdev120 the issue is still reproducible:
applet: "subscales (2)"
activity: "all"

video: https://www.screencast.com/t/NURV0FsXjpcK
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/AvRmkzE4hXm

Environment
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
