### ISSUE TITLE
The activity that was created after the activity with token prizes isn't copied/deleted after clicking the copy/delete button

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1119]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in geria2.test@gmail.com // McgzF127
3. Create a new applet
4. Create an activity with token prizes
5. Add a new activity in the same builder
6. Click the copy button on the newly created activity
7. Click the delete button on the newly created activity
8. Observe the result

**Actual result**
The activity that was created after the activity with token prizes can't be copied or deleted. 

**Expected result**
The activity that was created after the activity with token prizes can be copied or deleted successfully

**Note**
Reproduces for a copied or manually created activity. Can be fixed after clicking the Edit button and turning back to the Applet builder page.

**Video**: https://www.screencast.com/t/Ahl2kfJ2eh8

**Environment**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
applet: Test Applet
password: Qwe123!!!

**Comment by BarrySunderland** [comment]
activities listed in the protocol builder are filtered to only display activities without a prize

displayed here:
https://github.com/ChildMindInstitute/mindlogger-applet-builder/blob/ecbf1edb8c26b213dae9bc05d11e6d9252b7fb0a/src/components/ProtocolBuilder/ProtocolBuilder.vue#L74

filtered here:
https://github.com/ChildMindInstitute/mindlogger-applet-builder/blob/ecbf1edb8c26b213dae9bc05d11e6d9252b7fb0a/src/components/ProtocolBuilder/ProtocolBuilder.vue#L207

**Comment by natalia-muzyka** [comment]
The issue is partly fixed (deleting is possible only by the second click on the "delete" button). 
And there is a new issue, related to deleting the second activity:
After deleting the second activity and saving the applet, the token prizes from the first activity are also removed.
Reproducible for manually created and copied activity.
Video: https://www.screencast.com/t/ToTPGbYJ

Environment
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
geria2.test@gmail.com // McgzF127
applet: Token prizes
password: Qwe123!!!

@mtg137 Please let me know if you want to create a separate ticket for a new issue or you want to work with it in scope of current ticket

**Comment by techdev137** [comment]
@natalia-muzyka I can work with it in scope of current ticket. thanks.

**Comment by natalia-muzyka** [comment]
Verified as fixed
Environment
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
geria2.test@gmail.com // McgzF127
applet: Test, token prizes
password: Qwe123!!!
