### ISSUE TITLE
Nickname Field to show in an activity 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1155]
As an admin, I want to enter an identifier so that activities will show that user's name within activities 

Requirements 
* Add a field to the invitation called [Nickname] 
* Allow the user to enter [Nickname] into the question text field so that on mobile and webapp each specific user's name will show 
* If the user does not have a nickname, then do not show the field. ie Hi, How are you today? instead of Hi [Nickname], How are you today? - Just omit the nickname 
* The goal here is so that the editor can enter Hi [Nickname], How are you today? and on each user's device it will show a personalized greeting like Hi Johnny Appleseed, How are you today?" 
* Add Nickname field to user tab and have the field editable (add, edit and delete) 
* This effort is for webapp and mobile

**Comment by natalia-muzyka** [comment]
@WorldImpex @jj105 
Could anyone clarify, please, the next:
The editor needs just to enter "Hi [Nickname], How are you today" as a regular text into the "Text creator"?
And after saving the applet, user will see a prompt with his/her nickname on the webapp/mobile app?
Currently, it doesn't work in this way:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/07eb7992-6d09-40bb-8213-73b61234964d)

**Comment by WorldImpex** [comment]
@natalia-muzyka This field needs to be filled out for the [Nickname] field to be systematically filled out 

![image](https://user-images.githubusercontent.com/22243307/148066549-4f96246e-cee7-4c0e-8bc0-efc40ab13001.png)

**Comment by natalia-muzyka** [comment]
@WorldImpex sure, user has a nickname. But it is still missing on webapp. I thought maybe I do something wrong when entering the sentence in the text creator, so I wanted to clarify.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f9ae715e-f4e0-4caa-8d49-a9deb5882161)

**Comment by natalia-muzyka** [comment]
@jj105 
https://web-staging.mindlogger.org/ (v0.6.0)
account: bernard_ml@protonmail.com	qwe123!!!
user: loui_ml@protonmail.com	12345678
applet: mix applet (bernard)
activity: mix activity (nickname))

**Comment by natalia-muzyka** [comment]
@WorldImpex @jj105 

the "Secret user id" field became editable as well, do I miss some other tickets regarding the Secret ID field?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7a6d77f0-6016-4ed7-82c3-5420d80809aa)

**Comment by WorldImpex** [comment]
No that is bug @natalia-muzyka but I think we can leave it that way

**Comment by natalia-muzyka** [comment]
Works as expected. Checked on:
Win 10 // Chrome 97.0.4692.99 
macOS 10.15 // Chrome 97.0.4692.71
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
ML v0.18.39 staging
Samsung Galaxy S7 // Android 8
iPhone X // iOS 14.6
Samsung Galaxy S9 // Android 10
iPhone XS // iOS 15.2
