### ISSUE TITLE
The token values are cumulated for all the users within one account and can't be filtered by user secret id

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1156]
**Preconditions**
The user is logged in to the admin panel
https://admin-staging.mindlogger.org/
geria2.test@gmail.com // McgzF127
The applet with an activity that contains token values and user secret id item type is created
(e.g.. applet: TokenLogger Sleep geria2
Applet password: Qwe123!!!)
The mobile app is installed and launched, the user is logged in

**Steps to reproduce**
1. Complete the activity twice with a different user-id
2. Proceed to the user's DataViz / "Tokens" tab on the admin panel
3. Filter the data by the secret id
4. Observe the result

**Actual result**
The token values are cumulated for all the users within one account and can't be filtered by user secret id

**Expected result**
The data are filtered according to the selected secret id values (as on the "Responses" tab)

**Video:**
https://www.screencast.com/t/UiJuUVEa

**Environment**
https://admin-staging.mindlogger.org/
account (owner): geria2.test@gmail.com // McgzF127
applet / activity: TokenLogger Sleep geria2
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
version 1 of tokenlogger

**Comment by natalia-muzyka** [comment]
Close ticket due to the updated TL.
