### ISSUE TITLE
Fake user's data can't be deleted

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1170]
**Preconditions**
The user is logged in on the admin panel 
https://admin-staging.mindlogger.org/
geria2.test@gmail.com // McgzF127
There is an applet with automatically created Fake user after completing the assessment via the public link (that doesn't require a login) (applet: webapp test (1))

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Click the "View users" button on the applet with available Fake user (webapp test (1) / password: Qwe123!!!)
3. Click the "Edit access" button on the Fake user
4. Click the "Remove Fake's data and access to applet"
5. Enter the applet password (Qwe123!!!) and submit
6. Pay attention to the screen
7. Refresh the page and try to remove Fake's user data again
8. Observe the result

**Actual result**
Fake user's data can't be deleted

**Expected result**
As per the [requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/338):
The data of the fake user should be able to be deleted.

**Video:** https://www.screencast.com/t/txrjm5KXXkI

**Environment**
https://admin-staging.mindlogger.org/
owner: geria2.test@gmail.com // McgzF127
applet: webapp test (1)
password: Qwe123!!!
Win 10 // Chrome 92.0.4515.107

**Comment by natalia-muzyka** [comment]
The issue is still reproducible
video: https://www.screencast.com/t/aqETgqbH7Iy

Environment
https://admin-staging.mindlogger.org/
owner: geria2.test@gmail.com // McgzF127
applet: webapp test (1)
owner: johndoeregress@protonmail.com // 12345678
applet: public link (export)
password: Qwe123!!!
Win 10 // Chrome 92.0.4515.131

**Comment by jj105** [comment]
@natalia-muzyka could you please double check it when you get chance? 
( I think there was something wrong in backend deployment when you were testing issue. )

**Comment by natalia-muzyka** [comment]
verified as fixed
https://www.screencast.com/t/Iouk3YIYV

Environment
https://admin-staging.mindlogger.org/
owner: geria2.test@gmail.com // McgzF127
applet: webapp test (1)
owner: johndoeregress@protonmail.com // 12345678
applet: public link (export)
password: Qwe123!!!
Win 10 // Chrome 92.0.4515.131
