### ISSUE TITLE
The Summary(calculation) block is missing for the pediatric screener on DataViz

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1176]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: johndoeregress@protonmail.com // 12345678
3. Create a new applet with github schema:
https://raw.githubusercontent.com/ChildMindInstitute/Pediatric_screener_applet/master/protocol/HBN_PMHS/HBN_PMHS_schema
4. Complete the activity on the mobile app (Self Report 11-17)
5. Proceed to the user's DataViz 
6. Pay attention to the responses

**Actual result**
The Summary(calculation) block is missing for the pediatric screener on DataViz

**Expected result**
The Summary(calculation) block is displayed on DataViz for all the completed activities that contain the cumulative item as per the [requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1030)

**Screenshot:** https://www.screencast.com/t/Zjg0azvD4Erj

**Environment:**
https://admin-staging.mindlogger.org/
johndoeregress@protonmail.com // 12345678
applet: Mental Health Screening Survey: English
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
HBN has created a new ped screener using the applet builder so developer efforts have stopped supporting the GitHub version of ped screener

**Comment by natalia-muzyka** [comment]
Closed according to the comment above.
