### ISSUE TITLE
Video Export Differences between iOS and Android 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1186]
1. On Android and iOS the uploading audio/video is implemented with a difference: iOS automatically compresses audio and video files, Android doesn't. Because of this in case of uploading a large file(10 Mb+), Android uploads the original data and it takes more time. If the admin wants to export a user's data there could be only CSV file downloaded or the large file will be skipped.

2. Video quality on iOS is not good 

On the attached video I use a video file with 47Mb size.
https://www.screencast.com/t/y5kX4IyJq

**Comment by natalia-muzyka** [comment]
The video export is similar now. Close the ticket.
