### ISSUE TITLE
The markdown text is displayed raw in the response option on the DataViz

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1189]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: avani_ml@protonmail.com // 12345678
3. Create a new applet with at least one activity
4. Add at least one radio item and specify the markdown text (text creator), e.g.:
Lorem *ipsum* ++dolor++ ==sit== > amet
5. Complete the activity on the mobile app
6. Proceed to the user's DataViz
7. Pay attention to the response options

**Actual result**
The markdown text is displayed raw in the response option on the DataViz

**Expected result**
The markdown text is displayed accordingly to the markdown settings in the response option on the DataViz

**Screenshot:**
https://www.screencast.com/t/1Vm7XEnJcFOQ

**Environment**
https://admin-staging.mindlogger.org/
account: avani_ml@protonmail.com // 12345678
applet / activity: all item types / multiple
Applet password: Qwe123!!!

**Comment by HarutQA** [comment]
Works correctly.

**Comment by natalia-muzyka** [comment]
The markdown is still not supported for a few elements:
text alignment, quote, table and audio:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7a8a58a1-3a27-4196-88cf-1a4481a392e3)

Environment:
https://admin-staging.mindlogger.org/
geria2.test@gmail.com	// McgzF127
Win 10 // Chrome 93.0.4577.82 
applet / activity:
All (1) // markdown test

**Comment by natalia-muzyka** [comment]
Verified as fixed
Video: https://www.screencast.com/t/ukafr75c

Environment:
https://admin-staging.mindlogger.org/
geria2.test@gmail.com // McgzF127
Win 10 // Chrome 93.0.4577.82
applet / activity:
All (1) // markdown test
