### ISSUE TITLE
Editing Activities of an Applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#119]
As an editor, I want to edit activities that are part of my applet so that I can update or change questions for the applet. 

Description: An editor needs the ability to revise an activity within an applet that is currently in use. This change made by the editor would retain the historical data from the previously taken activity and then record the new data from the revised activity. The editor would edit the activity within the admin panel. 

Requirements
- Editors can change any part of the protocol that is covered in the activity set builder: 
   - Protocol Name & Description 
   - Activity Name, Description, Preamble, Shuffle item order, and Allow items to be skipped, 
   - Item Name, Description, Question and Input Type
- Added items are simply added to the protocol
- Deleted items are removed from the protocol 
- Edited items are updated to the new content inputted
- User is shown a version number and the history of changes is displayed on admin about the applet 
   - The applet starts at 1.0 and moves up 1.01, 1.02, etc 
   - Between each version, the history of changes is shown 
      - *Applet Name* name  was changed to *New Name* 
      - *Applet name"'s  description has changed to *New Name* 
      - *Activity Name* changed to *New Name* 
      - *Activity Name* was deleted
      - *Activity name's*  description has changed to *New Name*
       - *Activity name's* preamble was changed to *New preamble* 
       - Shuffle of *Activity's Name* order was turned on 
       - Shuffle of *Activity's Name* order was turned off 
       - Allow skipping of items turned on for *Activity's name* 
       - Allow skipping of items turned off for *Activity's name* 
       - *Question name* added with *input name type* 
       - *Question name* deleted with *input name type* 
       - *Question name* changed to *New question name* 
       - *Question name* changed from *input name type* to *input name type*
                   - Changed to radio, multiple choice or slider show the new input options (i.e. Multiple choice - 1. Ate breakfast 2. Ate Lunch 3. Ate Dinner) 
                   - All other options just show the input type name change 
       - Item name changed from *item name* to *new item name* 
       - *Item name's* description was changed from *item name's description* to *new item name's description* 
       - *Item name* was removed  
- Save Changes to Existing Applet: By saving a protocol that is in progress (applet has users and schedules defined), the applet is overwritten with the new data.
- The existing data is still stored with the original criterion
- Changes are not made to the users or schedule of the original applet
- The user would see the 'same applet' but with the new changes made

Acceptance Criteria
Given I am an editor
When I select an applet from my dashboard
Then I am able to edit activities and items of that applet 

Given I am an editor 
When I am editing an activity 
Then I am able to add and remove items as well as change content within the original items.

**Comment by sergeysemenuta** [comment]
Works as expected regarding the Requirements
Checked on https://admin-staging.mindlogger.org/
