### ISSUE TITLE
The duplicated info(graph) is displayed on the tokens tab after editing the applet

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1190]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: avani_ml@protonmail.com // 12345678
3. Create an activity with token values "TokenLogger School" 
applet schema: https://raw.githubusercontent.com/ChildMindInstitute/TokenLogger_school_applet/master/protocols/TokenLogger_school/TokenLogger_school_schema
4. Complete the activity on the mobile app
5. Proceed to the user's DataViz / Tokens tab
6. Pay attention to the screen
7. Edit an applet and save (e.g. change the applet description)
8. Proceed to the user's DataViz / Tokens tab
9. Compare the previous info with the current displaying

**Actual result**
The duplicated info is displayed on the tokens tab after editing the applet:
the tokens graph is bigger than the real quantity of the token, the tooltip shows duplicated responses.
The real token's quantity is correct on the graph and in the mobile app.

**Expected result**
The "Tokens" tab displays info accordingly to the user's responses and activity settings.

**Video:** https://www.screencast.com/t/H348aoLtHUt

**Environment:**
https://admin-staging.mindlogger.org/
account: avani_ml@protonmail.com // 12345678
applet: TokenLogger School, token values
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
UPD: 19/10/21
The issue is reproducible if the user copied an activity or use the radio + checkbox item.
The info graph is duplicated, though the tooltip and total amount displays the valid info.
Video: 
https://www.screencast.com/t/PZblknpq
https://www.screencast.com/t/skzNkC3hUqy

Environment:
https://admin-staging.mindlogger.org/
account: avani_ml@protonmail.com // 12345678
applet: TokenLogger School (1)
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
part of version 1 and we are now on verison2
