### ISSUE TITLE
[UI][Safari] The date values(x-axis) are shifted to the right on the DataViz "Tokens" tab 

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1194]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: geria2.test@gmail.com	// McgzF127
3. Complete on the mobile app or website any activity with token values (e.g. "TokenLogger School")
4. Proceed to the user's Dataviz / Tokens tab
5. Pay attention to the screen

**Actual result**
The date values(x-axis) are shifted to the right on the DataViz "Tokens" tab. The time range is displayed out of the chart.

**Expected result**
The date values(x-axis) are displayed accordingly to the x-axis positioning and selected time range on the DataViz "Tokens" tab.

**Screenshot:** https://www.screencast.com/t/13KCLWAH

**Environment:**
https://admin-staging.mindlogger.org/
macOS 10.15.6 // Safari 13.1.2 (15609.3.5.1.3)
geria2.test@gmail.com // McgzF127
applet: TokenLogger School, TokenLogger Sleep geria2
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
Libraries are not supported on Safari browser

**Comment by WorldImpex** [comment]
There hasn't been a good resolution for this ticket. We are starting a redesign effort so we are putting this bug on hold

**Comment by natalia-muzyka** [comment]
Close ticked due to updated TL.
