### ISSUE TITLE
User able to set the Timer and Idle Time at the same time

### ISSUE THREAD

**Issue by HarutQA** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1198]
Steps to reproduce
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: maddison_ml@protonmail.com / qwertyuio
3. Open "Calendar" screen
4. Create **TIME** Schedule on some day, for ex. 22.08.21/ 19:00 and save it
5. Open "Calendar" screen again
6. Choose the same day/time( 22.08.21/ 19:00) 
7. Create **IDLE** the same day/time( 22.08.21/ 19:00) and save it

Actual result
Both options(Time and Idle) are created in a same day and time

Expected result
User should not be able to set the Timer and Idle Time at the same time

**Comment by Matchdev120** [comment]
@WorldImpex would you please confirm this requirement?

I think users are not able to set Timer and Idle Time together for the same event and it works if they are different events even though the scheduled times are the same.

**Comment by WorldImpex** [comment]
@Matchdev120 Yes I agree.

**Comment by natalia-muzyka** [comment]
Not a bug as it is not possible to set up "Timer" and "Idle time" on the same event: https://www.screencast.com/t/CmgJPRw5Dptu
