### ISSUE TITLE
TokenLogger Charts Redesign 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1199]
As an admin, I want to see more graphically relevant data visuals related to TokenLogger so that I can make better decisions about a user's progress 

Requirements 
- This effort replaces the Frequency and Tokens tab that we have today. There will now only be one tab called "Frequency" 
- In this new tab on the data visualization, the user will have the option to switch between frequency and tokens 
   - Frequency has the option to show 3 different charts: 
      - Matrix View (what is shown by default when the user lands on the page)
      - Area Chart View
      - Bar Chart view
   - The icon changes the chart type and the word (frequency or tokens) changes the type of data being displayed 
- Each response option has its own color. 
   - The saturation of the color depends on how frequent the response option was select during that time period. 
      - The color saturation should be adjusted every time the user changes the time range (ie if the user moves from a day view to a week view then the highest frequency in the week view takes the most saturation) 
   - If the user has not responded during the time period shown then greyed out white should be used 
   - If the user has responded but not to that response option then show as white 
- Using the collapse icon on the left, the user can select from time ranges. There should also be an up and down arrow around that icon to allow the user to move forward and backward through the dates 
- If the user is looking at a month view then show the Sunday and Monday numbers bold with a line between them. Show the month and year next to the collapse icon 
- In a week view, show the days of the week (Monday, Tuesday, Etc). Also show the date range next to the collapse icon 
- If user is in day view, then show every hour. Allow the user to click an hour and see a 5 minute interval view 
   - Show time in 24 hour format 
- If the user hovers over the day & response option then tooltip the total frequency, average distress and impairment for that day.
Area & Stacked Bar chart
- If the user selects a response option in the chart then only show that response option in the chart type. If the user clicks again, then zoom the user back out to the full area or bar view 
- The color of the bar & area for each response option will always be the most saturated color 
Token chart 
- Time selection should remain the same 
- User is shown the cumulation of tokens over time 
- Show tooltip with +X amount of tokens earned for that day 
- The tokens graph should look like a desktop version of mobile 
![Screen Shot 2021-10-05 at 4.48.19 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/3b9ddaf3-07b2-4d18-bc4c-b976b567d6b1)
- [Design assets](https://docs.google.com/presentation/d/1siQMiOykHiJLFwisfkMJ30IvtsdfZ8_eIE6eKnhRU48/edit#slide=id.gcb08c228b9_0_135) (disregard the last slide with a mobile design)

**Comment by natalia-muzyka** [comment]
Works as expected.
Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.82 
macOS 10.15 // Chrome 98.0.4758.82 // Safari 13.1.2
