### ISSUE TITLE
"Save to dashboard" functionality error

### ISSUE THREAD

**Issue by HarutQA** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1200]
Steps to reproduce
1. Open a site https://admin-staging.mindlogger.org/
2. Tap on "Configure an Applet" button
3. Choose "Build an applet" variant
4. Create applet, add Activitie and item 
5. Press "Save to Dashboard"
 
Actual result
"Save to Dashboard" functionality do not works, user unable to save newly created applet

Expected result
User should be able to save applet into dash board

Environment:  MacBook Pro Version 14.0.3 

https://matter-lab.slack.com/archives/CDUG9H3J4/p1629389524013700

**Comment by Matchdev120** [comment]
@HarutQA It is not reproducible on my end.

Would you describe the steps in detail?

**Comment by HarutQA** [comment]
I have sent you the video of bug as a direct message on Slack, please take a look.

https://user-images.githubusercontent.com/88667535/130247097-b818f75a-65b4-43e8-929e-792f5c4a983a.mov

**Comment by HarutQA** [comment]
Works correctly. Fixed.
