### ISSUE TITLE
Set Notification time sheet on "Set a notification" field for Mac Safari works incorrect.

### ISSUE THREAD

**Issue by HarutQA** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1203]
Steps to reproduce.

1. Open https://admin-staging.mindlogger.org/#/login?nextUrl=%2Fdashboard%3Flang%3Den_US&lang=en_US
2. Log in. e.g. haruttsd@gmail.com/ harut91
3. Choose any Applet, e.g. Testing 4
4. Open Calendar, general or individual
5.Choose Activity name, try to set a notification

**Actual result**
There is no "Time sheet" on "Set a notification" field

**Expected result**

There should be a time sheet in set a notification screen.![Screen Shot 2021-08-23 at 19.11.27.png](https://images.zenhubusercontent.com/61125099ad96283f91ec1d29/8f6a1505-1cfd-4ca0-940f-cddfed58d05c)

**Comment by HarutQA** [comment]
The bug is actual.

**Comment by HarutQA** [comment]
Works correct. Perfect!

**Comment by natalia-muzyka** [comment]
The time picker isn't updated for:

1) Set Reminder
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9353cf88-1cb6-436c-b1a5-262a500284b9)

2) activity start / end time scheduling
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/0beb29bb-0361-4604-85c0-1c3c5cb00a69)

**Environment**
https://admin-staging.mindlogger.org/
macOS 11.0 // Safari 14.0.1

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/5YbdRf12OnuF

Environment
https://admin-staging.mindlogger.org/
macOS 11.0 // Safari 14.0.1
