### ISSUE TITLE
Prod "Score value" Minus value issue

### ISSUE THREAD

**Issue by HarutQA** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1208]
**Steps to reproduce**
1. Open https://admin-staging.mindlogger.org/#/login?lang=en_US
2. Log in. Example: haruttsd@gmail.com / harut91
3. Build an Applet
4. Choose "Radio button" option
5. Choose "Score value" for radio button 
6. set "Score value" minus value

**Actual result**
user is able to set minus value to "Score value" field.

**Expected result**
Should be impossible to set minus value for "Score value" field.

**Environment**
Macbook Pro Chrome Version 92.0.4515.159
![Screen Shot 2021-08-27 at 18.17.19.png](https://images.zenhubusercontent.com/61125099ad96283f91ec1d29/c26a4f95-837f-4cbf-adfd-00ab24872daf)

**Comment by WorldImpex** [comment]
This is default behvaior

**Comment by HarutQA** [comment]
ok, perfect.
