### ISSUE TITLE
UI updates to admin 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1209]
1. Replace 'surveys' with 'activities' 
![Resizer_16300965855284.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/7faf2643-6435-4409-802d-d251bda10b79)
2. Change text when an applet is being loaded into applet builder to - "Please wait for your applet to load"
![Resizer_16300965855282.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/7e6339aa-f623-4aa8-98c2-a19cbcf0fd96)

**Comment by HarutQA** [comment]
Works correctly.

![Screen Shot 2021-08-30 at 22.13.22.png](https://images.zenhubusercontent.com/61125099ad96283f91ec1d29/bc708d0e-aec7-4e1b-869e-63d38b4043d9)

Enviroment
MacBook Pro Chrome Version 92.0.4515.159
