### ISSUE TITLE
Update "Configure Applet" text to "Build/Edit an Applet"

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1213]
![mindlogger-admin (2).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/cd91de4a-05d2-46ae-8632-d0f66eb4b732)

**Comment by natalia-muzyka** [comment]
The "Configure Applet" button text  is updated to "Build/Edit an Applet"
Screenshot: https://www.screencast.com/t/PRv5lJIeD

Verified on:
Windows 10 x64 // Chrome 92.0.4515.159

**Comment by natalia-muzyka** [comment]
@Matchdev120 The button text is changed to the previous version after the weekend (on staging).
On prod we have an updated text.

Environment:
https://admin-staging.mindlogger.org/
Windows 10 x64 // Chrome 94.0.4606.61 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/98398062-042b-45c1-aac5-36f376776dce)

**Comment by Matchdev120** [comment]
@natalia-muzyka While merging PRs, the button text is changed again. I'll fix it now.

**Comment by natalia-muzyka** [comment]
Verified as fixed
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1a835c1d-73b9-4ebe-9524-63de3433e00e)

Environment:
https://admin-staging.mindlogger.org/
Windows 10 x64 // Chrome 94.0.4606.61
