### ISSUE TITLE
 Notification issue

### ISSUE THREAD

**Issue by HarutQA** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1217]
Steps to reproduce
1. Open https://admin-staging.mindlogger.org/#/dashboard?lang=en_US
2. Log in. Example: haruttsd@gmail.com / harut91
3. Choose any applet, e.g. TokenLogger School
4. Open "Individual" or "General" calendar
5. Choose date and set notification

Actual result
There is no notification on phone device at the corresponding time

Expected result
There should be a notification on mobile device.

Environment
Redmi note 9 /Android
iPhone 11 Pro /iOS

**Comment by jj105** [comment]
@HarutQA is it a prod notification issue or staging notification? ( I am seeing that you mentioned admin-staging.mindlogger.org )

**Comment by HarutQA** [comment]
@jj105 This is staging issue.

**Comment by HarutQA** [comment]
Fixed, works correctly.
