### ISSUE TITLE
[PROD] Transferring Ownership an applet did not work

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1247]
Steps to recreate 
1. Log into admin 
2. Transfer ownership from one account to another 
3. See results 

Expected: The new owner sees the applet and can action it on their own admin panel 
Actual: The old owner still sees the applet and cannot do anything with it. The new owner does not see any change on their owner account

**Comment by natalia-muzyka** [comment]
@WorldImpex I'm not able to reproduce this issue.
Is there a specific account that I can test as well?
Video: https://www.screencast.com/t/9vsscEpk

Environment:
https://admin.mindlogger.org/
Win 10 // Chrome 93.0.4577.82 
macOS 11.0 // Safari 14.0.1
geria.test@gmail.com	// 123456
johndoeregress@protonmail.com	// 12345678

**Comment by WorldImpex** [comment]
Waiting on stakeholder to confirm and then I will close @natalia-muzyka
