### ISSUE TITLE
Add Password Warning to Applet 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1250]
"Please ensure this password is stored securely outside of MindLogger. This password can never be changed or retrieved if forgotten due to security reasons. You will lose all data previously collected if this password is lost." 

- Add warning message to password creation module at applet creation and upload from GitHub
- Add messaging in email when applet has been successfully created

**Comment by natalia-muzyka** [comment]
Works as expected:
The Password Warning is displayed when the user creates, duplicates, transfers applet, uploads the GitHub protocol.
The email is updated as well.

Verified on:
Win 10 // Chrome 94.0.4606.54 
macOS 11.0 // Safari 14.0.1
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4ff46c70-6ddd-47a6-9355-d85dbf852768)
