### ISSUE TITLE
[BUG] When editing an applet, the labels from a stacked slider item always disappear

### ISSUE THREAD

**Issue by lioneldeveauxcri** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1264]
Stacked sliders label always needs to be the last thing done before saving the applet; please see the attached video.

(it works perfectly when I create an applet; it's when I edit the applet that I encounter this problem systematically)

Done in incognito mode, Chrome, iOS

https://user-images.githubusercontent.com/55746438/134172299-644522da-c391-436c-acfd-a70df4367206.mov

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/ONoh2Md0EvR

Environment:
Win 10 // Chrome 94.0.4606.61 
macOS 11.0 // Safari 14.0.1 // Chrome 94.0.4606.61 
account: avani_ml@protonmail.com //	12345678
applet: stacked labels test
Applet password: Qwe123!!!

@lioneldeveauxcri could you retest this ticket, please, or provide your account so I can retest it?
