### ISSUE TITLE
[BUG][PROD] Unsavable applets

### ISSUE THREAD

**Issue by lioneldeveauxcri** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1265]
Often, an applet becomes unsavable, even in incognito mode. There is no coming back from this state; if we duplicate the applet, the duplicate is uneditable.
Observed in both Anirudh's and Lionel's admin account.
See attached video

Chrome
Windows and iOS

https://user-images.githubusercontent.com/55746438/134177105-d01abe0d-c957-42f4-858e-73174ac6fcde.mov

**Comment by WorldImpex** [comment]
This is a known bug - https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/418 but very hard to recreate. We need to know exact steps to recreate in order to fix it. Clearing cache resolves the user's initial issue

**Comment by WorldImpex** [comment]
Duplicate  of https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/418
