### ISSUE TITLE
Update Transfer Applet Ownership

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1270]
1) Add a warning message into the existing Transfer Applet Ownership modal window:
 "Are you sure you want to transfer ownership of your applet to another user? This will only transfer the applet and no user data will be transferred."
Mockup:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/726c708c-45d5-4e4a-929f-87cf6ae32cf4)

2) After the applet is transferred if the new admin tries to do anything with the applet(edit, delete, etc) there should be a prompt to create a password (until the new password will be created). Currently, it is shown up only after clicking on the "View users" and "View general calendar".

**Comment by jj105** [comment]
@WorldImpex @natalia-muzyka -- just to confirm, should we show up applet password dialog when new owner clicks delete button button?

**Comment by WorldImpex** [comment]
@jj105  Yes

**Comment by natalia-muzyka** [comment]
Works as expected. 
Video: https://www.screencast.com/t/xNn0ESxCm

Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 94.0.4606.61 
macOS 11.0 // Safari 14.0.1
