### ISSUE TITLE
"Stacked" items: labels missing in the downloaded data .csv file

### ISSUE THREAD

**Issue by lioneldeveauxcri** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1281]
For every "stacked" item type (stacked radio, etc.)
In the downloaded data, the answers are present, but the labels corresponding to each number are missing.

**Comment by natalia-muzyka** [comment]
Verified as fixed.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/fcb8c330-36a9-4152-98f9-ab02b2823f20)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 94.0.4606.61
