### ISSUE TITLE
The SVG file (drawing response) is missing in the data export

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1284]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/
alyssia_ml@protonmail.com // qwertyuio

**Steps to reproduce**
1. Install and launch the app
2. Log in:maddison_ml@protonmail.com // qwertyuio
3. Complete the activity with a draw item (applet: media export check, activity: )
4. Proceed to the Users tab on the admin panel
5. Export the user's data
6. Pay attention to the exported CSV (draw responses) and downloaded archives

**Actual result**
The SVG file (drawing response) is missing in the data export even though the CSV responses are downloaded in the separate ZIP.

**Expected result**
The SVG file (drawing response) is downloaded in the media responses ZIP archive after the user's data export. The CSV responses are downloaded in the separate ZIP.

**Video:** https://www.screencast.com/t/7O2lMkBLvTz
**Screenshot:** 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a47a6040-f2d4-4408-9f21-56bc397cb5b5)

**Environment:**
https://admin-staging.mindlogger.org/
owner: alyssia_ml@protonmail.com // qwertyuio
users:
maddison_ml@protonmail.com // qwertyuio
janedoeregress@protonmail.com // %pVgPJ*O
ML v0.17.36 (staging)
iPhone SE (2020) // iOS 14.2	
iPhone 6S // iOS 14.4
Samsung Galaxy S7 SM-G930FD // Android 8.0
applet: media export check
activity: drawing
Applet password: Qwe123!!!

**Comment by lioneldeveauxcri** [comment]
Could you check the properties of the "microsoft edge" file? Isn't the extension .svg?

**Comment by natalia-muzyka** [comment]
You are right, ME this is the SVG, but these are old responses for another account.

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/TZNXyh73

Environment:
https://admin-staging.mindlogger.org/
owner: alyssia_ml@protonmail.com // qwertyuio
users:
maddison_ml@protonmail.com // qwertyuio
janedoeregress@protonmail.com // %pVgPJ*O
ML v0.17.38 (staging)
iPhone SE (2020) // iOS 14.2
Samsung Galaxy S7 SM-G930FD // Android 8.0
applet: media export check
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
The issue is reproducible again if activity was completed on **Android**.
CSV file with coordinates is downloaded, only the SVG file is missing.
Video: https://www.screencast.com/t/EoAF5Ph63AJ

Environment:
ML v0.19.13 staging
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
kimberly_ml@protonmail.com	12345678
media items, drawing
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/123abcd7-5966-499b-a345-5f952b141ca8)

Environment:
ML v0.19.14 staging
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android 9.0
kimberly_ml@protonmail.com 12345678
media items, drawing
Applet password Qwe123!!!
