### ISSUE TITLE
The "hit_next_time" timestamp is displayed in a different timezone and format that the "activity_start_time" and "activity_end_time"

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1287]
**Preconditions**
The user is logged in on the admin panel
The user is logged in on the mobile app
https://admin-staging.mindlogger.org/
alyssia_ml@protonmail.com // qwertyuio

**Steps to reproduce**
1. Complete any activity on the mobile app.
2. Proceed to the admin panel / applet's users tab, export the user's data.
3. Compare the timestamps formats in the "hit_next_time", "activity_start_time" and "activity_end_time" columns.

**Actual result:**
The "hit_next_time" timestamp is displayed in a different timezone and format that the "activity_start_time" and "activity_end_time"

**Expected result**
The timestamps in the CSV report are displayed in the same timezone(UTC) and format

**Screenshot:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/fc9dabf7-03f6-45ca-b6a2-3dd0478eb6ac)

**Environment:**
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 // Chrome 94.0.4606.61
ML v0.17.38 (staging)
iPhone SE (2020) // iOS 14.2	
Samsung Galaxy S7 SM-G930FD // Android 8.0
owner: alyssia_ml@protonmail.com // qwertyuio
user: loui_ml@protonmail.com // 12345678
applet / activity:
start, next, end events data / activity 1
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@devbtech I think seconds should be presented at least in the "hit_next_time" timestamp.
@WorldImpex could you confirm, please, should we have the seconds for "activity_start_time" and "activity_end_time" as well?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7ca1322e-85e3-4062-81d5-08720b7942bf)

**Comment by WorldImpex** [comment]
Yes @natalia-muzyka

**Comment by natalia-muzyka** [comment]
Verified as fixed.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/71d86c8e-6212-47ba-b8f5-697932cc56ae)

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 // Chrome 94.0.4606.81 
ML v0.17.43(staging)
iPhone SE (2020) // iOS 14.2
Samsung Galaxy S7 SM-G930FD // Android 8.0
owner: alyssia_ml@protonmail.com // qwertyuio
user: loui_ml@protonmail.com // 12345678
applet / activity:
start, next, end events data / activity 1
Applet password: Qwe123!!!
