### ISSUE TITLE
Add version of environment to header in Staging ONLY 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1297]
Please add the version tag of the environment to the admin, applet builder, webapp, and library so we can more clearly see if things are deployed or not

**Comment by natalia-muzyka** [comment]
@devbtech I don't see version of environment on staging, are these changes deployed?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/adc04b17-bbce-4056-9c9d-bc80c321cad3)

**Comment by natalia-muzyka** [comment]
@devbtech @WorldImpex 
Version is still missing in the Library.
Admin panel and Applet builder should have different versions, shouldn't they?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7de77fc4-a567-41ff-822d-cfa128a69d99)

**Comment by WorldImpex** [comment]
@devbtech Is this fixed? If so, its on hold when it should be in PR Review ready

**Comment by WorldImpex** [comment]
fixed - library in staging has a version and applet builder vs admin panel have different versions
