### ISSUE TITLE
The text in the report is shifted if there is an applet image (logo)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1313]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/
loui_ml@protonmail.com // 12345678
The user completed a cumulative activity with an applet image
(applet: Cumulative (revert summary screen) 3)

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Open the User's dataviz on admin panel
3. Download report
4. Pay attention to the PDF report displaying

**Actual result**
The text in the report is shifted if there is an applet image (logo)

**Expected result**
The text in the report is floating the logo image

**Screenshot:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/20861eae-cd07-4c02-a45f-fcd7808f164a)

**Environment:**
https://admin-staging.mindlogger.org/
loui_ml@protonmail.com // 12345678
applets:
cumulative (revert summary screen) 2
cumulative (revert summary screen) 3
Applet password: Qwe123!!!

**Comment by binaryExDev** [comment]
@natalia-muzyka On the screenshot, the overview and applet image can be overlapped.

**Comment by natalia-muzyka** [comment]
@binaryExDev what if text will be floating the logo?
Example:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/0505ea08-5209-4240-b0d3-e3f56741e762)

**Comment by natalia-muzyka** [comment]
@binaryExDev Could you add more space, please? The margin-left and margin-bottom for logo image. Currently, the text and logo are too close.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9e6781f2-12b6-4dcd-920b-d0a7ec7ded1c)

**Comment by natalia-muzyka** [comment]
Verified as fixed.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1c0f175a-8e22-4264-8c38-9a707de59b8a)
