### ISSUE TITLE
The splash screen image isn't displayed in the admin PDF report

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1314]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/
loui_ml@protonmail.com // 12345678
The mobile app is installed and launched
The user is logged in

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Create an activity with cumulative item (allow to see results)
3. Add the splash screen to the activity (MP4 with valid size/resolution, uploaded from PC) and save the applet
4. Refresh the mobile app
5. Complete the cumulative activity
6. Open the User's dataviz on admin panel
7. Download report
8. Pay attention to the PDF report displaying

**Actual result**
The splash screen image isn't displayed in the admin PDF report

**Expected result**
The splash screen image is displayed in the admin PDF report before the cumulative score title as per the [requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2040).
Every activity that has a report and splash screen should start with the splash screen full page and then next page should actually start the report.

**Video:** https://www.screencast.com/t/8HTbyeuhIf

**Uploaded videos:**
https://drive.google.com/drive/folders/1gWO4G0QYHKVnxAJeFJ73oU4c1qZ1lRjh?usp=sharing
URL GIF: https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif

**Environment:**
https://admin-staging.mindlogger.org/
loui_ml@protonmail.com // 12345678
applets:
Cumulative (splash screen PDF report)
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
Reproducible

**Comment by natalia-muzyka** [comment]
[UPD] Verified and closed. Works as expected with uploaded images: JPG, PNG, GIF.

---

@binaryExDev @WorldImpex 
Splash screen image is displayed if it is an image: JPG, PNG, or GIF (shows the first picture from animation)
There is no splash screen if there is a video uploaded. 
Video: https://www.screencast.com/t/Dngz7QKN

owner: kimberly_ml@protonmail.com	12345678
user: bernard_ml@protonmail.com	 qwe123!!!
applet: splash screen test (1)
activity: pc mp4 1920x1920
applet password: Qwe123!!!
