### ISSUE TITLE
The applet builder isn't opened after clicking the "Edit" button on the applet cart

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1315]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: loui_ml@protonmail.com // 12345678
3. Click the "Edit" button on the "Daisy chain loop" applet
4. Pay attention to the screen

**Actual result**
The applet builder isn't opened after clicking the "Edit" button on the applet cart

**Expected result**
The applet builder is opened after clicking the "Edit" button on the applet cart

Notes: The applet builder can be opened if admin clicks the "View users" btn on the same applet and the clicks the "Edit" btn 

**Video:** https://www.screencast.com/t/o8aTYZJ9k

**Environment:**
https://admin-staging.mindlogger.org/
loui_ml@protonmail.com // 12345678
Win 10 // Chrome 95.0.4638.69 
applets:
Daisy chain loop
Daisy chain loop (activity out of loop)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed on staging
Video: https://www.screencast.com/t/SaTIaGuv

Environment:
https://admin-staging.mindlogger.org/
loui_ml@protonmail.com // 12345678
Win 10 // Chrome  96.0.4664.45

**Comment by natalia-muzyka** [comment]
@WorldImpex just to make sure, this fix and fixes below should go in a normal order with the milestone 10 deploy or they should be deployed to prod before release?
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/582
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/772

**Comment by WorldImpex** [comment]
We can wait on milestone 10. Thanks for checking @natalia-muzyka

**Comment by natalia-muzyka** [comment]
@jj105 
Reproducible on staging after editing the activity with the Past behavior tracker item.
In this case, the applet builder can't be opened at all.

Video: https://www.screencast.com/t/gHfnYn7D

Environment:
https://admin-staging.mindlogger.org/
account:
bernard_ml@protonmail.com // qwe123!!!
applet: TL refresh
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/xnUxn1L83gkw

Environment:
https://admin-staging.mindlogger.org/
account:
bernard_ml@protonmail.com // qwe123!!!
applet: TL refresh
Applet password: Qwe123!!!
