### ISSUE TITLE
The applet logo should be displayed on the second page(with the main report) if there is a splash screen

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1323]
**Issue:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c6c21bcf-760b-4edd-84af-48b2a65a3bf9)

**Expected result: on admin panel, mobile app and webapp: applet logo should be moved to the second page (to the main report) if there is a splash screen uploaded (on the first page)**

**Account:**
kimberly_ml@protonmail.com	12345678
applet: splash screen test (1)
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
works as expected

**Comment by natalia-muzyka** [comment]
Verified as fixed on admin panel, webapp, mobile app

https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
ML v0.17.71 (staging)
Samsung S7 // Android 8.0	
iPhone 8 Plus // iOS 13.3

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/40c85fbc-b675-4cf5-9fa3-df411d351a9a)
