### ISSUE TITLE
[UI] The part of splash screen image is displayed on the next page if image ratio is 1.5:1 (1500x1000)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1324]
**Splash screen image should be displayed on one page in the report on webapp, admin panel, mobile app**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/005b5993-a57b-4ade-8031-016bfb1e94da)

account:
kimberly_ml@protonmail.com	12345678
user: bernard_ml@protonmail.com	qwe123!!!
applet / activity:
splash screen test (1) / URL 1000x1500 jpg

**Comment by Matchdev120** [comment]
@natalia-muzyka Did you test this applet/activity (splash screen test (1) / URL 1000x1500 jpg) on web app as well?
It's currently working fine on my side.

**Comment by natalia-muzyka** [comment]
@Matchdev120  for me it's not reproducible now with this particular image on webapp, but reproducible on mobile app (iOS and Android):
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/722c13f6-e295-4b26-8c0b-bbfba586264b)

But there is still a problem with displaying the image with a bigger ratio on webapp, mobile app and admin panel.

Uploaded image: 
![MindLogger_AppScreens_PediatricAssessment_Splash.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/61d82a6b-45a8-46c4-ac97-bf5d519e0d4d)

Webapp report:
[https://app.zenhub.com/files/189080374/f3f5505d-f6e0-4f34-8439-27e5a0eb0e7d/download](https://app.zenhub.com/files/189080374/f3f5505d-f6e0-4f34-8439-27e5a0eb0e7d/download)

Admin panel report:
[https://app.zenhub.com/files/189080374/f0f38a41-da68-420e-8127-d79e4e937d63/download](https://app.zenhub.com/files/189080374/f0f38a41-da68-420e-8127-d79e4e937d63/download)

Mobile app report:
[https://app.zenhub.com/files/189080374/154f447f-9321-4bdc-acf2-33249db9d358/download](https://app.zenhub.com/files/189080374/154f447f-9321-4bdc-acf2-33249db9d358/download)

https://web-staging.mindlogger.org/
https://admin-staging.mindlogger.org/
ML v0.17.71 (staging)
iPhone 8 Plus // iOS 13.3
Samsung S7 Edge // Android 8.0
account owner: kimberly_ml@protonmail.com // 12345678
account user:
avani_ml@protonmail.com // 12345678
maddison_ml@protonmail.com // qwertyuio
josephine_ml@protonmail.com // qwertyui
applet / activity:
splash screen test (1) / ML pediatric screener
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
There is still an issue with trimmed images. 
@Matchdev120 , As you correctly noticed, it is actually a similar issue with Splash screen doesn't fit the page in the PDF report [#219](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/219) 
So I think we can close this duplicate to not confuse anyone.
