### ISSUE TITLE
Show Milliseconds in data export for all time 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1331]
In our data export, we need to show milliseconds for all time that we collect. Please update

**Comment by natalia-muzyka** [comment]
@devbtech milliseconds are shown in export.

Google sheets:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/962674a7-16bc-45ef-80b9-4bb1fa2dc1ba)

Local PC(Excel):
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f7697be4-11fe-4e66-8ac5-50be444f5296)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.45
macOS 10.15 // Chrome 96.0.4664.45
account: josephine_ml@protonmail.com / qwertyui
applet: all item types(mobile app only)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@devbtech @WorldImpex milliseconds are missing in the drawing responses csv **on production**. In the general csv milliseconds are displayed. On staging everything works as expected (as in my comment above).

Screenshot:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5a6bcbf8-8b38-43e0-8628-44fd3cbfb8cf)

Environment:
https://admin.mindlogger.org/
Win 10 // Chrome 96.0.4664.45 
macOS 10.15 // Chrome 96.0.4664.55 // Safari 13.1.2
account: bernard_ml@protonmail.com	// qwe123!!!
applet: media items
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f5c45666-847f-4721-bdf9-655e4b9a32d9)

https://admin.mindlogger.org/
Win 10 // Chrome 96.0.4664.45
macOS 10.15 // Chrome 96.0.4664.45 // Safari 13.1.2
