### ISSUE TITLE
Public Link Accessibility 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1334]
If the applet is not fully functional on webapp, then grey out the public link button and do not allow the admin to create a public link

**Comment by natalia-muzyka** [comment]
**Related issues:**
Fixed - The generated public link is still accessible after adding not supported on webapp items to the applet#1498

@WorldImpex 
**Suggestions:**
There could be a hint to the greyed out "Generate" button with an explanation of why it is greyed out

**Comment by WorldImpex** [comment]
@natalia-muzyka Agreed!

**Comment by natalia-muzyka** [comment]
Works as expected. 

https://admin-staging.mindlogger.org/
Win 10 // Chrome 99.0.4844.84

**Comment by WorldImpex** [comment]
We need to revert these changes

**Comment by natalia-muzyka** [comment]
Public Link Accessibility is reverted.
There are no restrictions due to the item types on generating the public link.

Verified on:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/#/
Win 10 // Chrome 101.0.4951.67 
macOS BigSur 11.0 // Chrome
