### ISSUE TITLE
[PROD][bug] cannot edit an applet after ownership transfer

### ISSUE THREAD

**Issue by lioneldeveauxcri** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1339]
after applet ownership was transferred to mindlogger-admin@cri-paris.org, the system keeps asking me to change the password. I can't do anything.
see video: https://drive.google.com/file/d/1fqBVWmV_06_rck2hhSgAm1ZWoOf6tavU/view?usp=sharing

**Comment by lioneldeveauxcri** [comment]
it worked after logging in and out -> this should work on the first try

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/54yAmZJdxA3N

Environment:
Win 10 // Chrome 96.0.4664.45 
macOS 10.15 // Chrome 96.0.4664.45 // Safari 13.1.2

**Comment by natalia-muzyka** [comment]
@WorldImpex @devbtech issue is reproducible **on production**. Staging works as expected.
Video: https://www.screencast.com/t/HdjfjhyrmQi

Environment: 
https://admin.mindlogger.org/
Win 10 // Chrome 96.0.4664.45 
macOS 10.15 // Chrome 96.0.4664.55

**Comment by lioneldeveauxcri** [comment]
Yes, sorry, my issues/bugs are always on production. I should have written as much to avoid confusion.

**Comment by natalia-muzyka** [comment]
Verified as fixed on production.
Video: https://www.screencast.com/t/zSBuhYStMIVw

Environment:
https://admin.mindlogger.org/
Win 10 // Chrome 96.0.4664.45
macOS 10.15 // Chrome 96.0.4664.55 // Safari 13.1.2
