### ISSUE TITLE
[Flanker] Null value in CSV report if user didn't answer (Respond faster message)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1385]
Null value in CSV report if user didn't answer (Respond faster message)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3862ea4c-9311-4a3c-8cf8-12469f341141)

https://admin-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.110

**Comment by WorldImpex** [comment]
@natalia-muzyka What is the expected result here?

**Comment by natalia-muzyka** [comment]
@WorldImpex 
I'm not sure what's the expected behavior there - "0" or empty cell, I don't know
I just assume that the "null" value is not correct, as well as [object object] or so

**Comment by WorldImpex** [comment]
@mtg137 What is the fix you implemented?

**Comment by techdev137** [comment]
@WorldImpex @natalia-muzyka - I set it as empty cell instead of "null".

**Comment by natalia-muzyka** [comment]
There is a dot if there was no response:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e7897f9b-c5d4-4c2a-b5d6-e28e9539494a)
