### ISSUE TITLE
[Flanker] The "net" isn't replaced by "neut" in CSV report

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1386]
"net" isn't replaced by "neut" in CSV report:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/279c8f25-3e2e-4e51-ae15-2da1b2b68d54)

https://admin-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.110

**Comment by WorldImpex** [comment]
no longer required
