### ISSUE TITLE
[PROD] Admin, Applet Builder and Library version isn't hidden on prod

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1394]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/0219421f-846d-41a8-8110-ceb5ed3d22e2)

**Comment by WorldImpex** [comment]
@devbtech what is the status on this?

**Comment by natalia-muzyka** [comment]
@devbtech 
This ticket might need to be dropped to QA Prod column.
Fixed on PROD Admin and Applet builder.
On Library version is still displayed.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/0135e465-95bc-4dce-8ae0-d4adc2f89434)

**Comment by natalia-muzyka** [comment]
Verified as fixed for Library:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3251b168-bc23-443c-9f65-ab3ffafa1f4f)
