### ISSUE TITLE
Dashboard - Data is not shown at the right time/ some data broken

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1409]
1. The positive data goes negative on the Area chart and overlaps x axis. Expected: It is positive and does not overlap.
2. Bar chart is not shown 
3. Token chart does not show any tokens in "Today you will earn at least:" 
4. Token Chart: The day view has broken spacing between morning noon and evening. Expected: It is more evenly spaced 
5. Token Chart: 3 month view should have months identified

**Comment by natalia-muzyka** [comment]
@mtg137 
3. could you clarify the calculation for the "today you'll earn at least:", please?
on mobile app and admin panel it is different:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/473832ff-5001-45f2-a041-234229c1e2f7)

**Comment by techdev137** [comment]
@natalia-muzyka - I think we show tokens that user earned "today" in the tooltip

**Comment by mtg137** [comment]
admin panel is displayed in UTC timezone, and mobile data tab is in user’s timezone

I think meaning of "today" is different on mobile and admin because mobile is displayed in user's timezone and admin panel is displayed in UTC

**Comment by WorldImpex** [comment]
@mtg137 Please remove Today you will earn atleast tooltip from admin panel

**Comment by natalia-muzyka** [comment]
@mtg137 
token chart doesn't go negative but it shows start score incorrect:
Case: 
19/01 user completed the activity for the first time and earned 2 tokens per completing the past behavior activity
20/01 user earned +9 tokens per negative behavior
Expected: on mobile app is correct graph

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/20cc4cb7-48f7-494f-947d-d258aa82d984)

Environment:
https://admin-staging.mindlogger.org/
kimberly_ml@protonmail.com // 1234567
josephine_ml@protonmail.com // qwertyui
applet: TL applet CASE 1
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/466fe546-8075-425d-b698-03fc9f813339)

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e90df0ff-1fa1-423f-b494-268df5d89142)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 97.0.4692.99
