### ISSUE TITLE
Update Admin to show UTC Time

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1416]
Update the admin dashboards with "Time is shown in UTC" 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b9f5b519-3fed-4398-86f7-b7d6cf1d029b)

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/2e5ee750-4eca-4ff0-be0f-6b5200b6997c)

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/cdd3a6a1-0adb-4d4a-8675-5edf3331f4c6)

**Comment by natalia-muzyka** [comment]
Works as expected:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/13c1869a-6221-42c5-8334-4930736d41ce)

https://admin-staging.mindlogger.org/
Win 10 // Chrome 97.0.4692.71
