### ISSUE TITLE
[UI] The responses block is displayed out of the "Review" tab border

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1425]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7eed2969-409e-4b2f-ac5f-0be999a1df47)

Environment:
https://admin-staging.mindlogger.org/
kimberly_ml@protonmail.com	12345678
applet: applet name
Applet password	Qwe123!!!

**Comment by WorldImpex** [comment]
Resolved on macbook pro/ chrome & safari 
windows/ chrome & firefox
