### ISSUE TITLE
User's LastName is missing in the invitation email

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1439]
@WorldImpex should be there "--" after the LastName or this is a typo?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6467e302-45ae-4cf2-a92a-24dcd6beec79)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 97.0.4692.99

**Comment by WorldImpex** [comment]
Typo - That should be fixed. @natalia-muzyka

**Comment by natalia-muzyka** [comment]
@devbtech dashes after the Name LastName should be removed

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2f13a792-586a-46c9-bc96-71c20bf8af52)

**Comment by natalia-muzyka** [comment]
Verified as fixed in the invitation email:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f47d599d-44fb-4382-9181-ebbec50c5343)
