### ISSUE TITLE
Allow applets to be grouped in folders

### ISSUE THREAD

**Issue by henryrossiter** [ChildMindInstitute/mindlogger-admin-OLD-Vue#147]
As an organizer role, I want to be able to group applets in folders so that I can better organize my dashboard 

Requirements: 
* Allow a user to create a folder and name it whatever he or she wants
   * Folders can have the same name 
* Allow a user to edit the folder name 
* Allow user to drag and drop an applet into or out of the folder 
* Pinning an item in the folder only affects the order in the pinned folder 
* If the user attempts to delete an applet folder with applets inside, display "You cannot delete a folder that contains applets. Please remove applets from this folder and try again." 
* If the user attempts to delete an applet folder without applets inside, then remove the folder from the list 
* Folders are always at the top above pinned applets. 

![Applet Folders.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4a185695-3766-4bfd-9f21-68c5d83523bc)

**Comment by WorldImpex** [comment]
FE complete - Needs BE component
