### ISSUE TITLE
[CSV report][Variable name] Continuous slider, time range, date values are displayed as ObjectObject in the Prompt and Options columns

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1475]
**Preconditions**
User is logged in on the mobile app
There is an activity with the next items:
continuous slider, time range, date, age
Items names are added as variable names to the other items (as option text and prompt) (each item name is in the brackets [[]])

**Steps to reproduce**
1. Complete an activity on mobile app
2. Proceed to user's DataViz and export CSV with user's data
3. Pay attention to the Prompt and Options columns

**Actual result**
Continuous slider, time range, date values are displayed as ObjectObject in the Prompt and Options columns in the CSV report

**Expected result**
Continuous slider, time range, date values are displayed accordingly to the entered user's input in the Prompt and Options columns in the CSV report

**Screenshot:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5482a08a-21a4-4c0b-b40c-7cb0f23531bc)

**Environment:**
https://admin-staging.mindlogger.org/
ML v0.18.54 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
anita_ml@protonmail.com qwe123!!!
applet: applet name (anita) / variable name input 
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
Looks to be resolved ![Screen Shot 2022-02-24 at 6.38.10 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5ceb2b08-022b-424b-9532-284125c7bf24)

**Comment by WorldImpex** [comment]
When exporting data, the lazy loader does not disappear after the files have been downloaded

**Comment by jj105** [comment]
I think it is lazy loader for downloading media files
on my side, after 10-20 seconds, media responses are downloaded and loader disappears

**Comment by natalia-muzyka** [comment]
Verified as fixed:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d76ada44-a31d-4e50-821f-747810e17bf2)

Environment:
ML v0.18.58 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
