### ISSUE TITLE
Add a ToolTip to Combine all reports checkbox 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1477]
When the editor hoovers, show a tooltip "This feature only impacts mobile and the web-app. The admin report will remain unchanged."

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ed17bec6-54f5-4f86-bf2b-e1c34c2512a4)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![Screenshot_1.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5ab593c8-cbe0-4137-b69b-e277bf0fdab8)
