### ISSUE TITLE
reviewer is able to view scheduling page by changing url manually

### ISSUE THREAD

**Issue by fullstackdev065** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1483]
environment: admin-staging.mindlogger.org

account: test_reviewer@protonmail.com / 123456

steps:
1 - login to account
2 - switch to "manager" account
3 - click view users button for "webapp schedule" applet
4 - change end of url to "schedule"
https://admin-staging.mindlogger.org/#/applet/621c768f6087568bd4c06ece/schedule?lang=en_US
5 - user is redirected to page for scheduling

expected: user is redirected to dashboard page if permission for updating schedule is not granted

**Comment by natalia-muzyka** [comment]
Verified as fixed, reviewer has no access to calendar and is redirected to the main dashboard: https://www.screencast.com/t/hYHWMRdWEt
