### ISSUE TITLE
Incorrect data in change history modal

### ISSUE THREAD

**Issue by fullstackdev065** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1484]
environment: admin-staging.mindlogger.org

account: test_2@protonmail.com / 123456
applet: Transfer_reject_test

steps:
1 - click edit button for the applet
2 - change only activity name
3 - save applet
4 - click button for viewing history
5 - check latest changes made in applet

![image.png](https://images.zenhubusercontent.com/6181414bb17b332a2e8c0cb6/993041eb-2476-4451-b0e6-566f1e5f78a1)

current: it shows that new activity was inserted and order of activities were changed
expected: just display that name of activity is changed

**Comment by natalia-muzyka** [comment]
@jj105  It looks like history is broken at all.
After changing the applet description, applet name, activity name in two activities, editing the "conditional test" activity (added a new item and splash screen) there is always the same info in the history about the old changes in the activity "multiple".

Video 1: https://www.screencast.com/t/d2nP7dP7sTmW
Video 2: https://www.screencast.com/t/Ckb2QMLsep
Video 3: https://www.screencast.com/t/FMPBYmuto

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 99.0.4844.51

**Comment by natalia-muzyka** [comment]
Verified as fixed:
https://www.screencast.com/t/tvJFmdmGU

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 99.0.4844.74
