### ISSUE TITLE
Nothing happens after clicking the Remove button or basket icon for the event on the schedule page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#149]
Steps to reproduce:
1. Log in to the admin panel https://admin.mindlogger.org/#/ ( snakeprod // 123456 )
2. Select the NIMH applet
3. Set up several events for the general schedule
5. Try to delete these events from the calendar
6. Pay attention to the result

Actual result: Nothing happens after clicking the Remove button or basket icon for the event on the schedule page
Video: https://www.dropbox.com/s/5e5zvc7l4p71xg0/2020-04-21_16-03-21.MP4?dl=0
Note: The "Are you sure you want to remove this event?" modal window is shown only after reloading the page
Expected result: The "Are you sure you want to remove this event?" modal window is shown after clicking the Remove button or basket icon for the event on the schedule page

Environment:
Prod server
Win 10 x 64 // Chrome Version 81.0.4044.113 // Edge

**Comment by WorldImpex** [comment]
@ProNinoGit120 - There is a 500 error when trying to remove an applet on admin 

https://www.dropbox.com/s/zdvhelgtvcw6ndx/2020-04-28_18-58-24.MP4?dl=0

**Comment by sergeysemenuta** [comment]
The issue is not reproduced anymore
Environment:
Dev server
Prod server
 https://admin.mindlogger.org/
Chrome
Firefox
Edge
