### ISSUE TITLE
Firefox. The "Network Error" is displayed after trying to log in to the admin panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#150]
Steps to reproduce:
The user is registered on the site ( snakeprod // 123456)
Steps to reproduce:
1. Open the page https://admin.mindlogger.org/#/login
2. Specify your credentials and click the "LOGIN" button
3. Pay attention to the result

Actual result: The "Network Error" is displayed after trying to log in to the admin panel
Video: https://www.dropbox.com/s/tpaw0mobn9y5g39/2020-04-21_16-33-18.MP4?dl=0
Note: The same behavior occurs after trying to log in with the empty "Login" form
Expected result: The user is logged in successfully

Environment:
Prod server
Win 10 x64 //Firefox 75

**Comment by WorldImpex** [comment]
fixed
