### ISSUE TITLE
Store and export timestamps in seconds, not milliseconds

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1502]
Recently, timestamps in the csv export were changed from "yyyy-MM-dd HH:mm:ss" format to epoch time in milliseconds. This adds millisecond-level information that we didn't have before, which is great, but I suggest that we reformat it to epoch time **in seconds** with 3 decimal places or "yyyy-MM-dd HH:mm:ss.SSS" for the following reasons:

1. **Unit should be in seconds:** Currently all the code we've written at CMI to process/analyze ML data will output inaccurate times because it expects 1 second epochs. So 1647618528169 won't work but 1647618528.169 or "2022-03-18 15:48:48.169" would parse fine. (We actually found out about this because someone was running code to inspect participant data and noticed weird times)

2. **Human readable**: "2022-03-18 15:48:48.169" is easier to understand than 1647618528.169, and both contain the same information. However, if is this is going to cause confusion because we're storing and exporting in different formats, please ignore.

**Comment by WorldImpex** [comment]
Updates are going on this ticket per Arno's requirements 

https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-backend/1235
