### ISSUE TITLE
CST: Export shows the last line where test parameters reset 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1519]
If there is not anything wrong with the data collection, then please remove the last entry that shows the parameters resetting. If there is a data collection issue, please advise Wil 

![Screenshot (2).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/fbc34306-2341-40ad-9908-1514c0a4fdd1)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/442c80ca-6993-4305-b0a8-90e36f2b6677)

Checked on iOS:
ML v0.20.1 staging
iPhone XR // iOS 14.3
iPad Pro (10,5-inch) MQDX2 // iOS 15
Android:
ML v0.20.2 staging
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android 9.0

CST touch version
CST tilt version
