### ISSUE TITLE
BUG: Free text response character limit won't change from 50

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1520]
To reproduce:

1. Change the character limit for a free text response item in applet builder
2. Hit save
3. The item will still have 50 character limit
![text_limit](https://user-images.githubusercontent.com/24463939/160480845-eb200842-f968-4fcf-b1b9-3f910a107133.gif)

**Comment by natalia-muzyka** [comment]
Blocker issue:
Entered text is not reflected in the text input field#2529

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/5KwkRjPXupoS

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
