### ISSUE TITLE
The activity is missing on the applet screen on the last day of its repeated schedule

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1539]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/ and log in
2. Proceed to the Calendar of any applet
3. Create a repeated activity: Daily with 'begin' and 'end' date 
4. Save schedule
5. Set up the last day of the schedule on mobile device
6. Open mobile app and proceed to the applet with the scheduled activity
7. Pay attention to the applet screen

**Actual result**
The activity is missing on the applet screen on the last day of its repeated schedule

**Expected result**
The activity is displayed on the applet screen on the last day of its schedule until it is not completed

**Screenshot:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7c032fa7-df60-4063-8218-028cc0169b27)

**Environment:**
https://admin-staging.mindlogger.org/
ML v0.19.15 staging
Samsung Galaxy S7 // Android 8
iPhone XR // iOS 14.3
jeraka1732@wodeda.com 1234567890
applet: dbt / target behaviors
Applet password Qwe123!!!

**Comment by techdev137** [comment]
@natalia-muzyka - could you please check it without changing clock?

It works fine for me.
![image.png](https://images.zenhubusercontent.com/5fbce3e9259bafeab239c8c3/8b359a47-ef52-49f0-bb56-9af30221d655)

date and times are calculated on backend side so changing clock on mobile app might introduce bring bugs for scheduling.

**Comment by natalia-muzyka** [comment]
@mtg137 I checked without changing clock, but issue is still reproducible.
Are we in the same time zone now?
Video: https://www.screencast.com/t/kq4HWtV97Z

Environment:
ML v0.19.21 staging
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/beb8d279-5f27-4f76-9a92-ddbca039b289)

Environment:
ML v0.19.22 staging
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
