### ISSUE TITLE
Upload a CSV to Create a Schedule 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1546]
As a coordinator, I want to upload a CSV that creates a group or individual schedule so that I do not have to enter each event manually using the admin panel 

Requirements 
- Allow a coordinator to upload a schedule for an individual schedule 
   - Add an Upload Schedule button to the schedule page 
   - Show a popup module that allows an editor to upload an individual schedule 
   -  Allow editor to download the template
   - Show error message if parsing the csv fails. [Error messages here](https://docs.google.com/spreadsheets/d/1we26B-vTTalSpImlCmjKqQFzhK1a2Ns0iZkV6FagViI/edit?usp=sharing)
   - If an editor uploads a schedule of an individual that previously had a schedule replace the old schedule with the newly uploaded 
      - If a schedule is uploaded and then the coordinator manually adds 1 or more activity schedules, then the uploaded schedule does not change and the additional activities are added. 
      - If a coordinator deletes one activity schedule from the group of uploaded, then only the one activity schedule is deleted. The rest of the group schedules remains the same. 
   - Show confirmation screen when editor submits
 - Allow the coordinator to upload a schedule for a group 
   - Add an Upload Schedule button to the schedule page 
   - Show a popup module that allows an editor to upload a group schedule 
   -  Allow editor to download the template
   - Show error message if parsing the csv fails. [Error messages here](https://docs.google.com/spreadsheets/d/1we26B-vTTalSpImlCmjKqQFzhK1a2Ns0iZkV6FagViI/edit?usp=sharing)
   - Group and individual schedule rules should remain the same. (ie an individual schedule overrides a group schedule) 
   - If an editor uploads a schedule for a group that previously had a schedule replace the old schedule with the newly uploaded 
- If the editor clicks the upload schedule button after already importing a schedule or having a schedule already setup, show conformation message: "Importing a new schedule will replace the current schedule. Are you sure you want to continue?"
- If the editor tries to close import schedule module 
   - without any uploaded files then the previous schedule should still be displayed.
   - when there has been uploaded csv file then show confirmation message "Are you sure you want to leave without saving changes?" 
- Allow the editor export an uploaded schedule
   - If a schedule has been imported, then show a hyperlink under download template called Export Schedule 

![Schedule CSV (3).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4f395cad-2bd1-4673-9e2c-bc865a08b1e2)

Examples

Example 1: Secret ID 123123 already has a schedule. The coordinator uploads a csv that includes this Secret ID. 123123’s schedule is replaced

Example 2: Secret ID 123123 already has a schedule. Coordinator uploads a csv that does NOT this Secret ID. 123123’s  schedule remains and does not get removed because it was left out of the csv.

**Comment by natalia-muzyka** [comment]
Is blocked by:
The imported schedule is not applied after submitting the valid CSV file #1631

**Comment by eleonova-scn** [comment]
It seems that the blocker (https://github.com/ChildMindInstitute/mindlogger-admin/issues/1631) is closed. Does it mean that the current issue can be re-tested and closed (if fixed)?

**Comment by natalia-muzyka** [comment]
The feature was retested after fixing this blocker (#1631).
We still have a couple of issues with a CSV schedule, but according to the updated priorities (no blockers), this ticket can be closed.

**Issues:**

- Highest:
Not a blocker, improvement - The CSV template is not parsed if it was downloaded, edited in Excel and uploaded again #1643

- High:
Fixed - Group schedule is not created after uploading and submitting it on the Group Calendar page #1785

- Medium:
Fixed - Show only individual/group scheduled events in the individual/group calendar template #1786

**Comment by natalia-muzyka** [comment]
Verified and closed. 

Environment:
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
Windows 10 x64 // Chrome 106.0.5249.91
