### ISSUE TITLE
401 Error when navigating to the admin panel 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#155]
Steps to recreate: 
1. Log into admin dashboard 
2. Wait 24 hours 
3. Navigate back to admin dashboard 
4. See results

Expected results: User lands on dashboard 
Actual results: User sees 401 

If user logouts out on that page and logs back in, the 401 error goes away 

![Screen Shot 2020-04-22 at 8.44.30 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/1ded06c1-4451-48f4-961d-8c7c71b917cd)

**Comment by sergeysemenuta** [comment]
The issue is not reproduced.
Checked on:
Dev server
Win 10 x 64 // Chrome //   https://admin.mindlogger.org/#/
