### ISSUE TITLE
Remove email sentence from upload 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#157]
Simply remove "If you have an email address associated with your account, you will receive an email when your applet is ready." sentence confirming the applet being uploaded

![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/a27870cf-3938-47b2-804f-71020c7c3f46)

**Comment by henryrossiter** [comment]
This text is no longer in the code base at all. It was removed in pr 156. I'm not sure why it's still showing up sometimes. Maybe the browser is caching this text?

**Comment by WorldImpex** [comment]
@henryrossiter I tried in incognito mode and unfortunately it still shows up

**Comment by henryrossiter** [comment]
Ah, I was wrong. PR 163 will fix it though!
