### ISSUE TITLE
[Activity user journey CSV] Tap on the "Skip" is recorded as the press_next

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1572]
On the screenshot, there is a regular report on the top and an activity journey report below: https://www.screencast.com/t/DAcbXbxf

**Expected:** 
@WorldImpex help me, please, to define the expected result:
OR The skipped item should be missing as in the general report
OR There should be another column "press_skip_time"

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101
ML v0.20.4 staging
iPhone XR // iOS 14.3
owner: jeligi9407@zneep.com 123456
user: test-user1@mail.com	123456
my applet (import) / regular items (all skippable)
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
@natalia-muzyka 
Lets add a column! We should be recording all button presses so skip, undo, next should be part of the scope of activity journey

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/971fa881-7da9-483c-83e7-00d9fb356f32)

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/#/
Win 10 // Chrome 101
ML v0.20.6 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
owner: jeligi9407@zneep.com 123456
user: test-user1@mail.com 123456
my applet (import) / regular items (all skippable)
Applet password Qwe123!!!
