### ISSUE TITLE
[Activity user journey CSV] Time out is recorded as a Response selection time (replaces the actual selection time if there was a selection made)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1574]
Screenshot: https://www.screencast.com/t/qRBqm2fN	
Full video: https://www.screencast.com/t/vOq6DqADl

**Expected:**
@WorldImpex help me, please, to define the expected result:

1- If there were no selections on the screen:
OR the item should be missed as in the general report
OR there should be a new event (column) with a new entry

2 - If there were made selections the time_out timestamp shouldn't replace the selection response time. There should be a new entry

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101
ML v0.20.4 staging
iPhone XR // iOS 14.3
Samsung S7 // Android 8
owner: jeligi9407@zneep.com 123456
user: test-user1@mail.com 123456
my applet (import) / regular items (timer)
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
@natalia-muzyka 

1. item should be missed as in the general report
2. I think we just need to keep the time the user selected

**Comment by natalia-muzyka** [comment]
Verified as fixed.
1. item is missed if there was no selection and time is out
2. response_selection_time is recorded if user selects a response before the timer is out

Video: https://www.screencast.com/t/4xsnf80h02LQ
Report:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6f9acd97-1597-4db9-aba0-75868d368134)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101
ML v0.20.8 staging
iPhone XR // iOS 14.3
Google Pixel 5a // Android 11
owner: jeligi9407@zneep.com 123456
user: test-user1@mail.com 123456
my applet (import) / regular items (timer), media items (timer)
Applet password Qwe123!!!
