### ISSUE TITLE
[Activity user journey CSV] Only the last response option selection is recorded and displayed in the report

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1578]
There is a checkbox item with 5 options. User selects all options and completes the activity.
**Actual**: Only the last option is recorded and displayed in the report
**Expected**: Every response option selection is recorded and displayed in the report for a multiselection items (checkbox, stacked items)

could you help me with next, please, @WorldImpex :
Then if user UNselects the response option this should be recorded as a response_option_selection as well.
Additional: Then would be good to show what exactly was selected in the options column (currently the Options column shows all possible options as in the general report)

**Full video**: https://www.screencast.com/t/HqdjNlXxbQJj
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cd43cfc6-58ed-4a16-a000-cd955b1cb976)

**Environment**:
https://web-staging.mindlogger.org/#/
Win 10 // Chrome 101
ML v0.20.6 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
owner: jeligi9407@zneep.com 123456
user: test-user2@mail.com qwerty
my applet (import) / regular items
my applet web (import) / regular items
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
Agreed on both points @natalia-muzyka

**Comment by natalia-muzyka** [comment]
@WorldImpex there is one more case. The item + optional text. 
User selects an option, and then enters an optional text.
**Actual**: Only the time when the optional text is finished entering is recorded (when the keyboard is closed). It replaces the response option time selection.
**Expected**: There should be two separate entries for the response option and optional text.

**Comment by WorldImpex** [comment]
Yes but we can backlog that one @natalia-muzyka

**Comment by natalia-muzyka** [comment]
@jj105 

1 - [mobile app&website] Text item has a new entry for every entered character. The entered value is mirrored in the report.
Expected: Until user closes the keyboard it should be recorded as one entry
Video: https://www.screencast.com/t/wHtTvOgNRTmO
Report:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/89f62ecc-8dad-4e43-a447-3fc9894f3d9d)

2 - [mobile app] stacked items response_selection_time is missing at all now
Expected: Every response option selection is recorded and displayed in the report for a multiselection items
Video: https://www.screencast.com/t/LLzMzzoR
Report:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/18139bd8-affc-41c9-b924-b5a74f54ea6c)

3 - [mobile app] media files names from the last response are missing in the "responses" column
Video: https://www.screencast.com/t/S3Fvd8OO
Report:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/023f196b-9a22-4723-ba35-3fe6352cfeed)

cc: @WorldImpex 

Environment:
https://web-staging.mindlogger.org/#/
Win 10 // Chrome 101
ML v0.20.9 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
owner: jeligi9407@zneep.com 123456
user: 
test-user1@mail.com 123456
test-user2@mail.com qwerty
my applet (import) / regular items
my applet web (import) / regular items
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@jj105 
1 - mobile app and website: entered characters are still displayed in the incorrect order :
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7692a9df-8597-42f8-9f93-fe54d1165340)

2 - fixed
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b02b9a70-8a42-4602-bf9f-7deef608f1df)

3 - fixed
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c2028951-20cd-4e15-b6c2-33499d37ad9a)

**Environment:**
https://web-staging.mindlogger.org/#/
Win 10 // Chrome 101
ML v0.20.12 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
owner: jeligi9407@zneep.com 123456
user:
test-user1@mail.com 123456
test-user2@mail.com qwerty
my applet (import) / regular items
my applet web (import) / regular items
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![Screenshot_1.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f378b034-dbb1-46ac-a66c-6f8cec85d984)

Environment:
https://web-staging.mindlogger.org/#/
Win 10 // Chrome 102
ML v0.20.13 staging
iPhone XR // iOS 14.3
Google Pixel 5a // Android 11
