### ISSUE TITLE
Update Media File Export

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1587]
1. Change the "response" header to "filename"
2. Remove the "filename: "s from the row and just show the filename 
3. Add file type at the end of the filename

**Comment by natalia-muzyka** [comment]
@WorldImpex @binarybottle 
are these updates related to the CSV report and activity journey files?

cc: @iradchenk0

**Comment by iradchenk0** [comment]
@WorldImpex 
is this issue still makes sense? column "response" contains also "value: " fields, so it's strange to rename it to "filename"

![image.png](https://images.zenhubusercontent.com/631f33964819d323745f21b6/c2467ed7-7be0-4e98-82ec-e1dadb138d86)

**Comment by WorldImpex** [comment]
For Media responses, the filename is shown because we can't show the media in an excel. This ticket is to enhance how we show media data in the file you are viewing so its easier to read 

I agree with leaving the column name as "response" vs changing it to "Filename"

**Comment by iradchenk0** [comment]
@WorldImpex @binarybottle 
So should i get rid of "filename: ", or this task can be closed? 

cc: @natalia-muzyka

**Comment by WorldImpex** [comment]
Yes remove filename @iradchenk0

**Comment by natalia-muzyka** [comment]
Works as expected for media items:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/dbe0851f-890e-4fcd-aca4-60a19005e7fc)

@binarybottle could you confirm, please, if this ticket is only for media export (photo, video, audio, drawing items), or the same should be done with cognitive tasks export (flanker, CST, a/b trails)?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/45fde034-f7db-40b9-9bf1-d94140fe4ecb)

cc: @iradchenk0

**Comment by binarybottle** [comment]
We want the organization and naming to be as consistent as possible.  If the header says "filename" than the row entries can just have the file name.

**Comment by natalia-muzyka** [comment]
@binarybottle it was clarified between Ivan and Wil that header(column name) should still says "Response" because the user might select response options, not only send files.

So as you said, we need to be consistent, then I think we need to remove "filename:" from the flanker, CST, and trail "response" column values in the "report" and "user journey" as well.

**Comment by natalia-muzyka** [comment]
@iradchenk0 here you can find all the cognitive tasks and export data:
new_user@ml.com / 123456 / Applet
Applet password: Qwe123!!!

**Comment by binarybottle** [comment]
Perhaps we need a response column and a response filename column?  If not, then yes, I would just remove"filename:"

**Comment by TatianaBessonova** [comment]
Verified as fixed. 'filename:' is removed from 'report' and 'activity_user_journey' files. "Response" column name is preserved.
Environment:
https://admin-staging.mindlogger.org/
v0.21.54
![fix1.png](https://images.zenhubusercontent.com/6343d78c6dec4b57073d9061/04929fb4-d703-4840-81fd-6af849052476)![fix2.png](https://images.zenhubusercontent.com/6343d78c6dec4b57073d9061/a54b7fc5-67cd-48d7-87ff-a70c4bca0095)
