### ISSUE TITLE
[Flanker Native timestamps] Flanker ZIP, activity journey CSV and report CSV are not downloaded after clicking the export button

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1621]
**Preconditions**
Mobile app is installed and launched
User is logged in to the account with a Flanker applet in mobile app and admin panel:
flanker_test@mail.com / 123456
https://admin-staging.mindlogger.org/

**Steps to reproduce**
1. Complete the Flanker activity on mobile app
2. Open the applet's Users tab
3. Click the export button on the top / enter applet password
4. Pay attention to the screen

**Video**: https://www.screencast.com/t/1fOElWLPB

**Environment**:
ML v0.20.14 staging
https://admin-staging.mindlogger.org/
Win 10 // Chrome 102
flanker_test@mail.com / 123456
Flanker 360
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@mtg137 data export doesn't work on a new account for DBT applet as well (CORS error)  after completing it on 0.20.15 staging:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/98fc1dd1-8db8-456f-900d-1451f0aacc23)

**Comment by natalia-muzyka** [comment]
The same issue reproduces now on the applet with configured Flanker activities.
Not reproduced on the Flanker activities created and processed before the Configurable Flanker feature deployment.

cc: @WorldImpex 

Video: https://www.screencast.com/t/IqiJM5Fh0uQ

Environment:
https://admin-staging.mindlogger.org/
jeligi9407@zneep.com	123456
Flanker test
Applet password	Qwe123!!!

**Comment by WorldImpex** [comment]
Export still does not function

**Comment by natalia-muzyka** [comment]
**!!! Flanker native export shows incorrect timestamps (0 and negative values):**

Video:
https://www.screencast.com/t/AmPmmdZ6wP

Export files:
https://drive.google.com/drive/folders/1bV0PsfqCAdO0ySBkuUTL59FVyGpQ-pM9?usp=sharing

Environment:
ML v0.21.8 staging
iPhone 7 // iOS 13.1.1
flanker_test@mail.com / 123456
Flanker 360 (3)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Plain build 0.21.7 on iOS and Android works as expected (+export):
- flanker applet from staging protocol
- configurable flanker

Video: https://www.screencast.com/t/0FE33Wsd13Qy

Environment:
ML v0.21.7 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
jeligi9407@zneep.com	123456
Flanker v4
Flanker_360
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
export files aren't downloaded:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/21c61859-81b1-4165-b05e-437c30764a1b)

Environment:
ML v0.21.13 staging
iPhone 7 // iOS 13.1.1
jeligi9407@zneep.com 123456
Flanker_360 (6)
https://raw.githubusercontent.com/mtg137/Flanker_applet/staging/protocols/flanker/flanker_schema
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Export is still not downloadable.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4c087029-2f20-48e6-a603-95d6024a8543)

Environment:
ML v0.21.17 staging
iPhone 7 // iOS 13.1.1
flanker_test@mail.com / 123456
Flanker_360 (7)
https://raw.githubusercontent.com/mtg137/Flanker_applet/staging/protocols/flanker/flanker_schema
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@WorldImpex export doesn't work after completing applet on 0.21.18 as well

**Comment by natalia-muzyka** [comment]
Export works after completing the Flanker activity on 0.21.18(plain) and 0.21.19(Native):
https://www.screencast.com/t/vi47JaVeR

**Comment by natalia-muzyka** [comment]
Export works after completing the Flanker activity on iOS and Android 0.21.21 staging (Native).

Export works for Configurable Flanker after completing activity on Android 0.21.21 staging (Native):

https://admin-staging.mindlogger.org/
jeligi9407@zneep.com 123456
Flanker test V6
Applet password Qwe123!!!
