### ISSUE TITLE
Add a scrollbar to Add Export Widget

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1629]
Expected: The user can select any applet in the list 
Actual: The user cannot scroll to the bottom 

https://images.zenhubusercontent.com/189080374/dfccff84-ec71-45d9-a68f-3c6c47925ba9/cannot_select_applets__2_.m4v

**Comment by natalia-muzyka** [comment]
@devbtech could you fix the next, please:
1 - remove horizontal scroll (it doesn't work anyway, the applet names are shortened with "...")
2 - don't show scrollbar if there is a small list

Video: https://www.screencast.com/t/2o6XPavrTM

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/00b771c3-876c-4c96-81f8-cd5c3efe9505)

https://admin-staging.mindlogger.org/
Win 10 / Chrome 102
jeraka1732@wodeda.com / 1234567890
user: jeligi9407@zneep.com

**Comment by MaksimYurys** [comment]
**Fixed** small issues

![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/02964d1a-67ed-4a35-baf1-52f3ddd1fc9a)

**Main bug is reproduced**

**Expected:** The user can select any applet in the list
**Actual:** The user cannot scroll to the bottom

![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/3783981e-d2d0-447d-951f-5427f5e9d4af)

Environment
https://admin-staging.mindlogger.org/
Win 10 / Chrome 102
jeraka1732@wodeda.com / 1234567890
user: jeligi9407@zneep.com

**Comment by MaksimYurys** [comment]
@devbtech Main bug is reproduced

Expected: The user can select any applet in the list
Actual: The user cannot scroll to the bottom

Environment
https://admin-staging.mindlogger.org/
Win 10 / Chrome 102
jeraka1732@wodeda.com / 1234567890
user: jeligi9407@zneep.com

Video: https://www.dropbox.com/s/z3kwl3mbpn3jluq/26E4AA06-C80C-4F0B-8AB4-1F6276F0F000.MP4?dl=0

**Comment by MaksimYurys** [comment]
Main bug is fixed

Expected: The user can select any applet in the list
Actual: The user cannot scroll to the bottom

Environment
https://admin-staging.mindlogger.org/
Win 10 / Chrome 102
jeraka1732@wodeda.com / 1234567890
user: jeligi9407@zneep.com

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/60a54943-c535-4e4b-b542-0aad1c9e6fb4)
