### ISSUE TITLE
The unexpected elements "Select activity" dropdown, "Save" and "Close" button are shown in the "Import schedule" modal

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1634]
**Need to confirm the expectations:** @WorldImpex 
The "Import schedule" modal is a separate element on mockup, and the "Create event" modal is shown under the "Import schedule".
Suppose that the "Create event" modal shouldn't be shown under the import schedule and there was just a mockup issue.
The "Import schedule" modal should have its own "Close" button on the top right.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3f9d8c2d-3f1b-48ac-8c48-3b731d375763)

**Requirements :**
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1546

**Environment:**
https://admin-staging.mindlogger.org/
v0.17.2
Win 10 / Chrome 102

**Comment by WorldImpex** [comment]
Correct @natalia-muzyka

**Comment by natalia-muzyka** [comment]
Verified as fixed: 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cffd796b-1bac-408b-aee7-20ecdbaa7b7e)

Environment:
https://admin-staging.mindlogger.org/
v0.17.2
Win 10 / Chrome 102
