### ISSUE TITLE
The Secret user ID info text and "Secret User ID" column are missing in the General schedule template

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1638]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Click the "View users" button on any applet
3. Open a general calendar
4. Click the "Import schedule" button
5. Pay attention to the screen

**Actual result:**
The Secret user ID info text and "Secret User ID" column is missing in the General schedule template

**Expected result**: 
The General schedule template includes the "Secret User ID" column. The info text about the Secret User ID is shown above the template example.
As per the requirements mockup:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1546

**Notes: Even if the Secret User ID is added to the CSV it won't be parsed (no matter if it's valid or not)**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cbc4205f-d3fb-42a1-9f77-b569826af19d)

**Environment**:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 102
v0.17.2

**Comment by techdev137** [comment]
I've discussed with @WorldImpex, we want to stick with original implementation.

because events with secret id can't be displayed on general calendar and it might confuse user.

**Comment by natalia-muzyka** [comment]
@mtg137 so the same CSV template should work then in the general, group, and individual calendar?

**Comment by techdev137** [comment]
@natalia-muzyka yes

**Comment by WorldImpex** [comment]
Originally @mtg137 asked, the below. 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/564fdc5d-e4c8-4595-b229-9c06b9ac042d)

So we need the secret ID field, it should be on general and individual schedule. If a admin schedules secret ID events on a general calender then the events are not shown on the calendar but they are shown on that secret ID's personal calendar

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/V94uNuaWj

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 102
v0.17.10
