### ISSUE TITLE
[UI] The "Clear", "Save" and "Add event" buttons are blocking event cards in the calendar "Year" view

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1646]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/71515723-f3d4-46c1-be80-487abab28ad9)

Environment:
Win 10 // Chrome 102
macOS 11.0 // Chrome 102
jeligi9407@zneep.com	123456
vbn123
Applet password	Qwe123!!!

**Comment by MaksimYurys** [comment]
**Fixed** 

![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/39a79b69-daf3-4472-b5d8-c0eae63e2c53)
Win 10 // Chrome 102
macOS 11.0 // Chrome 102
jeligi9407@zneep.com 123456
vbn123
Applet password Qwe123!!!
