### ISSUE TITLE
There is no confirmation message if the editor clicks the upload schedule button when there is a schedule already set up

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1649]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/

**Steps to reproduce**

1. Open a site https://admin-staging.mindlogger.org/
2. Click the "View users" button on any applet with the schedule already set up
3. Open an individual or general calendar
4. Click the "Import schedule" button
5. Pay attention to the screen

**Actual result:**
The "Import schedule" modal is opened. Confirmation message if the editor clicks the upload schedule button with a schedule already set up is missing.

**Expected result:**
If the editor clicks the upload schedule button after already importing a schedule or having a schedule already set up, show a confirmation message: "Importing a new schedule will replace the current schedule. Are you sure you want to continue?"

**Video:** https://www.screencast.com/t/GFETOY1H0ta2

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 102

**Comment by MaksimYurys** [comment]
**Fixed**

![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/9c41a43e-968a-46fd-a401-2af6a21eae43)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 102
