### ISSUE TITLE
The new event has access from 12AM to 12AM if there was no specified activity_start_time and activity_end_time in the CSV

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1656]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/

**Steps to reproduce**

1. Open a site https://admin-staging.mindlogger.org/
2. Click the "View users" button on any applet
3. Open an individual calendar of any user
4. Click the "Import schedule" button
5. Import a valid CSV schedule with the event that has no specified activity_start_time and activity_end_time
6. Click Submit button
7. Check the created calendar events

**Actual result**
The new event has access from 12AM to 12AM if there was no specified activity_start_time and activity_end_time in the CSV

**Expected result**
@WorldImpex The new "Always available" event is created if there was no specified activity_start_time and activity_end_time in the CSV

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/bbe19af1-a570-41f8-b462-e5f098dbc548)

**Environment:**
https://admin-staging.mindlogger.org/
v0.17.6
Win 10 / Chrome 102
jeligi9407@zneep.com / 123456
vbn123
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
at a minimum I think this should be 12 AM - 12 PM so its an all day event if times are specified

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f65307fe-795c-4984-8645-fff896a37b43)

Environment:
https://admin-staging.mindlogger.org/
v0.17.8
Win 10 / Chrome 102
