### ISSUE TITLE
The new event has notifications turned ON if there was no specified notifications time in the CSV

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1657]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/

**Steps to reproduce**

1. Open a site https://admin-staging.mindlogger.org/
2. Click the "View users" button on any applet
3. Open an individual calendar of any user
4. Click the "Import schedule" button
5. Import a valid CSV schedule with event that has no notifications time specified
6. Click Submit button
7. Check the calendar events

**Actual result**
The new event has notifications turned ON if there was no specified notifications time in the CSV

**Expected result**
The new event has notifications turned OFF if there was no specified notifications time in the CSV

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e947f7d5-6743-46a8-b88d-17872c278478)

**Environment:**
https://admin-staging.mindlogger.org/
v0.17.6
Win 10 / Chrome 102
jeligi9407@zneep.com / 123456
vbn123
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@mtg137 it looks like only UI is fixed, because when I'm trying to save the schedule I get the same 500 Error as if I was trying to save with the "Notification" toggle ON but without specified time.

Video (upload CSV and try to Save schedule): https://www.screencast.com/t/3OcJq9Jm
Video (create an event without specified Notification time and try to save): https://www.screencast.com/t/9YMvEIJr

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8815298e-0940-47a6-a837-8feaf851ff15)

Environment:
https://admin-staging.mindlogger.org/
v0.17.7
Win 10 / Chrome 102
jeligi9407@zneep.com / 123456
vbn123, my applet import
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@mtg137 
1 - Issue is still reproducible after uploading CSV schedule.
Video: https://www.screencast.com/t/rmJh1Epy1c6N
2 - Now it's possible to save the event with turned-ON notifications, but not specified notification time 
Expected: it shouldn't be available to save such an event. At least let it be a 500 error(as previously) and I'll create a new ticket, that there should be validation on saving the card or saving the schedule. 
Video: https://www.screencast.com/t/bRlRCl7S3

**Comment by techdev137** [comment]
@natalia-muzyka - could you let me know email/password of your account for comment 1?

**Comment by natalia-muzyka** [comment]
@mtg137 
owner: jeligi9407@zneep.com	123456
applet: test conditional (1)
user: jeraka1732@wodeda.com	1234567890

**Comment by natalia-muzyka** [comment]
#1 Verified as fixed: https://www.screencast.com/t/nfVyxAMgdg

Environment:
https://admin-staging.mindlogger.org/
v0.17.8
Win 10 / Chrome 102
