### ISSUE TITLE
[UI] The "Remove" button goes beyond the Event modal if the activity name has a maximum length

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1661]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2191889f-56bc-4591-a2fb-7cefd1908a0b)

Resolutions:
1920x1080
1366x768
1536x864
1280x720
1600x900

Environment:
https://admin-staging.mindlogger.org/
v0.17.6
Win 10 / Chrome 102
jeligi9407@zneep.com / 123456
vbn123 / Vbn123Vbn123Vbn123Vbn123Vbn123Vbn123Vbn123Vbn123Vbn123V
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
**Fixed**

![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/7db713f3-b847-4032-ae11-ff172291875e)

Resolutions:
1920x1080
1536x864
1280x720
1600x900

Environment:
https://admin-staging.mindlogger.org/
v0.17.7
Win 10 / Chrome 102
qqtest.02@gmail.com / Qqww!123
aaaaaaa / "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
Applet password Qqww!123
