### ISSUE TITLE
[UI][Reviewer assessment] Response option images and text aren't vertically aligned

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1668]
**Preconditions**
The user is logged in on the admin panel:
https://admin-staging.mindlogger.org/
ml3_general_acc@protonmail.com / 12345678
There is an applet with a reviewer assessment.
Response options have uploaded images with a different ratios.

**Steps to reproduce**

1. Open the site https://admin-staging.mindlogger.org/
2. Click on the "View Users" button on the applet with a reviewer assessment
3. Click on the "View Data" button of any user
4. Click on the Review tab
5. Click on the "Assessment" tab
6. Pay attention to the assessment response options

**Actual result**
Response option images and text aren't vertically aligned on the assessment tab

**Expected result**
Response option images and text are vertically aligned on the assessment tab

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/576059bf-dc8b-4d12-99e3-d7f1b966b91e)

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 / Chrome 102
macOS BigSur 11.0 / Chrome 102
ml3_general_acc@protonmail.com / 12345678
My applet ML3 (web) / Reviewer assessment
Applet password: Qwe123!!!

**Comment by MaksimYurys** [comment]
Bug was fixed 

Attachents: ![Snag_1f36af5b.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/b2fa24c6-e748-42f7-994b-0370ea465b75)
![Snag_1f36f0aa.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/2b8726ca-2064-40cc-9525-d3d9ba09720a)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 102
macOS BigSur 11.0 / Chrome 102
ml3_general_acc@protonmail.com / 12345678
My applet ML3 (web) / Reviewer assessment
Applet password: Qwe123!!!
