### ISSUE TITLE
[Flanker] There is the "undefined" value in the "block_number" column

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1691]
**Expected:**
There should be:
0 - if practice
1, 2, or 3 - according to the trial #

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/787dd3bd-d7c4-4fe8-8f97-43c106e8cc83)

**Environment:**
https://admin-staging.mindlogger.org/

flanker native:
flanker_test@mail.com / 123456
Flanker 360 (8)

plain:
tets-user17@mail.com / 123456
Flanker 360 (1)

https://raw.githubusercontent.com/mtg137/Flanker_applet/staging/protocols/flanker/flanker_schema
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
The issue is still reproducible for configurable flanker activity:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d31f0908-893d-4d35-b640-d6fe97533ada)

Verified as fixed for Flanker applet:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2a0ee147-54f6-422c-b3e9-f074898700fc)

0.21.21 Native build
iPhone 7 // iOS 13.1.1

**Comment by jj105** [comment]
the PR for fixing this issue on config flanker is not merged yet.
https://github.com/ChildMindInstitute/mindlogger-applet-builder/pull/942

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/bc732239-d26b-4faf-a46a-70a8cade5212)

0.21.25 Native build
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
