### ISSUE TITLE
The Export Schedule button is missing under the Download template when the schedule has been imported

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1698]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/

**Steps to reproduce**

1. Open a site https://admin-staging.mindlogger.org/
2. Open the general calendar of any applet
3. Click the "Import schedule" button, click "Yes"
4. Upload valid CSV schedule
5. Download template and compare with 
-the previously uploaded schedule 
-the table in the modal
6. Submit the uploaded schedule
7. Click the "Import schedule" button, click "Yes"
8. Download template and compare with 
-the previously uploaded schedule 
-the table in the modal
9. Observe the result

**Actual result:**
The Export Schedule button is missing under the Download template when the schedule has been imported. The newly uploaded schedule is available with the "Download template' button and only until admin submits the schedule.

**Expected result:**
If a schedule has been imported, then show a button under download template called Export Schedule.
@WorldImpex  Need to confirm that my expectations are correct:
On the next opening the "Import schedule" modal there should be available to download the previusly uploaded and saved file.
The CSV preview should match the previuosly uploaded file. There's no need to update the schedule table if there were some changes made in the schedule with UI, it should be just the same file that was uploaded and saved the last time.
The first default template should be always available with the "Download template" button.

**Video**: https://www.screencast.com/t/z7nk2zngw

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103

**Comment by WorldImpex** [comment]
@natalia-muzyka Agreed

**Comment by MaksimYurys** [comment]
Verified as fixed

Video: https://images.zenhubusercontent.com/189080374/712baae9-7365-408b-9f59-405121cc19eb/5802e97c_630b_4ec6_a53e_124574e6bf19.mp4

Environment:
Win 10 // Chrome 102
https://admin-staging.mindlogger.org/

**Comment by MaksimYurys** [comment]
The uploaded CSV file have wrong "Activity End Time" and secret id "undefined"

Videos: 
The "Activity End Time" - https://images.zenhubusercontent.com/189080374/ba852332-4ca1-470a-9124-2e759b784955/95950a58_1c7e_4eb8_85ef_b1504c858023.mp4

The secret id "undefined" - https://www.screencast.com/t/Yrah8vtrfKF

Environment
Win 10 // Crome 102
https://admin-staging.mindlogger.org/
qqtest.02@gmail.com // Qqww!123

**Comment by natalia-muzyka** [comment]
@devbtech 

fixed: 
1 - the "activity end time" issue 
2 - the secret id "undefined" issue
Video: https://www.screencast.com/t/EwfXLNqxx

Environment
Win 10 // Crome 103
v0.17.11
https://admin-staging.mindlogger.org/
