### ISSUE TITLE
I want to create a new Applet from an existing

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#171]
As an editor, I want to duplicate an existing applet from my database and make changes to it so that I can customize it for a different use

Requirements: 
- Allow user to duplicate an existing applet and require the user to change the applet name. If the user does not change the name then we simply add a (1), etc to the end of the new applet's name.  
- Editing is covered in ChildMindInstitute/mindlogger-app#119
- The applet is saved as new 
- Users and schedules are not copied to the new applet. 
- This effort does include retrieving a GitHub stored protocol
- When an applet is duplicated, the organization roles (manager, reviewer, coordinator, and editor) are not retained for the new applet. Only Owner and editor roles are stored for the new applet. User access is not copied over either

Applet Builder
- Editor should be landed on the applet builder with all fields filled out mirroring the original applet. 
- All fields should be editable  

# 3 in the below diagram 
![schemaFlow.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/3791cc9c-a9ef-48eb-b7b0-72af6d3d8d0f)

Acceptance Criteria 
Given I am an editor with applets in my database
When I navigate to my activity builder
Then I select which applet I want to duplicate and hit duplicate 

Given I am an editor
When I duplicate an applet of mine
Then I am required to rename it before I can edit it

**Comment by sergeysemenuta** [comment]
Closing this ticket out. Works as expected regarding the Requirements
