### ISSUE TITLE
The duplicated applet with the activity flow is not editable

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1711]
**Preconditions**
The user is logged in to the account with the applet which contains the activity flow
https://admin-dev.mindlogger.org/
user3-dev@ml.com / 123456

**Steps to reproduce**

1. Open a site https://admin-dev.mindlogger.org/
2. Duplicate the applet which contains the activity flow (set up the applet password and confirm)
3. Refresh the dashboard
4. Click edit on the duplicated applet
5. Pay attention to the screen

**Actual result**
The duplicated applet with the activity flow is not editable

**Expected result**
The duplicated applet with the activity flow is editable

**Video**: https://www.screencast.com/t/sMrPGV9sIwB

Environment:
https://admin-dev.mindlogger.org/
v0.17.12
Win 10 / Chrome 103
user3-dev@ml.com / 123456
activity flow 4 (original applet to duplicate)

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video:https://images.zenhubusercontent.com/189080374/8315785f-da8d-4480-865e-fc26b04bb50e/26a8477b_d126_4f89_a425_88ff339bde05.mp4

Environment:
https://admin-dev.mindlogger.org/
v0.17.16
Win 10 / Chrome 103
