### ISSUE TITLE
The *activity name* plug is displayed in the "Invalid CSV File" error pop-up instead of the actual activity name

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1720]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/
jeligi9407@zneep.com / 123456

**Steps to reproduce**

1. Open a site https://admin-staging.mindlogger.org/
2. Click the "General calendar" button on any applet with at least one user (vbn123)
3. Click the "Import schedule" button, and click "Yes"
4. Upload the CSV schedule which contains one event with Repeats="Yes" but not specified "Frequency"
5. Pay attention to the screen

**Actual result:**
The *activity name* plug is displayed in the error pop-up instead of the actual activity name after uploading the CSV schedule which contains one event with Repeats="Yes" but not specified "Frequency"

**Expected result:**
The activity name of the failed activity is displayed in the error pop-up after uploading the CSV schedule which contains one event with Repeats="Yes" but not specified "Frequency"

**NOTES: REPRODUCIBLE AFTER UPLOADING THE CSV WIH INVALID ACTIVITY NAME**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1a3586d9-04e3-40a4-9408-6bb6ef2a4c1b)

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cc162371-e2e0-49f6-bab4-c29542ac8a0a)

**Environment:**
https://admin-staging.mindlogger.org/
v0.17.11
Win 10 / Chrome 103
jeligi9407@zneep.com / 123456
applets:
vbn123 , TokenLogger applet (Anita)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
fixed for repeats:Yes and no frequency.
@jj105 the issue is still reproducible after uploading the CSV with the invalid activity name:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7d3839ce-da7d-4fdc-a709-3ae2c91a8526)

Environment:
https://admin-staging.mindlogger.org/
v0.17.16
Win 10 / Chrome 103
jeligi9407@zneep.com / 123456
applets:
vbn123
Applet password: Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshots:
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/4e36c54d-8379-47ab-b3a8-6fc4b35ba5a9)
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/5b066bd6-858c-449f-98bf-77afb8cbe79b)
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/ce1c72e5-2e9f-4bd5-b809-80d6ec3e9980)

Environment:
Win 10 // Chrome 103
https://admin-staging.mindlogger.org/
v0.17.17
