### ISSUE TITLE
[UI] The activity flow cards are not distinguished by color on the calendar

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1723]
**Preconditions**
User is logged in on the admin panel
There is the applet with at least two activity flows

**Steps to reproduce**

1. Open a site https://admin-dev.mindlogger.org/
2. Open the General calendar of the applet with the activity flows
3. Pay attention to the color of the event cards
4. Add a new flow and save the applet
5. Open the Calendar
6. Observe the result

**Actual result**
The activity flow cards are not distinguished by color on the calendar

**Expected result**
All the event cards are distinguished by color on the calendar. Design: https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a33aed53-397b-48c3-a50b-9d8fd21dd759)

**Environment:**
https://admin-dev.mindlogger.org/
Win 10 / Chrome 103
user3-dev@ml.com / 123456
Activity Flow 4 
Applet password Qwe123!!!

**Comment by binaryExDev** [comment]
@natalia-muzyka The fix is deployed to staging (admin-staging)

![image.png](https://images.zenhubusercontent.com/5fc8d89138215d1055c6d606/b75a1bbd-d755-4f83-b286-a221ce82f162)

**Comment by MaksimYurys** [comment]
@binaryExDev 
Bug is reproduced

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/4640e997-ee25-4cf4-ac27-ce3159e9efc8)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
qqtest.02@gmail.com // Qqww!123
applet - zxczxc // Qqww!123

**Comment by binaryExDev** [comment]
@MaksimYurys Just tested in your account but it works like this:
![image.png](https://images.zenhubusercontent.com/5fc8d89138215d1055c6d606/f15579e5-de31-4931-b117-6b0f38bc6f04)

**Comment by natalia-muzyka** [comment]
@binaryExDev the issue is reproducible right after adding a new flow. If you open a calendar with cleared cache then the issue is not reproducible.
Video: https://www.screencast.com/t/Mvmc6vjzn

**Comment by MaksimYurys** [comment]
@binaryExDev the issue is reproducible right after adding a duplicated flow. Other bugs are fixed.

Video: https://images.zenhubusercontent.com/189080374/f33c755a-0ad1-4a61-b364-b0bc1f11e6c6/7ae7149c_c581_4c26_8e4a_b32201adf86f.mp4

Environment:
https://admin-staging.mindlogger.org/
v0.17.14
Win 10 // Chrome 103
JhoneeMind@gmail.com // Qqww!123
ConfReports 3 // Qqww!123

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video: https://images.zenhubusercontent.com/189080374/f33c755a-0ad1-4a61-b364-b0bc1f11e6c6/7ae7149c_c581_4c26_8e4a_b32201adf86f.mp4

Environment:
https://admin-staging.mindlogger.org/
v0.17.14
Win 10 // Chrome 103
JhoneeMind@gmail.com // Qqww!123
ConfReports 3 // Qqww!123

**Comment by natalia-muzyka** [comment]
@devbtech could you fix event cards on the calendar as well, please?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5d93be15-ea35-400f-80b7-595fccc51ccb)

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/6b3634d5-4e6d-4ed2-a280-cb9bc2d5f7f3)

Environment:
https://admin-staging.mindlogger.org/
v0.17.18
Win 10 // Chrome 103
