### ISSUE TITLE
Admin report is not available after completing the activity on the mobile app for the first time

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1737]
Video: https://www.screencast.com/t/FiI4tTfZ4yNH

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
Config reports v2 / Test A
Applet password	Qwe123!!!

**Comment by fullstackdev065** [comment]
@natalia-muzyka I think you have disabled "Make Report available for Export" button on reports screen on applet-builder.

I think download export button works only when the option is enabled.

**Comment by natalia-muzyka** [comment]
@astef021 probably you were right, I'm able to download the report after selecting "make export available", but PDF is broken as in the email.

There is the case in the new applet - when I'm passing activity for the first time, I see the time of response on the admin, but the report is not downloadable on admin DataViz and is not received to the email.
Video: https://www.screencast.com/t/vhTvfH3aV

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
Config reports v7 / Test A
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@astef021 
UPD: the "failed to load PDF document" is shown after 3rd wrong password. I'm trying to enter 123456 or with the applet password. Is there any other password?

**Comment by natalia-muzyka** [comment]
@astef021 could you clarify, please, the issue that I can get the report only after the second completion of the activity is fixed?
we were discussing and resolving the password issue in the end, and I'm not sure if the main issue wasn't lost

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/TZdt3GbsLcHb

Environment:
ML v0.21.39 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
Config reports v9 
Applet password Qwe123!!!
