### ISSUE TITLE
Variable values do not match the user's responses

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1743]
**Preconditions**
User is logged in on website:
test-user1@com.us / qwerty
There is the activity with the configured exportable report.
The radio, checkbox, slider, text, age, and date variable are added to the markdown field in the report.

**Steps to reproduce**

1. Complete the activity on mobile app by selecting any responses on the radio, checkbox, slider, text, age, and date screens.
2. Download the admin report on the user's DataViz.
3. Pay attention to the variable values in the report.

**Actual result**
No age value in the report after completing activity on website

**Expected result**
Age value is displayed in the report after completing activity on website

**Reproduces for: radio, checkbox, slider, text, age, and date**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4ac18af2-4be3-4e99-a357-0cd30af69672)

**Environment:**
https://admin-staging.mindlogger.org/
https://admin.mindlogger.org/
Win 10 / Chrome 103
staging account:
user-stg@ml.com / 123456
config reports v9 / test D
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@astef021 The issue is still reproducible for: radio, checkbox, slider, text, date

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2c30f341-2523-47a7-a813-24486f365245)

**Comment by natalia-muzyka** [comment]
@astef021 date shows the actually selected month - 1

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4e576e22-2d9f-4cf0-8699-9be4379cd68a)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v9 / test D
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9fbad6e5-555e-4204-8d28-940c8d7823bc)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v9 / test D
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
The issue is reproduced in the printed items (radio, checkbox, slider, text) for variable values of radio button, checkbox, slider, age, date):

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9c981b09-339b-41a2-a8be-e6cbf281a367)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v9 / test D
https://admin.mindlogger.org/
Win 10 / Chrome 103
my applet 2 / regular activity 2
Applet password: Qwe123!!!

**Comment by karser** [comment]
The Prompt 6: "your age" response didn't show up in the report. I fixed it.
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/3cb0c0ad-f0cd-4d14-b308-e9935b57de62)

**Comment by karser** [comment]
Now the responses in printed items are rendered correctly as well
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/203ccbf9-3f7b-4cbb-be6e-e24b78c146b8)

![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/8506c46a-997e-4151-b3f1-dff5cfa3e1d4)

**Comment by karser** [comment]
Also added variables support to the **email body** with **activity prefix**.

Configuration:
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/a090a2a5-14cd-46a1-9556-0be86f5cdd9a)

Received email:
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/2fb36e73-cd97-4ac6-b9fd-9715094d8130)

All available variables:
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/59c56648-596d-4efe-bc93-4f0cdfe575ad)

**Comment by natalia-muzyka** [comment]
@karser can I change the server configurations in this fixed applet or this is the new server we need to use?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f4b76625-97c7-46bf-8614-4c8b72b8e3d3)

**Comment by natalia-muzyka** [comment]
@karser verified as fixed in the report: age variable representation is fixed, and all the variable values(radio, checkbox, slider, text, date, age) are rendered in the printed questions (prompts and options) as expected.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d13c4f84-8512-4ee2-a4ea-7cf8fc86e330)

In the email body variable value won't be supported if activity name contains a character other than space or underscore.
For item names we have restrictions: it is possible to set an item name by using letters, numbers, and underscores only.
For activity names there are no such restrictions and symbols are common in use.

Video: https://www.screencast.com/t/9yVfIBfGR

I don't remember such a requirement for email body (to support variable values), but I think we could create a new ticket for this issue and clarify if we need to fix it now and what's the priority.

cc: @WorldImpex @binarybottle @eleonova-scn

**Comment by natalia-muzyka** [comment]
The email body should support variables, so ticket is reopened.

**Comment by karser** [comment]
@natalia-muzyka  Should be fixed
![image](https://user-images.githubusercontent.com/1675033/190631332-8a9b42ac-3791-4c83-b70a-3f78b1d7f9b9.png)

**Comment by natalia-muzyka** [comment]
Verified as fixed: 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c0fd2e10-0852-496c-aeb4-74abc0c3e2ad)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v9 / test D
