### ISSUE TITLE
Page breaks are happening in the middle of the content

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1745]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/fc7f818d-b489-4840-b69b-7a51b89296c7)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v9 / test D
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@astef021 is still reproducible on markdown/html elements, like images, tables :

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7d18fa53-6561-4ac2-8c8a-65a8f48d4dbe)

**Comment by natalia-muzyka** [comment]
@astef021 reproducible with a large print question as well:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/76856a20-2292-48ff-95d4-3be38fe7f030)

@WorldImpex in the scope of page breaks:
 is this expected that if there are two question blocks that can't be displayed fully on one page they will be displayed on different pages? (we don't have such example in design):

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/56c491be-4aad-43ed-906b-ff80ae90ffa0)

**Comment by fullstackdev065** [comment]
@natalia-muzyka I fixed page break issue for response options, items, tables, and images.

but for markdown elements, could you please add "page-break-inside: avoid;" to the style of elements that you want page break?
pdf pages have too many page breaks if we do for all markdowns in the code, so I think page breaks should be decided by applet editors.

example: div style="page-break-inside: avoid;"

**Comment by astef021** [comment]
@natalia-muzyka I fixed page break issue for response options, items, tables, and images.

but for markdown elements, could you please add "page-break-inside: avoid;" to elements that you want page break?
pdf pages have too many page breaks if we do for all markdowns in the code, so I think page breaks should be decided by applet editors.

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/IwNsW9kQ

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
macOS Catalina 10.15 / Chrome 103
user-stg@ml.com / 123456
config reports v9 / test D
Applet password: Qwe123!!!
