### ISSUE TITLE
The Summary screen is not added as the first page in the admin activity and flow report

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1748]
Expected;
If the summary screen is turned on with alerts or scoreID then the first page of the report should be the summary screen

@WorldImpex
Case:
If not combined, then there is one file for each activity in the flow in one email
Question:
Were should be the combined flow summary? Or should there be added separate summary pages to every activity report?

Requirements:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/878

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v9 / test A, B, C, D; My Flow 2
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
The summary should show on the report that the summary was shown on the activity

**Comment by natalia-muzyka** [comment]
@WorldImpex I mean if there is a separate report for every activity (not combined), then this summary should be a separate file as well?

**Comment by WorldImpex** [comment]
Yes

**Comment by natalia-muzyka** [comment]
Verified as fixed for single activity report and combined flow report:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c1a78a12-ab11-474c-b8ea-976c54f90296)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reprots v11 / test B, my Flow combined
Applet password Qwe123!!!
