### ISSUE TITLE
The invalid activity name error is shown after uploading the CSV Schedule for Activity Flow 

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1752]
Expected: It should be available to upload a CSV schedule for activity flow

Video: https://www.screencast.com/t/bZQkI3AAe

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
v0.17.16

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video: https://images.zenhubusercontent.com/189080374/715cdeff-94ff-48bf-8211-d7cc63bda781/c4100e16_af61_48e8_bea0_0b3aa483653c.mp4

https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
v0.17.17
