### ISSUE TITLE
The uploaded image is displayed as the URL link in the PDF report

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1753]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/59ebfec6-cee5-4224-9633-80ccd69aa818)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com	/ 123456
config reports v10 / test a
Applet password	Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/251d410f-6d00-4215-9ded-31414dff0e63)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
JhoneeMind@gmail.com // Qqww!123
little Re-testing // created activity 1
applet password // Qqww!123
