### ISSUE TITLE
Markdown is not applied to the printed questions

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1754]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/423a482c-1495-47e0-a159-500c136d4dc8)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v10 / test a
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/c7ee9bbd-f370-46de-87a3-64acec8b59a5)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
JhoneeMind@gmail.com // Qqww!123
little Re-testing // created activity 1
applet password // Qqww!123

**Comment by natalia-muzyka** [comment]
@mtg137 
The issue is still reproducible. I see bold and italic text is not formatted as expected 9in markdown and HTML as well):

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1d22bb15-84b4-4149-a7a2-bf5d5bff3b11)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
ml3_general_acc@protonmail.com / 12345678
Config report & Activity flow
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot:
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/cb059a4d-c685-4717-afba-50468c188e14)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
JhoneeMind@gmail.com // Qqww!123
applet - little Re-testing 2 / created activity 1
applet password // Qqww!123
