### ISSUE TITLE
There is too small space between the item name and prompt in the printed item block

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1755]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6624e148-ef7d-4173-968d-31219c7c78f3)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v10 / test a
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: 
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/1be615cf-ce88-4f31-9afb-ff193edb6aaf)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v10 / test a
Applet password Qwe123!!!
