### ISSUE TITLE
There is the combined admin and email report after completing the flow with the disallowed "Combine" option

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1762]
Expected:
Allow an editor at the activity flow level to combine reports from each linked activity into one report.
If not combined, then there is one file for each activity in the flow in one email.

Requirements:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/874

Video: https://www.screencast.com/t/vdQf1bbIxymK

Environment:
https://admin-staging.mindlogger.org/
Win 10/ Chrome 103
user-stg@ml.com / 123456
config reprots v11 / my Flow not combined
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@WorldImpex @jj105 @astef021 is this a bug or acceptable behavior for the Config reports v1 because of the email URL fix?

**Comment by WorldImpex** [comment]
We should expect with combined on there is 1 URL and with combined off multiple URLs. Could the link in the email send the user to a folder of PDFs to download each one individually?

**Comment by jj105** [comment]
I think it's not easy to show folders in s3 bucket. can we send email each time user completes an activity in activity flow in if combine reports is turned off?

**Comment by WorldImpex** [comment]
Yes that is fine for now @jj105

**Comment by natalia-muzyka** [comment]
Verified as fixed for Android: https://www.screencast.com/t/Bb7q1eq1Q

Environment:
ML v0.21.43 staging
Google Pixel 5a // Android 11
user-stg@ml.com 123456
config reports v11 / my flow not combined
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed for iOS: https://www.screencast.com/t/OqBq4fcl

Environment:
ML v0.21.48 staging
iPhone 7 // iOS 13.1.1
user-stg@ml.com 123456
config reports v11 / my flow not combined
Applet password Qwe123!!!
