### ISSUE TITLE
There is a blank page after Report summary if report filled out all the first page

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1764]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4ef95050-002a-40eb-ba95-322f638b4c8e)

Environment:
https://admin-staging.mindlogger.org/
Win 10/ Chrome 103
user-stg@ml.com / 123456
config reprots v9 / test D
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/1f7ec180-1ebe-4c7b-b1ee-646da63f2d8f)![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/5e5bc084-7aaa-4e36-9699-b6aa35784711)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
JhoneeMind@gmail.com // Qqww!123
little Re-testing // created activity 1
applet password // Qqww!123
