### ISSUE TITLE
Activity flow name is changed in the calendar after the activities within the flow / the flow was hidden

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1766]
**Preconditions**
The user is logged on admin panel

**Steps to reproduce**

1. Set up the schedule for the activity flow and save
2. Move to the flow tab and hide the flow (click on the "Eye" icon to hide)
3. Save the applet
4. Move back to the calendar
5. Pay attention to the flow's name

**Video**: https://www.screencast.com/t/ImX3jq7bp

**Notes:**
Reproduced when the activity within the flow was hidden as well

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f4d00df9-0425-4d0e-ad32-574ff9b7941b)

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
config reports v11 / one-time completion, daily, particular day flow
activity flow 2
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
@jj105 verified as fixed for admin panel. Bug reproduced for mobile app.

Video: https://images.zenhubusercontent.com/189080374/6bb941ea-8543-4b7f-80d9-156fc69ea25b/0cf335e9_6005_46c8_a0ed_c72802de621d.mp4

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/bb82b0b7-9412-4d5a-b02d-61114d80629d)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
JhoneeMind@gmail.com // Qqww!123
applet - little Re-testing 2 // Qqww!123
ML v0.21.48 staging
iPhone 8 // 14.7.1
Samsung Galaxy S8 // Android 8

**Comment by natalia-muzyka** [comment]
@iradchenk0  
Flow's name is still changed after hiding the flow in the builder: the undersores are added automatically to the flow name instead of the spaces and the flow name is removed from the event modal (after clicking on the event card).
Noticed that actually any edits and saving in the builder caused this issue.

Reproduces on prod as well.

Video: https://www.screencast.com/t/qTV4heZ4560

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 106
new_user@ml.com / 123456
Schedule flow check
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 107
macOS 10.15 / Chrome 107 / Safari 13.1.2
