### ISSUE TITLE
The activity is not hidden on the mobile app/website after activating the  "Hidden" toggle on the Calendar

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1767]
Expected:
If an activity or activity flow has been hidden in the applet builder then when creating a scheduled event for one show the scheduling module with Hidden turned on.
If the coordinator hides an activity, then it should be hidden in the applet builder.

Requirements:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1552

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/49fea11f-f1dc-4512-8a5f-5fd259b6e651)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
user-stg@ml.com / 123456
activity flow 2
Applet password Qwe123!!!

**Comment by binarybottle** [comment]
@natalia-muzyka -- Re: "If the coordinator hides an activity, then it should be hidden in the applet builder."

This means that if an admin toggles an activity to be hidden, that they can still see the activity in the builder, but respondents will not see it in the mobile applet, correct?

**Comment by natalia-muzyka** [comment]
@binarybottle correct. It works now on the activity flow, but missing on the activity. Wil was saying that the show/hide (eye) button should be in the same state as in the calendar.

**Comment by WorldImpex** [comment]
That is correct

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/1f4a31dc-6d94-46fb-9d1e-8a3ff9fe25a6)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
JhoneeMind@gmail.com // Qqww!123
applet - little Re-testing // Qqww!123

**Comment by natalia-muzyka** [comment]
The "Hidden" toggle is present now but doesn't work properly for the activity. After activating the toggle on the "Calendar" for a single activity and saving the schedule:
1 - Activity is not actually hidden in the app / on the website
2 - The "Hide/Show" button (eye) is not changed in the applet builder on the activity card
3 - The event card firstly shows the toggle ON, and then OFF after moving to the dashboard and reopening the calendar

In the video, I'm comparing how the logic works for flow (correct) and for the single activity (issue).
Video: https://www.screencast.com/t/JbCOqoqPPeG

Environment:
https://admin.mindlogger.org/
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
staging account:
test_account@ml.com  / 123456
applet: Hidden activity/flow in the calendar
Applet password: Qwe123!!!

**Comment by TatianaBessonova** [comment]
The issue is reproduced on [https://admin-staging.mindlogger.org/](url), appled builder v0.18.9-alpha:
After creating of a calendar entry for an activity with Hidden flag and saving the calendar the activity is **not** marked as hidden in the applet builder.

**Comment by natalia-muzyka** [comment]
just a workaround, if it's not a big effort and we have time for it:
to prevent using this option from the calendar we could grey out(make unclickable) the "Hidden" toggle in the calendar, and add some info text below it, like "activity or flow is hidden. please, unhide it in the builder".

@iradchenk0 how much time and effort do you think it could take?

cc: @eleonova-scn

**Comment by natalia-muzyka** [comment]
Verified as fixed except for one blocked case. 
One case can't be checked (flow name is removed from event after hiding it in the builder),
So the issue needs to be retested after fixing the related to flow scheduling issue:
https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin-old-vue/1766

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 107
macOS 10 / Chrome 107 / Safari 13.1.2

**Comment by natalia-muzyka** [comment]
Verified as fixed.
There is one ticket updated with the lower priority related to this update in JIRA:
https://mindlogger.atlassian.net/browse/MIN-22

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 107
macOS 10.15 / Chrome 107 / Safari 13.1.2
