### ISSUE TITLE
The applet's owner can create the user without a nickname and secret ID

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1778]
Preconditions:
The owner is logged in at https://admin.mindlogger.org/
The owner has invited users for applet(s)

Steps to reproduce:
1. Delete the user's secret ID.
2. Delete the user's nickname.
3. Go to the "View users" page.
4. Pay attention to the screen.

Actual result: 
The applet's owner can create the user without a nickname and secret ID

Expected result:
The applet's owner can't create the user without a secret ID

Screenshot:
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/06c16f20-c6fe-43ee-b6e1-470997431739)

Environment:
Win 10 // Chrome 103 
https://admin.mindlogger.org/
mndlgr04@gmail.com // Qqww!1234

**Comment by DeepDeveloper1996** [comment]
I have also added validation from backend side in order to require these fields, pull request `https://github.com/ChildMindInstitute/mindlogger-backend/pull/1307`

**Comment by natalia-muzyka** [comment]
Verified as fixed: 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7b7d1158-f052-4381-9960-e30e5523703d)

Win 10 // Chrome 105.0.5195.127
https://admin-staging.mindlogger.org/
