### ISSUE TITLE
Applet image is displayed on the 2nd report page

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1779]
**Preconditions**
There is the activity with configured report. Export is allowed. The recipient email and server are configured. 
The applet has uploaded applet image.

**Steps to reproduce**
1. Complete activity on mobile app
2. Check the recipient's email
3. Pay attention to the second page in the report

**Actual result:**
Applet image is displayed on the 2nd report page

**Expected result:**
Applet image is not displayed on the 2nd report page

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3d641f45-21b8-4ff6-9dc1-0b0cc1fafef5)

**Environment:**
https://admin.mindlogger.org/
https://admin-staging.mindlogger.org/
prod account:
test-user1@com.us	qwerty
my applet 2 / regular activity
Applet password	Qwe123!!!

**Comment by e-kass** [comment]
See Issue #: 2859

https://github.com/ChildMindInstitute/mindlogger-app/issues/2859

**Comment by hotavocado** [comment]
To clarify, the **applet watermark** should be the image showing at the top of every page of the report, the **applet image** (which is displayed on the applet list in the mobile app, web app, and admin panel) is not supposed to show up at all. There seems to have been some confusion between the two image fields.

**Comment by Damirkhon** [comment]
@eleonova-scn please clarify, should applet image be removed? should watermark be printed instead?

**Comment by eleonova-scn** [comment]
Yes, right, please see Mike's comment above:
"To clarify, the **applet watermark should be the image showing at the top of every page of the report**, the **applet image** (which is displayed on the applet list in the mobile app, web app, and admin panel) **is not supposed to show up at all**. There seems to have been some confusion between the two image fields."

**Comment by yzenchanka** [comment]
Verified as fixed. The applet watermark is showing at the top of every page of the report, the applet image isn't showed up at all
**Environment:**
https://admin-staging.mindlogger.org
Mobile app version 0.21.59
Staging account:
userone@ml.com / QAtest123
Test Reports (1)
Applet password: Asd123!!!
![image.png](https://images.zenhubusercontent.com/6316e4697ddec12592e31aaa/421cf380-4004-47bc-a508-07e0000dbdd2)

**Comment by yzenchanka** [comment]
Verified as fixed. The applet watermark is showing at the top of every page of the report, the applet image isn't showed up at all
**Environment:**
https://admin-staging.mindlogger.org
Mobile app version 0.21.59
Staging account:
userone@ml.com / QAtest123
Test Reports (1)
Applet password: Asd123!!!
![image.png](https://images.zenhubusercontent.com/6316e4697ddec12592e31aaa/421cf380-4004-47bc-a508-07e0000dbdd2)

**Comment by natalia-muzyka** [comment]
The applet image in the report is replaced with the watermark image.
**Issue:** it is not shown on every page, but it is associated with every first page of the next activity report (as it was in the original implementation with the applet image). 

@hotavocado @e-kass could anyone clarify, please, do we need to fix this placement now and add the watermark to every page (including the first report page and splash image), **or** the original placement (associated with only the beginning of the activity report) is enough now? If we need to fix it before refactoring, @hotavocado could you, please, advise on the design? I think I can't find related mockups, could you help me, please? I use this design: https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=112%3A2248 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cd1bf27f-aefc-40bc-8857-063dbe10e66b)

cc: @eleonova-scn @Damirkhon @yzenchanka

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 106
new_user@ml.com / 123456
applet: Applet
activities: Test A, Config report
flow: Combined
Applet password: Qwe123!!!

**Comment by hotavocado** [comment]
hi @natalia-muzyka, i'm suggesting that watermarks should show up on every page except the summary page and splash screen, ive updated the figma file: https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=1873%3A36730

For the specs:
1. uploaded watermark image is resized to a fixed 64px height, width will resize proportionally
2. this image go inside container with 32px padding on all sides
3. position of container is fixed at top right

currently awaiting confirmation from Bennett and Lindsay

**Update**: confirmed, we'll want watermarks to show up on each page of the report, excluding the summary screen and splash

**Comment by natalia-muzyka** [comment]
@hotavocado thank you!
@Damirkhon could you implement the requirements according to Mike's comment above, please? 

> watermarks should show up on every page except the summary page and splash screen, ive updated the figma file: https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=1873%3A36730

> 1. uploaded watermark image is resized to a fixed 64px height, width will resize proportionally
> 2. this image go inside container with 32px padding on all sides
> 3. position of container is fixed at top right

cc: @eleonova-scn @yzenchanka

**Comment by Damirkhon** [comment]
@natalia-muzyka yes, sure

**Comment by yzenchanka** [comment]
Verified as fixed. 
The applet watermark is shouw up on every page except the summary page and splash screen
Environment:
https://admin-staging.mindlogger.org
Mobile app version 0.21.59
Staging account:
userone@ml.com / QAtest123
Test Reports (1)
Applet password: Asd123!!!

**Comment by natalia-muzyka** [comment]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2ae7beaf-f500-4f2a-af3c-8ce8b8203479)

Verified as fixed
Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 106
new_user@ml.com / 123456
applet: Applet
activities: Test A, Config report
flow: Combined
Applet password: Qwe123!!!
