### ISSUE TITLE
There is a [Nickname] variable instead of the user's nickname in the report after completing activity on mobile app/website

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1780]
**Preconditions**
Mobile app is installed and launched.
User is logged in:
test-user2@com.us / 123456
There is the activity with the configured report (My applet 4/ Test A). 
The [Nickname] variable is added to the markdown field in the report.

**Steps to reproduce**

1. Complete the activity on mobile app or website.
2. Download the admin report on the user's DataViz.
3. Pay attention to the nickname.

**Actual result**
There is a [Nickname] variable instead of the user's nickname in the report

**Expected result**
There is user's nickname  instead of the [Nickname] variable in the report

**Notes: Reproducible in the main body report text and in the printed items (text creator)**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d6bfb77f-39e9-46a2-9b3c-4796e386da8b)

**Environment:**
https://admin.mindlogger.org/
https://admin-staging.mindlogger.org/
prod account:
test-user1@com.us qwerty
my applet 4 / test A
Applet password Qwe123!!!

**Comment by karser** [comment]
Can't find "my applet 4" under test-user1@com.us on prod
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/dd311b66-7f2c-439e-a4e8-63ace4186c0b)

**Comment by natalia-muzyka** [comment]
@karser on your screenshot you are logged in to the user's account test-user2@com.us / 123456

owner's account is test-user1@com.us qwerty
Video: https://www.screencast.com/t/5sqNq0fsno

**Comment by karser** [comment]
for participants it uses nickName:
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/89ce927a-b33b-4e9f-8b8f-e50a8dc85a4c)

for managers it uses firstName + lastName:
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/3ef405ab-ae0c-4b61-b40a-2d495f4db50e)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1620b254-a396-410c-89f9-260140239973)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
ML v0.21.49
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
