### ISSUE TITLE
The message won't be shown/items won't be printed/score won't be flagged if Average/Percentage score condition IS EQUAL TO/IS NOT EQUAL TO is met

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1781]
**Preconditions**
User is logged in on admin:
test-user2@com.us / 123456
There is the activity with a configured report that contains: 
1-score ID with average calculation type 
2-score condition ID with IS EQUAL TO rule
3-according to condition there should be printed messages or items

**Steps to reproduce**

1. Complete the activity My applet 4 / Test B on mobile app or website so the IS EQUAL TO/IS NOT EQUAL TO condition is met.
2. Download the admin report on the user's DataViz or open the email report.
3. Pay attention to the printed messages and items according to the score conditional logic.
4. Complete the activity My applet 4 / Test C on mobile app or website so the IS EQUAL TO/IS NOT EQUAL TO condition is met.
5. Repeat steps 2-3
6. Observe the result

**Actual result**
The message won't be shown/items won't be printed if Average/Percentage score condition IS EQUAL TO/IS NOT EQUAL TO is met.

**Expected result**
The message is shown/items are printed if the Average/Percentage score condition IS EQUAL TO/IS NOT EQUAL TO is met.

**Notes**: Not reproduced with Between, Outside of, Greater than, Less than. Possibly the issue is caused by using decimals for Average and Percentage calculations.

**Video**: https://www.screencast.com/t/DbY4xdeHi

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8787710a-5a14-4284-8b91-e9ce7b3a598a)

**Environment:**
https://admin.mindlogger.org/
https://admin-staging.mindlogger.org/
https://web.mindlogger.org/
https://web-staging.mindlogger.org/
prod account:
test-user1@com.us qwerty
my applet 4 / test B, test C
Applet password: Qwe123!!!

**Comment by e-kass** [comment]
Percentage score not being used in ped screener. Otherwise seems like High Priority

**Comment by natalia-muzyka** [comment]
@iradchenk0 
Percentage Score ID is not highlighted with red on mobile app side if the condition IS EQUAL/IS NOT EQUAL was met (when value is 0 or 100):

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/927e8573-d2b1-4ace-b001-180d23dd21d5)

Environment:
ML v0.21.52
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
Win 10 / Chrome 105
user-stg@ml.com / 123456
Conditional in report retest / Test C
Applet password:	Qwe123!!!

**Comment by iradchenk0** [comment]
@natalia-muzyka @anq83 
Seems like all conditions awe working correctly on web and report server side, the only place where it's reproduced is the mobile app
![2022-09-26_19-12.png](https://images.zenhubusercontent.com/631f33964819d323745f21b6/39c2c24f-f9ef-4a06-b77f-1e820348e25f)

**Comment by anq83** [comment]
@natalia-muzyka Please reopen this one or add a new ticket

**Comment by natalia-muzyka** [comment]
@anq83 suggest continuing with this ticket

**Comment by natalia-muzyka** [comment]
@anq83 
Video of the issue for PERCENTAGE calculation + IS EQUAL TO condition: https://www.screencast.com/t/MrOm2s9odhy6

Video of correct behavior for PERCENTAGE calculation + BETWEEN condition: 
https://www.screencast.com/t/TBxWNuLF

Environment:
ML v0.21.57 staging
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
https://admin-staging.mindlogger.org/
test_account2@ml.com / 123456
applet/activity: conditional in report retest / Test C

**Comment by anq83** [comment]
done, check fix in the next version of mobile app

**Comment by yzenchanka** [comment]
The issue is fixed
Video for 
AVERAGE calculation + IS EQUAL TO https://app.screencast.com/IZCxVkKnQwWgg
PERCENTAFE calculation + IS NOT EQUAL TO https://app.screencast.com/yuaugNMrUjY3c
Environment:
ML v0.21.62 staging
iPhone 7 Plus // iOS 14.4
https://admin-staging.mindlogger.org/
userone@ml.com / QAtest123
applet/activity: Test reports(1)/ Activity B and Activity C

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
ML v0.21.62 staging
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
https://admin-staging.mindlogger.org/
test_account2@ml.com / 123456
applet/activity: conditional in report retest / Test C
