### ISSUE TITLE
Group schedule is not created after uploading and submitting it on the Group Calendar page

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1785]
**Preconditions**
The user is logged in on the admin panel

**Steps to reproduce**

1. Open a site https://admin.mindlogger.org/
2. Click the "View Users" tab on any applet with at least two users (Schedule CSV)
3. Select two users and click the "Calendar" button above
4. Click the "Import schedule" button, and click "Yes"
5. Upload valid CSV schedule similar to the template
6. Submit the table
7. Pay attention to the calendar

**Actual result:**
Group schedule is not created after uploading and submitting it on the Group Calendar page

**Expected result:**
Group schedule is created/replace the previous one after uploading and submitting it on the Group Calendar page

**Notes: There is a workaround: Group scheduling is available only with a General Calendar. To create a group you need to add all the users in one Secret UID cell and separate them with comma and space character ", "**

**Video**: https://www.screencast.com/t/zQlYuzEJ25Or

**CSV schedule file:**
https://drive.google.com/file/d/1DD2mpVle-asotLBXxp_j6LHRonYToXb4/view?usp=sharing

**Environment:**
https://admin.mindlogger.org/
Win 10 / Chrome 103
test-user1@com.us / qwerty
Schedule CSV
https://admin-staging.mindlogger.org/
jeligi9407@zneep.com / 123456
applets:
vbn123
Applet password: Qwe123!!!

**Comment by e-kass** [comment]
Ped Screener doesn't use calendar/scheduling

**Comment by eleonova-scn** [comment]
@natalia-muzyka , could you please add the file you uploaded in the video to the task?
Thanks.

**Comment by natalia-muzyka** [comment]
@eleonova-scn updated a ticket

**Comment by yzenchanka** [comment]
Verified as fixed:
Video: https://screencast-o-matic.com/watch/c3Qrj2VOkqU
Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 105.0.5195.127
