### ISSUE TITLE
Group calendar should show only group events for a selected group

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1788]
Actual:
After uploading group and individual events in the general calendar and selecting group users there are all the individual users' events in addition to group events.

Expected:
Only group events are displayed in the group calendar. 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/33d5c3b8-6f02-4a44-b73b-70c68bd65723)

**Comment by e-kass** [comment]
Not used in Ped Screener

**Comment by natalia-muzyka** [comment]
Verified as fixed: 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ee7aa3bd-0891-4b48-92b5-592762f8fc7b)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 105.0.5195.127
