### ISSUE TITLE
Users invited to be a manager/coordinator/reviewer/editor are shown as a regular user on the email invite

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#187]
**Steps to reproduce:**
1. Log in to the admin panel https://admin.mindlogger.org/
2. Invite users to be a manager /coordinator/reviewer/editor
3. Check the mailbox for invited users
4. Pay attention to the result

**Actual result:** Users invited to be a manager/coordinator/reviewer/editor are shown as a regular user on the email invite
![2020-05-27_15-41-46.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/193048e3-957a-4c22-ada9-60848abdfb85)
**Expected result:**  Users invited to be a manager/coordinator/reviewer/editor should be invited accoding to their roles on the email invite
**Environment:** 
Dev server
Win 10 // Chrome 81

**Comment by WorldImpex** [comment]
187 needs to be fixed and then for 193 we can show the manager, coordinator, etc email address just not the User's

There is also the sentence at the top on the image that needs to be removed that @Sergey Semenuta has pointed a requirements arrow at

**Comment by WorldImpex** [comment]
![invitation_for_an_applet_wavanauken_gmail_com_Gmail.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/03925981-8e29-4adc-99b6-670a2d965867)

fixed
