### ISSUE TITLE
Unsupported Calendar + Outdated Vuetify

### ISSUE THREAD

**Issue by henryrossiter** [ChildMindInstitute/mindlogger-admin-OLD-Vue#19]
Project is currently using Vuetify 1.3.9. Vuetify 2 was released months ago and 2.1.3 is available as of October 2019. The dayspan-vuetify calendar library doesn't support Vuetify 2. We should eventually find a new calendar component so we can update Vuetify.

**Comment by shnizzedy** [comment]
Yesterday I set up an applet on the production server (`5ddbf366886fcbb593e06407`) using the protocol https://raw.githubusercontent.com/ChildMindInstitute/reproschema/master/protocols/ema-hbn/ema-hbn-self_schema and forgot to set a schedule on it. Since I got notifications for both activities at midnight this morning, I guess that's the default? I know we have this issue open to replace the calendar component because it is outdated, but we should also consider usability in prioritizing this issue and choosing / building a replacement.

I set a daily schedule on each of the two activities in this applet, but only one appears in the monthly view. Both are visible at weekly and daily.
![monthly calendar](https://user-images.githubusercontent.com/5974438/69653101-aa56fb80-1040-11ea-96d4-b0eaf8670c93.png)
![weekly calendar](https://user-images.githubusercontent.com/5974438/69653265-eab67980-1040-11ea-98a9-fccfae6bb993.png)

**Comment by shnizzedy** [comment]
Looking into the notification weirdness more, I'm more convinced that this issue (#19) is the main problem. Even though the admin panel calendar is showing a morning and evening schedule, the data is an array of the evening activity once and the morning activity three times, all at 8. I'm going to manually update this now, but that's just going to fix it for this one applet.

#### Before
```json
{
	"schedule": {
		"type": 0,
		"size": 1,
		"fill": false,
		"minimumSize": 0,
		"repeatCovers": true,
		"listTimes": true,
		"eventsOutside": true,
		"updateRows": true,
		"updateColumns": true,
		"around": "1573534800000",
		"events": [{
			"data": {
				"title": "Evening",
				"description": "",
				"location": "",
				"color": "#FF9800",
				"forecolor": "#ffffff",
				"calendar": "",
				"busy": true,
				"icon": "",
				"URI": "https://raw.githubusercontent.com/ChildMindInstitute/reproschema/master/activities/EmaHBNEvening-self/ema_evening_schema",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "08:00"
				}],
				"useNotifications": true
			},
			"schedule": {
				"times": ["19"],
				"duration": 5,
				"durationUnit": "minutes"
			}
		}, {
			"data": {
				"title": "Morning",
				"description": "",
				"location": "",
				"color": "#673AB7",
				"forecolor": "#ffffff",
				"calendar": "",
				"busy": true,
				"icon": "",
				"URI": "https://raw.githubusercontent.com/ChildMindInstitute/reproschema/master/activities/EmaHBNMorning-self/ema_morning_schema",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "08:00"
				}],
				"useNotifications": true
			},
			"schedule": {
				"times": ["07"],
				"duration": 5,
				"durationUnit": "minutes"
			}
		}, {
			"data": {
				"title": "Morning",
				"description": "",
				"location": "",
				"color": "#673AB7",
				"forecolor": "#ffffff",
				"calendar": "",
				"busy": true,
				"icon": "",
				"URI": "https://raw.githubusercontent.com/ChildMindInstitute/reproschema/master/activities/EmaHBNMorning-self/ema_morning_schema",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "08:00"
				}],
				"useNotifications": true
			},
			"schedule": {
				"times": ["07"],
				"duration": 5,
				"durationUnit": "minutes"
			}
		}, {
			"data": {
				"title": "Morning",
				"description": "",
				"location": "",
				"color": "#673AB7",
				"forecolor": "#ffffff",
				"calendar": "",
				"busy": true,
				"icon": "",
				"URI": "https://raw.githubusercontent.com/ChildMindInstitute/reproschema/master/activities/EmaHBNMorning-self/ema_morning_schema",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "08:00"
				}],
				"useNotifications": true
			},
			"schedule": {
				"times": ["07"],
				"duration": 5,
				"durationUnit": "minutes"
			}
		}]
	}
}
```

#### After
```json
{
	"schedule": {
		"type": 0,
		"size": 1,
		"fill": false,
		"minimumSize": 0,
		"repeatCovers": true,
		"listTimes": true,
		"eventsOutside": true,
		"updateRows": true,
		"updateColumns": true,
		"around": "1573534800000",
		"events": [{
			"data": {
				"title": "Evening",
				"description": "",
				"location": "",
				"color": "#FF9800",
				"forecolor": "#ffffff",
				"calendar": "",
				"busy": true,
				"icon": "",
				"URI": "https://raw.githubusercontent.com/ChildMindInstitute/reproschema/master/activities/EmaHBNEvening-self/ema_evening_schema",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "20:00"
				}],
				"useNotifications": true
			},
			"schedule": {
				"times": ["19"],
				"duration": 5,
				"durationUnit": "minutes"
			}
		}, {
			"data": {
				"title": "Morning",
				"description": "",
				"location": "",
				"color": "#673AB7",
				"forecolor": "#ffffff",
				"calendar": "",
				"busy": true,
				"icon": "",
				"URI": "https://raw.githubusercontent.com/ChildMindInstitute/reproschema/master/activities/EmaHBNMorning-self/ema_morning_schema",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "08:00"
				}],
				"useNotifications": true
			},
			"schedule": {
				"times": ["07"],
				"duration": 5,
				"durationUnit": "minutes"
			}
		}]
	}
}
```

**Comment by shnizzedy** [comment]
https://github.com/ChildMindInstitute/mindlogger-admin/issues/19#issuecomment-561861370 seems to have done the trick for notifications. See this morning / yesterday evening vs. Tuesday morning on my lock screen for illustration

![Notifications as expected after not as expected](https://user-images.githubusercontent.com/5974438/70244287-1c66c900-1742-11ea-94ed-8ee8e44eade9.png)

**Comment by henryrossiter** [comment]
I recently found this: https://github.com/ahmadissa/dayspan-vuetify-2

It appears to be an updated version of ```dayspan-vuetify```, the dayspan calendar we are currently using. I haven't tested it yet but it could very well be the update we've been looking for!

**Comment by Eden2016** [comment]
@henryrossiter I've tried to migrate the app to vuetify 2.1.0 and use dayspan-vuetify-2 to upgrade the calendar and everything seemed ok until I tried to delete created event, I could not invoke an actions list where the delete event button located, something wrong with the component that is responsible for this list.

**Comment by henryrossiter** [comment]
@Eden2016 Okay great, I was working on this as well. I need to update the ```activity-set-builder``` component today and then I'll modify and modify and merge the code you wrote on the ```calendar-update-#19```
