### ISSUE TITLE
The auto logout after reloading the page on the Admin panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#192]
Steps to reproduce:
1. Open the site https://admin-dev.mindlogger.org/
2. Log in to the site
3. Reload the page
4. Pay attention to the result

Actual result:The auto logout after reloading the page on the Admin panel
Video: https://www.dropbox.com/s/0m2614mr87jpg0k/2020-05-28_16-14-28.MP4?dl=0
Expected result: After reloading the page the user should be logged in on the admin panel

Environment:
https://admin-dev.mindlogger.org/
Win 10 /Chrome 81

**Comment by sergeysemenuta** [comment]
The  issue is fixed.
Checked on the site https://admin-dev.mindlogger.org/
Environment:
Win 10 // Chrome Version 83.0.4103.97

**Comment by sergeysemenuta** [comment]
Reopening the issue. It reproduces again on the staging environment
https://www.screencast.com/t/KIi8wuTwIVM
Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome Version 85

**Comment by WorldImpex** [comment]
This happened with the deployment from today @devbtech

**Comment by sergeysemenuta** [comment]
This issue is not reproduced anymore on the site https://admin-staging.mindlogger.org/
https://www.screencast.com/t/cf0koyyh

Closing the issue
