### ISSUE TITLE
The encrypted information is displayed on the email invite

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#193]
Steps to repro:
1. Log in to the admin panel https://admin-dev.mindlogger.org/
2. Invite any user (user B) to an applet 
4. Open the  email invite as a user B
5. Look at the screen

Actual result: The encrypted information is displayed on the email invite
![2020-05-28_17-33-33.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/bb98eedc-8a65-41fd-8930-844cb50db4fc)
Expected result: Any role that is not user, does not need to be encrypted on the emai invite according to Requirements

Environment:
Dev server
Win 10 //Chrome//Fifefox

**Comment by WorldImpex** [comment]
![Screen Shot 2020-06-02 at 7.11.47 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/24b3181a-ceeb-4637-9144-4d564a883022)

Expected behavior
