### ISSUE TITLE
The "Save Unsuccessful. Error: Request failed with status code 500'' is shown after saving events on the Admin panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#194]
Steps to reproduce:
1. Log in to the site https://admin-dev.mindlogger.org/ (qatestqass@gmail.com // 123456)
2. Select the NIMH applet
3. Navigate to the calendar
4. Set up scheduling  for  any events and click "Save" button
5. Look at the page

Actual result: The "Save Unsuccessful. Error: Request failed with status code 500'' is shown after saving events on the Admin panel
Video: https://www.dropbox.com/s/y5zsi7vi5cgnvng/2020-05-29_16-33-24.MP4?dl=0
Expected result: The "Save Unsuccessful. Error: Request failed with status code 500'' is not shown after saving events on the Admin panel

Environment:
Dev server
Win 10 // Chrome 81

**Comment by WorldImpex** [comment]
@sergeysemenuta Please provide your login for this

**Comment by sergeysemenuta** [comment]
@WorldImpex  Added the log in credentials (qatestqass@gmail.com // 123456)

**Comment by WorldImpex** [comment]
@sergeysemenuta - @devbtech cannot reproduce this yesterday or today

**Comment by sergeysemenuta** [comment]
@devbtech @WorldImpex 
I reproduced this issue again
Video: https://www.dropbox.com/s/kg68rbrtt8ka4m1/2020-06-02_19-04-36.MP4?dl=0
Steps to reproduce:
1. Log in to the site https://admin-dev.mindlogger.org/ (qatestqass@gmail.com // 123456)
2. Select the NIMH applet
3. Navigate to the calendar
4. Select events and save them separately for the next days
6. Pay attention to the result

Note: The same issue occurs when removing events and saving the scheduling

Win 10 // Chrome Version 83.0.4103.61

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on the site https://admin-dev.mindlogger.org/
Video: https://www.dropbox.com/s/ujuogymn1oy71dh/2020-06-05_12-04-19.MP4?dl=0
Environment:
Win 10 // Chrome Version 83.0.4103.97
