### ISSUE TITLE
FE  - Allow User to complete Past Due Activity

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#197]

**Comment by sergeysemenuta** [comment]
Works as expected.
Checked on the staging environment.
https://admin-staging.mindlogger.org/
Win 10 // Chrome Version 85.0.4183.83
MindLogger app v 0.13.17
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

Closing the ticket
