### ISSUE TITLE
The events are not deleted from the calendar on the admin panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#201]
**Preconditions:**
The user has scheduled events on the calendar
**Steps to reproduce:**
1. Log in to the site https://admin-dev.mindlogger.org/  ( snakessqa@gmail.com // 123456 )
2. Navigate to the calendar
3. Remove one or all events from the calendar
4 . Click the "SAVE" button at the bottom right corner
5. Log out from the site
6. Log in again
7. Pay attention to the calendar from step 2

**Actual result:** The events are not deleted from the calendar on the admin panel
**Video:** https://www.dropbox.com/s/1j5e6y6w6pmjlnz/2020-06-05_19-18-56.MP4?dl=0
**Expected result:** The events are not shown on the calendar after removing and saving the schedule on the admin panel

**Environment:**
Win 10 // Chrome 83

**Comment by WorldImpex** [comment]
events are now duplicated per #1026

**Comment by WorldImpex** [comment]
Events are not duplicated any longer but they are not deleted

**Comment by WorldImpex** [comment]
events are deleted and updated on device when deleted
