### ISSUE TITLE
TokenLogger Visualization Dashboard - Web

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#207]
@WorldImpex commented on [Tue Apr 28 2020](https://github.com/ChildMindInstitute/mindlogger-web-vue/issues/66)

We need to display the data to a reviewer on the web for TokenLogger.  There has already been some development work in the past with [#61]([https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-bug-reports/61)). We hopefully can reuse this dashboard and enhance it to what we need: 

Requirements 
1. Data visualization should be filterable: 
   1st: User or users 
   2nd: Applet
   3rd: Activity 
2. Filter results by date range 
3. Downloadable (PDF) 
4. See each item results within an activity 
5. Fix Data export to pull data from an entire applet group of users 
6. Add timestamp and date to each item submission for each activity 

![MindLogger_Dashboard_Design_June_17_Google_Slides.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/148a2d4f-e38f-4844-b61e-916a3fedec63)

Current Data Export: [Click here](https://docs.google.com/document/d/1k2u56OxP9XeFJlLMMm1qjoi1QRokZsI51oihq3Emsqk/edit?usp=sharing)

Here is an example of what we are trying to display to the reviewer 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/087af0eb-182b-4dce-b95b-f7e81b6395cb)

Additional conversation: https://matter-lab.slack.com/archives/CEHC2AVTJ/p1587703557003400

**Comment by sergeysemenuta** [comment]
Checked the visualization dashboard for the TokenLogger applet on the  https://admin-staging.mindlogger.org/ (win 10//Chrome 85)
It shows the data with the correct result but the data export doesn't work.
See the video: https://www.screencast.com/t/4kTaeCVEUh7

**Comment by sergeysemenuta** [comment]
- The wrong data is displayed in the tokenLogger chart
After completing the  assessment with all items selected the 14 points are shown  on the chart
Expected result: After completing the  assessment with all items selected the 15 points should be shown  on the chart
See screenshot: https://www.screencast.com/t/x3nIVP0gj

- The decimal numbers are displayed in the TokenLogger chart on the dashboard
Expected result: Only integers should be displayed in the TokenLogger chart
https://www.screencast.com/t/UscC3ceDLscn
https://www.screencast.com/t/3W7jxDEerf

Test accounts: ruby@st.com // 123456 (owner)
https://admin-staging.mindlogger.org/

Win10 //Chrome 85// Firefox 80

**Comment by sergeysemenuta** [comment]
Issues found:
1. The negative values are show up on the TokenLogger dashboard.
![2020-09-16_10-51-08.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6ee99d5f-9a06-41b8-afb2-2a078906b1eb)
2. The progress bar is not displayed for the current day in the chart.
![barmissing.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5a2058f1-e274-4979-8124-57816d6e197b)
3. Values are duplicated on the table
![duplicated.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/aec61991-77f3-4a7a-986a-b90d416a8927)
Video: https://www.screencast.com/t/Ij95Lo5KK6R7

Environment:
https://admin-staging.mindlogger.org/
Win10//Chrome 85

cc: @WorldImpex @ngonzalvez

**Comment by sergeysemenuta** [comment]
@ngonzalvez 

 The labels are duplicated in the table if the user selects the following items separately:

- Cleaned up room (+1)

- Brushed teeth (+2)
**Video:** https://www.screencast.com/t/AcYiFzKEiv0
**To reproduce:**
1. Log in to the app an navigate to the token screen
2. Select the "Cleaned up room (+1)" item
3. Tap the "Done button"
4. Check the result on the TokenLoger dashboard on the Admin panel
**Actual result:**
![2020-09-29_14-12-00.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/a25c1122-1c59-4bfd-942b-7c61311c39f6)
**To reproduce:**

1. Log in to the app an navigate to the token screen
2. Select the "Brushed teeth (+2)" item
3. Tap the "Done button"
4. Check the result on the TokenLoger dashboard on the Admin panel
**Actual result:**
![2020-09-29_14-15-17.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/d3e3d482-d3d4-47fd-9bf2-48aac0b6641f)


- The chart bar is not displayed for the current day

![2020-09-29_14-19-32.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/d6f065f7-54e1-4b7d-a4b6-66d2967ce989)


**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85

cc: @WorldImpex

**Comment by sergeysemenuta** [comment]
There is no distance between numbers in the TokenLogger chart. This is reproducible for users who have a long activity history with maximum tokens on the dashboard
![2020-09-30_14-05-35.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5e5d7701-962a-4225-b413-67ac1aa77a8e)

**Comment by WorldImpex** [comment]
Looks to be all fixed. We need #413 & #887 to test accumulation of tokens but the graph seems to size well with the limited amount of tokens we can record

**Comment by sergeysemenuta** [comment]
Blocked by [389](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/389)
cc: @WorldImpex

**Comment by sergeysemenuta** [comment]
- Values are duplicated on the table- **fixed**

- The chart bar is not displayed for the current day - **Fixed**

-There is no distance between numbers in the TokenLogger chart. - **Fixed**

![2020-10-13_13-12-05.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/522c80ac-b988-4d9b-9f47-08d99facb1a7)

Checked on:
https://admin-staging.mindlogger.org/
Win 10 //Chrome 85

**Comment by sergeysemenuta** [comment]
The chart bar is displayed next to the last day  in the chart 
![2020-10-13_18-03-05.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/535d503a-7a43-4fb1-a6d3-f4cfea8fa735)
Expected result: The chart bar should display directly over the current date in the chart 

Checked on:
https://admin-staging.mindlogger.org/
Win 10 //Chrome 85

**Comment by WorldImpex** [comment]
Fixed 

![Screen Shot 2020-10-28 at 6.36.09 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/03c44d77-78ae-495c-8bfa-001d22eae50d)
