### ISSUE TITLE
FE-Gate what different types of roles see on admin 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#210]
These below roles will have access to specific applets depending on how he or she was invited to the applet. Each role will be a different experience due to the permission level 

Owner - Needs a transfer ownership option
Manager
Coordinator  
Editor
Reviewer

**Comment by sergeysemenuta** [comment]
All permissions work as expected regarding the applet permissions - https://docs.google.com/spreadsheets/d/1ZmrEy9dTlrM400Uw4SS89n8Q8LoqB3pIejNfq0XojAY/edit#gid=0
The only case that has not been implemented yet - The owner is not able to  transfer ownership to another user 

Closing the ticket
