### ISSUE TITLE
The events from the individual scheduling are reflected on the general scheduling on the Admin Panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#214]
**Preconditions:**
There aren't any event scheduled on the general calendar
Steps to reproduce:
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakess@gmail.com // 123456)
2. Open the "users" page
3. Select any user from the "Active Users" section and apply individual cheduling
4. Go to the "Applets" page
5. Click the "Select" button and shoose the "View General Calendar" option
6. Look at the page

**Actual result:** The events from the individual scheduling are reflected on general scheduling on the Admin Panel
Video: https://www.dropbox.com/s/d8z0po7ldzx8z1m/2020-06-26_12-36-32.MP4?dl=0
**Expected result:** The events from the individual scheduling are not reflected on the general scheduling on the Admin Panel. 

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // chrome 83

**Comment by sergeysemenuta** [comment]
The events from the individual scheduling are reflected on the general scheduling on the Admin Panel after clicking the current day, even more, all events from general and individual scheduling are shown 
**Video:** https://www.dropbox.com/s/t1zxk437joqx5k6/2020-07-03_16-24-39.MP4?dl=0
CC: @ProNinoGit120 @WorldImpex

**Comment by WorldImpex** [comment]
Fixed on chrome

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on :
https://admin-staging.mindlogger.org/
Wim 10 // Chrome 83
