### ISSUE TITLE
Newly Uploaded Applet not Shown with refreshing the screen

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#216]
Steps: 
1. Create a new account on https://admin-staging.mindlogger.org/#/applets
2. Add EMA applet to new account (https://raw.githubusercontent.com/ChildMindInstitute/NIMH_EMA_applet/master/protocols/EMA_HBN_NIMH2/EMA_HBN_NIMH2_schema?token=AL6IBQHVGIQQRGZL3UDCX6C66CWCC) 
3. Wait 10 mins 
4. Refresh page 
5. See Results

Expected: Applet is shown on dashboard 
Actual: Applet is not shown on dashboard but user can navigate to 'account tab" and when selected the applet is now displayed 

Below is what I mean by account tab 
![mindlogger-admin.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e567f927-fa70-4a7b-8666-0fde1fdcab5b)

**Comment by sergeysemenuta** [comment]
The issue is reproduced.
Newly uploaded applet is not shown with refreshing the screen. after refreshing applets or reloading the page some applets are disappeared
Video: https://www.dropbox.com/s/4ah8wsth1pc3nwm/2020-07-01_15-57-48.MP4?dl=0
Rechecked on https://admin-staging.mindlogger.org/
win10 // Chrome 83
Test account: norman@ml.com // 123456

**Comment by sergeysemenuta** [comment]
I have recreated the issue again.
Newly uploaded applet is not shown with refreshing the page.
Steps:
1. Create a new account on https://admin-staging.mindlogger.org/#/applets
2. Add EMA applet to new account (https://raw.githubusercontent.com/ChildMindInstitute/NIMH_EMA_applet/master/protocols/EMA_HBN_NIMH2/EMA_HBN_NIMH2_schema?token=AL6IBQHVGIQQRGZL3UDCX6C66CWCC)
3. Wait 10 mins
4. Refresh page
5. See Results
Expected: Applet is shown on dashboard
Actual: Applet is not shown on dashboard but user can navigate to 'account tab" and when selected the applet is now displayed
**Video:** https://www.dropbox.com/s/c8udg5m9izly2o9/2020-07-03_17-08-35.MP4?dl=0

Win 10 //Chrome 83

**Comment by sergeysemenuta** [comment]
The issue is fixed.

- Newly uploaded applet is shown with refreshing the page.

https://www.dropbox.com/s/86ayjz0qp7vz23a/2020-07-09_18-36-48.MP4?dl=0
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 83
