### ISSUE TITLE
The applet is not deleted from the admin panel after clicking the "DELETE" button

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#220]
**Precontidions:**
There are several applets on the admin panel
**Steps to reproduce:**
1. Log in to the site https://admin-staging.mindlogger.org/ (e.g. norman@ml.com // 123456)
2. Click the "DELETE" button
3. Look at the page

**Actual result:** The applet is not deleted from the admin panel after clicking the "DELETE" button. The 403 error is occured
**Video:** https://www.dropbox.com/s/oya8yobt8xk6prt/2020-06-30_19-31-00.MP4?dl=0
**Expected result:** The applet is removed from the admin panel and from the app after clicking the "DELETE" button without errors

**Environment:**
Staging server
Win 10 //Chrome 83
MindLogger app v 0.11.45
Google Pixel 3a XL// Android 10
iPhone 6 //12.4.1
iPhone 8 // 12.3.1

**Comment by WorldImpex** [comment]
Applet is deleted on chrome

**Comment by sergeysemenuta** [comment]
The applet is deleted.
https://www.dropbox.com/s/or4t0o6ox1o1yky/2020-07-10_10-40-30.MP4?dl=0
Checked on Win 10 // Chrome 83
