### ISSUE TITLE
The individual scheduling is broken

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#221]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ as user C (e.g. norman@ml.com // 123456)
2. Do not set up general scheduling 
3. Set up individual scheduling for User A (e.g. fiona@ml.com // 123456)
4. Set up individual schedulind for user B (e.g loura@ml.com // 123456)
5. Log in to the app as user A/user B/user C
6. Observe the scheduled events on admin panel and device for user A
7. Observe the scheduled events on admin panel and device for user B
8. Pay attention to the result
9. Observe the general calendar on adnin panel and compare with User C device
10. Pay attention to the result

**Actual result:** The individual scheduling is broken. The events from individual scheduling for user A are displayed on general calendar. The individual scheduling for user B is not applied on the app.  The user b have events that were scheduled for user A on the app
![scheduling.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3c0b7de9-7e23-426f-a0a4-b93662088c45)
**Expected result:** The events for individual scheduling are not displayed on the General calendar. All individual scheduling should be applied for paticular user on the app and on the admin panel.
**Note:** After setting up individual scheduling for 1 user then the events are not displayed on the general calendar
**Environment:** 
https://admin-staging.mindlogger.org/
MindLogger app v 0.11.45
**Devices:**
iPhone 6 //12.4.1
iPhone XR // iOS 13.2.3
Google Pixel 3a XL// Android 10

**Comment by WorldImpex** [comment]
@sergeysemenuta I think it might be due to an old account. I created manager13@ml.com/ abcd123 with a general schedule and I see general schedule on the device. I created user13@ml.com with individual schedule  and I see the correct schedule on the device. I do see that more then 1 individual schedule causes those users to have the same schedule

I created #1058 for what I found

**Comment by sergeysemenuta** [comment]
Closing this issue . Some issues from this ticket are described under: [#214](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/214) , [#1058](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1058)
