### ISSUE TITLE
The username of the owner of the applet is replaced by the AccountName who were invited to be a reviewer of the applet after creating invitations on the account menu

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#223]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ as an existing user
2. Upload an applet NIMH
4. Invite several users with different roles to the applet (do not accept invitations)
5. Reload the page several times
6. Open the account menu
7. Observe the menu

**Actual result:** The username of the owner of the applet is replaced by the AccountName who were invited to be a reviewer of the applet after creating invitations on the account menu
![replacednames.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3e7f0690-1561-4eee-951a-7de678a82460)
**Expected result:** The username of the owner of the applet is not replaced by the account Name who were invited to be a reviewer of the applet after creating invitations on the account menu

**Environment:**
Staging server
Test account: star@ml.com // 123456
Win 10 // Chrome 83

**Comment by WorldImpex** [comment]
@sergeysemenuta I created ml12@ml.com/ abcd123 and invited multiple users but I could not recreate this. Could you provide more information?

**Comment by sergeysemenuta** [comment]
The issue is reproducible for me.
Video: https://www.dropbox.com/s/gegld773qr6i3vm/2020-07-03_16-28-53.MP4?dl=0
Steps to reproduce:
1. Log in to the admin panel https://admin-staging.mindlogger.org/ as an existing user  (user A)
2. Upload an applet NIMH
4. Invite several users with different roles to the applet (do not accept invitations)
5. Log in as user B to the admin panel
6. Select any applet and invite the user A to be a manager of the applet
7. Accept the invitation as user B
8. As user A create invitation to be a reviewer of the applet 
9. Reload the page/ appet several times
10. Wait for some time
11. Observe the menu

**Note:** It’s hard to write the exact expected steps to reproduce

cc: @WorldImpex

**Comment by sergeysemenuta** [comment]
@ProNinoGit120    It is possible to set the accountName after each invite
https://www.dropbox.com/s/tiipq7dey5yspwl/2020-07-08_15-24-37.MP4?dl=0

**Comment by WorldImpex** [comment]
in #229

**Comment by WorldImpex** [comment]
Checked on chrome and works as expected 

Steps to recreate: 
1. Login to owner12@ml.com/abcd123
2. Create a new invitation for a manager role
3. Set the account name (CMI)
4. Accept invitation from that new role (manager12@ml.com/ abcd123)
5. Log into admin with coordinator login and see results 

Expected & Actual: Managersees CMI and own personal account 

An owner should only set the account name once so a follow up bug ticket was opened #1079

**Comment by sergeysemenuta** [comment]
Rechecked using the steps in the comment above.
Works as expected on https://admin-staging.mindlogger.org/

Win10 // Chrome 83
