### ISSUE TITLE
The 500 error occurs after saving scheduling with multiple random notification settings for the event

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#227]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (e.g. owen@ml.com // 123456)
2. Select the NIMH applet and navigate to the general calendar
3. Set up random notifications for the event (Pre-Questionnaire) 
4. Click the "+" button and setup ramdom notifications with different data
5. Repeat the step 4 several times
6. Save scheduling
7. Pay attention to the result

 **Actual result:** The 500 error occurs after saving scheduling with multiple random notification settings for the event
**Video:** https://www.dropbox.com/s/plsq68mf9pnfcdw/2020-07-07_14-52-43.MP4?dl=0

**Expected result:** The scheduling for the event is saved without any errors

**Environment:**
Staging server
Win 10 // Chrome 83

**Comment by natalia-muzyka** [comment]
Not reproducible anymore: https://www.screencast.com/t/Pe81q56JsO

https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
