### ISSUE TITLE
Applet User Data Export

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#231]
As an owner or manager, I want to export the user data from an applet so that I can review it outside of the MindLogger platform. 

Requirements
* Provide a way for the owner or manager to export every user's data collected by an applet via the user's detail page for an applet. 
* Provide a way for the owner or manager to export one user's data collected by an applet via the user's detail page for an applet. 
* Require the owner/manager to enter their password to be able to export the data
* Export in the form of CSV
* All historic response data from the user 

![ce4fc022_29b5_4eb3_9a69_9aba7d681795_2882×2985_.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c2247d2f-08d1-47a6-9894-76482fb34f63)

**Comment by sergeysemenuta** [comment]
Works as expected for the owner role in the staging environment.
Unable to check for the manager role for now. Raised the separate issue  [357](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/357)

**Comment by sergeysemenuta** [comment]
Raised a ticket [359](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/359) related to this task

**Comment by sergeysemenuta** [comment]
The export data functionality works as expected according to Requirements
The  owner, manager, and reviewer are able to export  user's data in the form of CSV
https://www.screencast.com/t/ZtxRKLgQlPjJ
Checked on:
https://admin-staging.mindlogger.org/
Win 10//Chrome 85

**Comment by sergeysemenuta** [comment]
- Unable to export user's data for NIMH, DBT, etc. applets
Test account: bughunterqa123@gmail.com // 123456
Applet password: Qwe123!!!
Nothing happens after entering the applet password when trying to export the data
**Video:** https://www.screencast.com/t/7N6Xx1crH
**Expected result:** The data should be exported to the csv file. It should be work for all applets
**Note**: Works as expected only for the TokenLogger applet

Reproduced on:
https://admin-staging.mindlogger.org
Win 10 Chrome 85//Firefox 80

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/dyafD9IxJ
Checked on:
https://admin-staging.mindlogger.org
Win 10 Chrome 85//Firefox 80
