### ISSUE TITLE
Email the editor applet upload status

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#246]
As an editor, I want to know if an applet was successfully uploaded so that I know it is ready for the coordinators. 

We need to inform users when a newly created applet is uploaded that it has failed via URL upload or from the applet builder

Requirements:
URL Upload 
1. Remove spaces from the user's URL entry automatically 
2. Change URL upload success text to "The applet is building. We will send you an email in 10 mins or less when it has been successfully created."
3. The email should be sent to the editor creating/ uploading the new applet. (This should apply to a manager and owner as well but an email is only sent to that user who initiated the creation/ upload)

Email
1. Users should receive a success email if the applet was successfully uploaded 
" Hey *First name*, 

Your applet was successfully uploaded! It is ready to have invitations sent out and schedule created."
2. Users should receive an unsuccessful email if the applet was not able to uploaded 
"Hi *First name*, 

Your applet, unfortunately, was not able to be uploaded. Please double check your applet and try again"

**Comment by sergeysemenuta** [comment]
Checked on the staging  environment https://admin-staging.mindlogger.org/


1. After creating an applet via applet builder  the email is not sent to the creator of the applet but it works  as expected if user uploaded an applet via the URL upload (Checked for the NIMH applet)
Video: https://www.screencast.com/t/kcElA2kWH
2. The URL upload success text  not chaged to "The applet is building. We will send you an email in 10 mins or less when it has been successfully created."
![2020-08-17_12-36-07.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/117efd91-ff0b-4367-8a2b-844efe01fc50)

Note: Users receive an unsuccessful email if the applet was not able to uploaded/. Checked this for the NIMH applet
![2020-08-17_12-24-41.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/d8b89e31-0ef1-480b-ae5f-a5ed55188d52)
CC: @WorldImpex

**Comment by sergeysemenuta** [comment]
Checked the Editor, Manager, and Owner roles. They are received correct emails after uploading or building the applet.
The 1st issue in the comment above is fixed. But the 2nd one still reproduces.

- The upload success text "The applet is building. We will send you an email in 10 mins or less when it has been successfully created." is not updated yet.
![2020-08-27_18-11-34.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e1e77707-64e9-4239-92c4-10f1123fb141)

**Comment by sergeysemenuta** [comment]
The upload success text is displayed "The applet is building. We will send you an email in 1 min or less when it has been successfully created or failed.'' after building the applet via the applet builder
![2020-10-08_15-48-43.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/fce7182d-f8d9-4382-bb34-dfda3c847fc7)
Expected result: The applet is building. We will send you an email in 10 mins or less when it has been successfully created or failed. 

Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85

**Comment by sergeysemenuta** [comment]
The issue is fixed
![2020-10-15_15-07-53.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/844eb79c-4377-401d-ad98-9ab891dbbdbe)

Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85
