### ISSUE TITLE
The event cards are populated to the next column on the calendar after adding events within 11 pm

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#249]
Steps to reproduce:
1. Log into the Admin Panel https://admin.mindlogger.org/  ( harper@prod.com // 123456 )
2. Shoose the NIMH applet and navigare to the general or individual calendar
3. Set any event at 11 pm and save
4. Set any event at 11:10 pm and save
5. Set any event at 11:20 pm and save
6. Look at the page

**Actual result:** The event cards are populated to the next column on the calendar after adding events within 11 pm
https://www.dropbox.com/s/y6lcg7pgshnx35a/2020-07-16_10-24-58.MP4?dl=0
![2020-07-16_10-27-15.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/b31ae7e3-062d-4e2b-a3fa-19d91759eefd)
**Expected result:** The event cards are not populated to the next column on the calendar after adding events within 11 pm

**Environment:**
Win 10 // Chrome Version 84.0.4147.89

**Comment by sergeysemenuta** [comment]
The issue is reproduced on  https://admin.mindlogger.org/
https://www.dropbox.com/s/tvndpara3gki5c7/2020-07-20_18-24-08.MP4?dl=0
Win 10 // Chrome 84

**Comment by WorldImpex** [comment]
@sergeysemenuta Please check on staging

**Comment by sergeysemenuta** [comment]
The issue is not reproduced on https://admin-staging.mindlogger.org/
https://www.dropbox.com/s/lw95vpvmspufd59/2020-07-21_10-47-27.MP4?dl=0
Win 10 // Chrome 84
cc: @WorldImpex

**Comment by sergeysemenuta** [comment]
Verified on https://admin.mindlogger.org/
https://www.dropbox.com/s/tjeil6coim65ske/2020-07-22_14-45-51.MP4?dl=0
Win 10 // Chrome 83
