### ISSUE TITLE
Prod. The events are disappeared form the individual calendar

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#261]
**Steps to reproduce:**
1. Log in to the admin panel https://admin.mindlogger.org/ as an owner (e.g. harper@prod.com)
2. Select the NIMH applet and schedul events on general calendar and save
3. Navigate to the users page and set individual schedule for several users and save
4. Navigate to general calendar
5. Wait for some time
6. Go back to individual caledar for users from step3
7. Pay attention to the result

**Actual result:**  The events are disappeared form the individual calendar. The individual calendar is empty
**Video:** https://www.dropbox.com/s/93dc013o7cujqo7/2020-07-23_14-32-09.MP4?dl=0
**Expected result:** The events are not disappeared form the individual calendar. The events should be displayed on the individual calendar
**Note:** On the app the events for individuals are shown
**Environment:**
https://admin.mindlogger.org/

**Comment by jj105** [comment]
# https://github.com/ChildMindInstitute/mindlogger-backend/pull/812
# https://github.com/ChildMindInstitute/mindlogger-admin/pull/263

**Comment by sergeysemenuta** [comment]
The issue still reproduces on https://admin.mindlogger.org/ , Chrome 84//Firefox 79
https://www.dropbox.com/s/x82tg2jc9h7axuf/2020-08-01_14-34-16.MP4?dl=0

**Comment by sergeysemenuta** [comment]
Verified on:
https://admin.mindlogger.org/
Win 10 // Chome 84
