### ISSUE TITLE
Unable to set event on admin - Staging

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#264]
Steps to recreate: 
1. Log onto admin and open general schedule 
2. Try to add an event with a few options 
3. See Results 

Expected: User can scroll up to save the event
Actual: User cannot scroll all the way up to the save button on the event card 

MacOS - Google Chrome 

![ezgif-4-83269e3c1f58.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/1f992ebb-85af-4708-8a3c-27a61f9f7dd8)

**Comment by sergeysemenuta** [comment]
The issue still occurs
Unable to scroll up/down in the pop-up. The same result on the Chrome browser
Video: https://www.dropbox.com/s/mqllm1n271floj6/Untitled.mov?dl=0
Checked on:
https://admin-staging.mindlogger.org/
MacBook Air 13" (MMGF2) New 2016 (8Gb RAM) // Mojave Version 10.14.1
Safari 12.0.2// Chrome 84
cc: @WorldImpex

**Comment by natalia-muzyka** [comment]
Not reproduced on a new design: https://www.screencast.com/t/3st8hpy5oC

https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
