### ISSUE TITLE
Removing events from one applet removes the event from another applet on the admin panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#265]
**Steps to reproduce:**
1. Log in to the Admin Panel https://admin.mindlogger.org/ as an owner (harper@prod.com //123456)
2. Upload 2 NIMH applets
3. Shedule events for the 1st applet on General calendar and save 
4. Schedul events for the 2nd applet on General calendar and save
5. Remove all the events from the 1st applet and save
6. Navigate to the general calendar on the 2nd applet
7. Pay attention to the result

**Actual result:**  Removing events from one applet removes the event from another applet
**Video:** https://www.dropbox.com/s/sjla6sr6m2vzvtu/2020-07-25_10-19-32.MP4?dl=0
**Expected result:** The events shoudl be removed only from the 1st applet on the general callendar
**Note:** This bug has an impact on the app as well. The schedule is reset for the users that are users of the 2nd  applet

**Environment**: 
Production server 
Win 10 //Chrome 84

**Comment by jj105** [comment]
# https://github.com/ChildMindInstitute/mindlogger-admin/pull/276

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.dropbox.com/s/6d07yw5owhghadi/2020-08-01_14-21-21.MP4?dl=0
Verified on: 
https://admin.mindlogger.org
Win Chrome 84 // Firefox 79
