### ISSUE TITLE
 The event cards are duplicated on the admin panel after saving the schedule

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#271]
**Steps to reproduce:**
1. Log in to the admin panel https://admin.mindlogger.org/
2. Select the NIMH applet and navigate to the general calendar
3. Select the Pre-Questionaire activity and set any schedule setting and click the "Save" button
4. Click the "Save all Scheuled activities" button
5. Close the "Saving Schedule" pop-up
6. Make actions that are described in step 3,4,5 with other activities (Morning, Midday,Night)
7. Wait for some time and reload the page
8. Look at the calendar

**Actual result:** The event cards are duplicated on the admin panel after saving the schedule
**Video:** https://www.dropbox.com/s/4afayi830fko5ne/2020-07-28_11-58-29.MP4?dl=0
**Note:** Reproduced on the newly created account: newaccounttest@prod.com // 123456
![2020-07-28_11-27-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/78d386f9-a676-4789-a791-cbed07678995)
![2020-07-28_12-01-05.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/26dbbe29-418d-4f20-9d80-c99480485218)
**Expected result:** The event cards are not duplicated on the admin panel after saving the schedule

**Environment:**
Win 10 // Chrome 84

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.dropbox.com/s/cphumlpbndgfb52/2020-07-29_10-39-52.MP4?dl=0
Chedked on: https://admin.mindlogger.org/, Win 10 // Chrome 84

**Comment by sergeysemenuta** [comment]
The issue is reproduced on staging https://admin-staging.mindlogger.org/
The event cards are duplicated 
Test account: owen@ml.com // 123456
https://www.dropbox.com/s/8jod1zthdy4ila8/2020-07-30_10-53-26.MP4?dl=0
Win10 // Chrome 84
cc: @WorldImpex

**Comment by WorldImpex** [comment]
Fixed on prod  @devbtech Should we close this out?

**Comment by sergeysemenuta** [comment]
Closing this ticket. The issue is not reproducible on production
