### ISSUE TITLE
#1 Admin Dashboard Landing Page

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#272]
As an owner, I want to have a more intuitive experience on the dashboard so I can better administer my applet 

Requirements
- This effort will stud in the landing page after the user logs in. The pages linked from there will be taken care of in other tickets 
- Please replace all purple with the MindLogger blue or a shade of it depending on the design 
- Create a pager for all tabs and allow the user to sort the rows of data
- Pinned applets will move to the top of the list 
- Search should query the backend to optimize performance 
- Management of users will be accomplished here as well
- Multi-select is done with click and drag or click and CTRL 

[Design Assets](https://matter-lab.slack.com/archives/CH3L0LJR0/p1595937536201100)

![Admin Dashboard.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d3b445af-7ba7-4974-9d95-e3dbb8e35097)

![Organizer Mgmt.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/61b1f159-284e-4f77-ba5b-6a59685345cc)

[Landing Page Components](https://app.zenhub.com/files/189080374/29b4663d-0978-420a-aba3-686e0e47777a/download)

[Landing page Specs](https://app.zenhub.com/files/189080374/636d5316-1f93-45c7-9abf-38305bc2721a/download)

**Comment by sergeysemenuta** [comment]
Implemented and works as expected according to the Requirements
**Verified on** https://admin-staging.mindlogger.org/ Win 10// Chrome 87
