### ISSUE TITLE
#2 Applet Selected 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#273]
As an owner, I want to select an applet to narrow down my list of users so that I can view related data 

Requirements
* Allow the user to search with text to filter the MRN list 
* When  a user clicks on a MRN row then option buttons appear 
* Users in list are only from the applet selected 

![Screen Shot 2020-10-19 at 7.48.39 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/85ec4135-d209-4745-bf9e-ab10b126b154)

![Admin Dashboard.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/73bc2ac2-b30e-4a2d-a1ad-39fa8ef66e97)

[Design Assets](https://matter-lab.slack.com/archives/CH3L0LJR0/p1595937536201100)

**Comment by sergeysemenuta** [comment]
Works as expected regarding the requirments on https://admin-new.mindlogger.org/
Closing this ticket out.
