### ISSUE TITLE
#4 Schedule Group/ Individual Schedule 2.0 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#274]
Requirements: 
- Update the Calendar to align closer to the new design 
- Move options into "Event Details" and javascript remove code from event detail card 
![Scheduling tool .png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b8a1f427-445e-45fa-ad3a-dd584b903ded)
- When clicking on a day to open a new event, skip the small card and open the event detail card automatically. 
[Design Assets](https://matter-lab.slack.com/archives/CH3L0LJR0/p1595937536201100)

![Schedule 2.0 .png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c0812d50-21b9-4b37-8e41-323b25d5602b)

![Admin Dashboard.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8aec6e50-8486-4a79-8bc9-7ce304453e28)

**Comment by devbtech** [comment]
Please test on admin new design.

**Comment by Eugenia299** [comment]
Works as expected regarding the requirements on https://admin-new.mindlogger.org/
Win 10 // Chrome 87
