### ISSUE TITLE
#3 User Detail Page - User Data Viz 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#275]
As a reviewer, I want to see a data visualization dashboard so that I can review the user's data. 

Requirements: 
* The Data Visualization page should be a separate tab that is outlined when the user clicks to see the information 
* Data Visualization page is the default view when the user lands on the user's data detail page 
* Always show one 1 of data for the week the user is on Monday-Sunday 
* Ensure that plot lines are aligned by activity and item level 
* Activities are shown unexpanded as default with a line plot for when an activity was completed
* If an activity is expanded then show item level details with response data for each item in that activity 
* If an activity is taken more than once in a day, then show two dots on that day. 
  * The time a response was recorded should be what factors one dot being before another. 
  * If the reviewer changes the date to same day, then the distance between dots should be based on time of day 
* Sliders, checkboxes, and radio buttons should show as a dot for the answer that was provided on that day. 
* If multiple days have responses for slider or radio button, show line plot to connect each dot 

![Data Viz Without Scoring  (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4c7c81d4-6891-45e5-aa55-e67aae7650c0)

**Comment by devbtech** [comment]
Please test on admin new design.

**Comment by Eugenia299** [comment]
Works as expected regarding the requirements on https://admin-new.mindlogger.org/
Win 10 // Chrome 87
