### ISSUE TITLE
 I want to change the language of my admin panel 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#297]
As a user of the admin panel, I want to change the language of the panel so that I can administer applets to my users and read it in my native language 

Description: Provide a way on admin panel to change the language of MindLogger so non-English speaking users are able to take assessments without needing to translate

Requirements
[Content](https://docs.google.com/spreadsheets/d/1XLI0t3heBJ366I36D8pUbHLz8xWV4Um-l965sa5G6PU/edit?usp=sharing)
Provide the user a way to change the language of the admin panel prior to logging into the user's account
A user should be able to transition between different languages with a click of the button
French is the required language
Future support for other languages should be easily done after this has been setup (generic names for all the text strings in the code, and translation resource files)

Acceptance Criteria
Given I am a user of the admin panel 
When I want to change the language of MindLogger
Then I navigate to my login screen

Given I am a user
When I change the language to French
Then all of the text in the admin panel changes

**Comment by sergeysemenuta** [comment]
Works as expected according to the Requirements
Verified on:
https://admin-staging.mindlogger.org/
Win 10 //  Chrome 87
