### ISSUE TITLE
Change MRN Copy to Institutional ID

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#298]

**Comment by sergeysemenuta** [comment]
Verified on https://admin-staging.mindlogger.org/
The  MRN is changed to Institutional ID 
![2020-09-02_16-27-53.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ba4f7c7a-bc7d-4206-b7a9-a6431a3eb863)
Win10 // Chrome 85
