### ISSUE TITLE
There is a clickable area outside of the checkboxes on the event details modal window

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#300]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/
2. Select the applet and navigate to the general or individual calendar
3. Open the  event details modal window
4. Click outside of the checkboxes
5. Pay attention to the result

**Actual result:** There is a clickable area outside of the checkboxes  on the event details modal window
**Video:** https://www.screencast.com/t/yuYnHjqtJn9x
**Note:** The same behavior occurs next to "Forgot password? " link on the 'Login' form
https://www.screencast.com/t/4qMovAgABR
**Expected result**: There is no clickable area outside of the checkboxes  on the event details modal window. The checkboxes should be marked after clicking directly on the checkboxes 

**Reproduced on:**
https://admin-staging.mindlogger.org/
https://admin.mindlogger.org/
Win//10 Chrome 84 // Firefox 79

**Comment by natalia-muzyka** [comment]
Not reproducible on a new design: https://www.screencast.com/t/OHIMDNNWMjT

https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
