### ISSUE TITLE
TokenReport with additional comments

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-admin-OLD-Vue#302]
As a manager, I want to export a report about a user and add comments so that I can customize the messaging to the user. 

Requirements
* Export a PDF that shows the time range the user has selected 
* The frequency chart and the cumulative score chart should be shown 
* The mockup is not to scale but only for representation of expectations 
* When the admin selects "Export to PDF" from the data visualization screen,  show a module to create notes in markdown 
  ** If the user does not add notes, do not show that section in the PDF when exported 

![TokenReport.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5d7cfe2d-fb78-4c06-87e6-2cb130987944)

**Comment by WorldImpex** [comment]
1. Only one chart is shown in the PDF based on what the user has selected at that time. Expected: Frequency chart selected and cumulative chart should be shown in the same PDF 
2. Missing header text with Applet title and date of export

**Comment by natalia-muzyka** [comment]
**Fixed:**
1. Frequency chart selected and cumulative chart are shown in the same PDF 
2. Header text with Applet title and date of export is displayed

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/06c22c87-82fd-47c9-8d08-d40f8f2d1a92)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 97.0.4692.71 
macOS 10.15 // Chrome 97.0.4692.71
