### ISSUE TITLE
Schedule an Event for only Days Activity should be available

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#304]
As a coordinator, I want to schedule specific days an activity is available so that the user cannot answer the activity every day. 

We need a way for coordinators to schedule an event for an activity to only show on the days selected. An example would be if a user only wants the activity to show on a Friday of each week, the rest of the time the activity would not be visible 

Requirements 
* When a user sets an event to repeat weekly or monthly, then give the option to "Only show the activity on the scheduled day" 
* If the user removes the weekly or monthly option, then the Only show the activity on the scheduled day is removed as well 
* If this feature is set with a notification or any other parameters, it is copied to each future event 

Accept Criteria 
Given I am a user, 
When I have a weekly event scheduled for an activity on Friday
Then only on Friday will the event be shown on my device 

Given I am a coordinator
When I am scheduling a "Only show the activity on the scheduled day" is selected
Then any parameters I add to this event will be duplicated on others

**Comment by WorldImpex** [comment]
Weekly set schedule seems to function as expected with notification. iPhone 6s

**Comment by sergeysemenuta** [comment]
Weekly/Monthly set schedule works as expected regarding the  Requirements
Checked on https://admin-staging.mindlogger.org/ 
Win 10 Chrome 85
Win 10 // Chrome Version 85
MindLogger app v 0.13.23
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Closing this ticket out
