### ISSUE TITLE
Timed Activity

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#305]
As an editor, I want to add an activity timer so that if a user starts an activity they only have a predetermined amount of time to complete the assessment 

Requirements: 
* The editor can turn on the Timed Activity and set the amount of time (in hours and minutes) the user has access to the whole activity after starting it 
* Once the user starts it, the timer begins and nothing will stop the count down to when the activity is no longer available for the user for that day
* Once the time as run out, the user cannot access the activity any longer and any data that was entered is submitted for that activity 
* Idle time should not be available choices if the user sets an activity timer 
* Show timer on activity card 
* ![Slack-Wil-Stockpile (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8fcf70b9-295f-4ae7-884f-7f0a9d8bf3c3)
* Show time left in activity 
![Slack-Wil-Stockpile (2).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9e371de9-79db-449b-a4e0-8cd7e125693c)

Given I am a user 
When I have a Timed Activity 
Then I will see on my activity cards how much time I have available to complete it in 

Given I am a user 
When I have a Timed Activity 
Then I see how much time I have left to complete it in while I am taking it 

Given I am a coordinator
When I create an event and select Timed Activity
Then idle timer, extended past due and timeout are greyed out and cannot be used 

Given I am a coordinator 
When I create an event and select Timed Activity 
Then I can enter the hours and minutes the activity should be available to for the user to complete the activity in

**Comment by sergeysemenuta** [comment]
Works as expected according to  requirements

A separate issue raised related to this feature  https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1371

Closing this task out
