### ISSUE TITLE
Unable to invite the reviewer to an applet after specifying the Institutional ID into the "users" field on the "Create Invitation" form

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#323]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ as an owner /manager/coordinator https://admin-staging.mindlogger.org/
2. Select the TokenLogger or NIMH applet and navigate to the create invitation form
3. Fill out the "FirstName, LastName, Email" fields
4. Select the  "reviewer" item from the "Role" list
5. Specify the valid Institutional id for the active users (Not Id of the users) into the "Users" field
6. Click the "SUBMIT" button
7. Look at the result

**Actual result:** Unable to invite the reviewer to an applet after specifying the Institutional Id into the "users" field on the "Create Invitation" form. The invitation is not created.
**Video:** https://www.screencast.com/t/MhehQPhqF
**Expected result:** It should be possible to invite the reviewer to an applet after specifying the Institutional Id into the "users" field on the "Create Invitation" form. After entering the valid Institutional id for the active users (Not Id of the users) into the "Users" field and clicking the  "SUBMIT" button the invitation should be created
****
**Environment:**
Win 10 // Chrome 85

**Comment by ngonzalvez** [comment]
The issue here is that the IDs entered for the **users** field in the invitation form are **Institutional IDs**. The form expects one or more **User IDs** as provided in the users table on the top section of the page.

**Comment by ngonzalvez** [comment]
@WorldImpex  Do we need to continue to support invites using the user UUID? 

![image.png](https://images.zenhubusercontent.com/54d0f9907c6ccc6277a71011/8eee902c-9c84-4fa7-9ae1-2cc0024cac51)

Also, should the **Active Users** table show the **Institutional ID**?

**Comment by WorldImpex** [comment]
@ngonzalvez I think we might still need it as we have no other way in the QA environments to know who the user is without a MRN but production doesn't need it. MRN(institutional ID) should be used. Yes active users should show institutional ID

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/A3iZAs6SliQS
Checked on:
https://admin-staging.mindlogger.org/
Win 10//Chrome 85
