### ISSUE TITLE
The unnecessary characters are displayed for the date/time range stamp in the 'TokenLogger' chart 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#330]
**Steps to reproduce:**
1. Log in to the Admin panel https://admin-staging.mindlogger.org/  as a reviewer (sara@st.com / / 123456)
2. Select the TokenLogger applet and navigate to the users page
3. Choose several users and click the " View the applet dashboard for the selected users" button
4. Observe the date/time range stamp 

**Actual result:** The unnecessary characters ".000Z" are displayed for the date/time range stamp in the 'TokenLogger' chart 
![2020-09-08_15-38-30.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c7db2d3d-31ad-48fb-89af-e1df4cc8103e)
**Video:** https://www.screencast.com/t/f81hqSjJb2
**Expected result:** The characters ".000Z" are not displayed for the date/time range stamp in the 'TokenLogger' chart. The user should see the date and time stamps and it should be clearly visible

**Environment:**
https://admin-staging.mindlogger.org/ 
Win 10 // Chrome 85

**Comment by ngonzalvez** [comment]
Oops. My bad. That was debugging code. But showing the selected time range (nicely formatted) is not a bad idea. I'll fix the format and styling.

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2020-09-21_11-04-50.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/36341141-1b79-439e-b5f9-bbb9cce6085f)
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85
