### ISSUE TITLE
Transfer Applet Ownership 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#332]
As an owner, I want to transfer ownership of an applet to another user so that I can give control to an applet that I do not need any longer. 

Requirements 
* An owner can transfer ownership of an applet via the select button with the option to transfer ownership
* If the owner clicks on that button then he or she should see a confirmation button "Are you sure you want to transfer ownership of your applet to another user? This will only transfer the applet and no user data will be transferred."
   * If the user clicks Yes, then have the 
   * If the user clicks No, then land the user on the homepage

**Comment by sergeysemenuta** [comment]
The Transfer Applet Ownership functionality works as expected.
**Video:** https://www.screencast.com/t/b1eBrVtP

Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome Version 85//Firefox 80

Closing this task
