### ISSUE TITLE
Export Data Updates

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#336]
We need to align [these requests ](https://docs.google.com/document/d/15lxDo9BA8CgyUTjATC87ED9oz-nv39Ti04JoH5akL2U/edit?usp=sharing)with our export file so the data is more useful for the reviewer 

https://docs.google.com/document/d/14o8FcliPf99U5VS44EWbfnahib0DuHc_XPWtzlMqaVY/edit?usp=sharing

**Comment by sergeysemenuta** [comment]
Here is a csv file with data for the EMA applet https://drive.google.com/file/d/1An2debjiJmc3Fy_KIQx6NOMuivYxGqSv/view?usp=sharing
From  staging

**Comment by WorldImpex** [comment]
Mike confirms that this is sufficient

**Comment by WorldImpex** [comment]
Steps to recreate

1. Log into an account that has stored user data 
2. Export a user's data
3. See results 

Expected: The start and stop time is provided 
Actual: Null is shown 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/bf2870a7-435c-44c9-a5a1-700934a48878)

**Comment by sergeysemenuta** [comment]
The start and stop time are provided in the staging
![2021-04-07_18-43-56.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/59c53a8c-64c9-4642-9df1-1610dc4e65ce)
Other issues are mentioned in [901](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/901)

Checked on:
https://admin-staging.mindlogger.org/
Closing this ticket out
