### ISSUE TITLE
The data is not displayed on the "Tokenlogger" dashboard after completing the assessment

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#338]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ as an owner (ruby@st.com // 123456) 
2. Select the TokenLogger applet and navigate to the users page
3. Log in to the app as users that have this applet and complete the assessment
4. Select active users and navigate to the dashboard
5. Look at the page

**Actual result:** The data is not displayed on the "Tokenlogger" dashboard after completing the assessment. The dashboard is empty.
**Video:** https://www.screencast.com/t/6nsdgBQIkc
**Expected result:** The data is displayed on the "Tokenlogger" dashboard after completing the assessment. 

**Environment:**
 https://admin-staging.mindlogger.org/ 
Win 10 // Chrome 85

**Comment by WorldImpex** [comment]
@sergeysemenuta Lets double check this after institutional ID is deployed #232

**Comment by sergeysemenuta** [comment]
- The data is not displayed for the current day. For the last days, It shows up correctly.

https://www.screencast.com/t/wDBYUtKs7n
https://www.screencast.com/t/Ij95Lo5KK6R7
**Environment:**
https://admin-staging.mindlogger.org/
Win10//Chrome 85
CC: @WorldImpex

**Comment by ngonzalvez** [comment]
This was caused by an error when formatting the new format of the users response created by the latest mobile app version. This was fixed in [this PR](https://github.com/ChildMindInstitute/mindlogger-admin/pull/346). I'm closing this one.

**Comment by sergeysemenuta** [comment]
The data is displayed and updated.
https://www.screencast.com/t/2eaZZZPGMLjm
Checked on:
https://admin-staging.mindlogger.org/ //Chrome 85
