### ISSUE TITLE
The "user" role is applied for all types of users for the coordinator in the  'Active Users' section

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#342]
**Preconditions:**
All types of users (manager, coordinator, user, owner, editor, reviewer)  are existed in the "Active Users" section (users are invited by the owner)
**Steps to reproduce:**
1. Log in as an owner (owen@ml.com // 123456)  of the applet to the  admin panel https://admin-staging.mindlogger.org/ 
2. Select the NIMH applet and navigate to the 'users' page 
3. Invite a new user to be a coordinator of the applet and accept the invitation by that user
4. Log in as a coordinator (From step 3) to the admin panel and navigate to the 'users' page
5. Look at the "Roles" column in the 'Active Users' section

**Actual result:** The "user" role is applied for all types of users for the coordinator in the  'Active Users' section
![2020-09-14_14-36-44.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/05fa6276-5391-4ea8-a6d8-d5a4b04de0e7)
**Expected result:** The different types of users should be shown for the coordinator in the  'Active Users' section

**Environment:**
Win10//Chrome85 // Firefox 80

**Comment by ngonzalvez** [comment]
@sergeysemenuta I stumbled across this code while working on #337. It seems like this is implemented on purpose. The user roles are shown only for managers. If you are not a manager, then all the users will be shown as users. I don't know if this is the expected behavior, but it is the way it was implemented.

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2020-10-02_13-41-30.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/82c8992b-8e95-42af-8d11-711947b1f816)
Win10//Chrome85 // Firefox 80
https://admin-staging.mindlogger.org/
