### ISSUE TITLE
TokenLogger Applets User Data Legend Over Runs border

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#344]
Steps to recreate: 
1. Log into admin panel 
2. Navigate to users 
3. Click on a user and view user's response data chart
4. See results 

Expected: Legend text is within the border of the cart 
Actual: Text from legend spills over the border

**Comment by sergeysemenuta** [comment]
The issue is fixed
![2020-09-21_17-31-30.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9afbbe58-4382-4389-8d04-83dea5cf4383)
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85
