### ISSUE TITLE
The "Remove user" option doesn't  function for the coordinator role on the 'users' page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#350]
**Preconditions:**
The user is a coordinator of an applet
**Steps to reproduce:**
1. Log in as a coordinator of the applet to the admin panel
2. Select the applet were are you a coordinator and navigate to the 'users' page
3. Click the basket icon for the user
4. Click the "Remove user" 
5. Pay attention to the result

**Actual result:**
1. The "Remove user" option does not function for the coordinator role
2. The "Remove user & data" is available for the coordinator
**Video:** https://www.screencast.com/t/BXCS2HUP4Zl
![2020-09-15_13-28-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c31bb869-5c16-47bc-acfb-50a004838175)
**Expected result:** 
1. The coordinator should be able to remove the user from the applet
2. The coordinator should not be able to  remove the user and data from the applet (The 'Remove user& Data' should be hidden for coordinators)Only owners and managers should see that option

**Environment:**
https://admin-staging.mindlogger.org
Win 10//  Chrome 85 // Firefox 80

**Comment by WorldImpex** [comment]
@ProNinoGit120 What else needs to be completed? Do you need to arrange with @jj105 to wrap up the backend?

**Comment by sergeysemenuta** [comment]
The issue still reproduces
1. The "Remove user" option does not function for the coordinator role
2. The "Remove user & data" is available for the coordinator
Video: https://www.screencast.com/t/aAPTckHyaV
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/KJirDvvvDb6
Checked on:
https://admin-staging.mindlogger.org/
Win10//Chrome 85// Firefox 80
