### ISSUE TITLE
Monthly Events are causing the applets to disappear

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#412]
Steps to recreate
1. Log into staging-admin (wavanauken+1@gmail.com/ abcd123)
2. Navigate to the general calendar 
3. Schedule an activity with "Only scheduled day" with repeat monthly
4. Save
5. Open mobile device and refresh applet list.
6. See results

Expected: The applet is updated with the correct schedule
Actual: All applets disappear from device. If you delete the monthly event, then all applets re-appear

**Comment by sergeysemenuta** [comment]
The issue is not reproduced
https://www.screencast.com/t/ZoHJj7JaS
Test account: leo@stage.com // 123456
Staging
MindLogger app v 0.13.23
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
