### ISSUE TITLE
Add response option values in user data export.

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#415]
We want to provide owners/ reviewers with the response option values when they are exporting the user's response data so that the reviewer of the data knows the values of the responses

**Comment by sergeysemenuta** [comment]
The response option values are added and generated to the CSV file.
Checked on TokenLogger, HIMH, DBT and applets created via the applet builder

![2020-10-19_15-14-52.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/09abbccf-aa9d-4337-a474-70a4fbf3a12d)

Environment:
https://admin-staging.mindlogger.org/
Win 10// Chrome 85
