### ISSUE TITLE
It is not possible to edit  an existing applet on the admin panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#416]
**Preconditions:**
The applets are displayed on the applet page
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ owen@ml.com//123456
2. Choose any applet and click the "EDIT" button
3. Look at the result

**Actual result:** It is not possible to edit an existing applet. The user is navigated to the build page with empty fields
**Video:** https://www.screencast.com/t/EZolIoPslAa
**Expected result:** The user is navigated to the build page and all fields should be filled in for the current version of the applet
**Environment:** 
https://admin-staging.mindlogger.org/
Win 10//Chrome 85

**Comment by WorldImpex** [comment]
This seems to be fixed @sergeysemenuta

**Comment by sergeysemenuta** [comment]
The user is navigated to the correct page and all fields are filled out.
Closing this ticket out. Created the separate one [421](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/421)
