### ISSUE TITLE
The layout of the data chart becomes broken when filtering results by date range

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#425]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (bughunterqa123@gmail.com // 123456)
2. Select tokenLogger applet and navigate to the users page
3. Select a user and navigate to the TokenLogger dashboard (Applet password: Qwe123!!!)
4. Select the previous date from the second filter
5. Select the  previous  day from the first filter
6. Select the past days from the second filter
7. Look at the chart

**Actual result:** The layout of the data chart becomes broken when filtering results by date range. The future date is shown by default on the date range filter
**Video:** https://www.screencast.com/t/INdN9g3h
![2020-10-13_11-43-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6146ad46-8c3c-4136-85e7-b03d63d571a1)
**Expected result:** 
1.The layout of the data chart is not broken when filtering results by date range. 
2.The data chart should display correct data.

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85

**Comment by WorldImpex** [comment]
Graph does not break but a user should not be able to filter backwards

**Comment by natalia-muzyka** [comment]
Close due to the redesigned TL.
