### ISSUE TITLE
The wrong data is displayed for the group of users on the TokenLogger dashboard

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#426]
**Preconditions:**
Several users (User A, UserB, User C) took the TokenLogger assessment
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (bughunterqa123@gmail.com // 123456)
2. Select the TokenLogger applet and navigate to the users page
3. Select several users and navigate to the TokenLogger dashboard (Applet password: Qwe123!!!)
4. Look at the graphs

**Actual result:** The wrong data is displayed for the group of users on the TokenLogger dashboard
**Video:** https://www.screencast.com/t/og5C2CR4A6
**Expected result:** For each user selected the separate graph should be shown on the dashboard with correct token values

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85

**Comment by natalia-muzyka** [comment]
Close due to the updated TokenLogger.
