### ISSUE TITLE
TokenLogger: Add # of occurrences

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#429]
As a reviewer, I want to see the number of times a item option was selected so that I can visualize the data better 

Requirements: 
- Add the number of times an item was selected for a given day when the reviewer hoovers over the bar 
- Text-wrap the words to not have the box take up so much space on the page 

![Screen Shot 2020-11-02 at 6.05.57 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/eafd4926-4d10-4bde-bcc9-3dee7653b2fa)

**Comment by devbtech** [comment]
Please test on admin new design.

**Comment by sergeysemenuta** [comment]
The text is not readable after hovering the mouse over the bar
**Note :** The user has taken the activity several times per day
owner: mrn@ml.com// 123456
(Applet password: Qwe123!!!)
Users:
apple@ml.com /123456
mango@ml.com // 123456
TL sleep applet
![2020-12-21_14-14-48.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0a73f237-0026-489d-828e-0081105759c7)
Checked on:
https://admin-new.mindlogger.org/
Win 10 //Chrome 86

**Comment by Eugenia299** [comment]
Fixed on:
https://admin-new.mindlogger.org/
Win 10 // Chrome 87
![token.png](https://images.zenhubusercontent.com/5fe0464563e4d26035f8293f/ebdfe5c6-d279-4444-b8b6-845e761d010c)
