### ISSUE TITLE
Applet Deletion Confirmation 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#435]
As an owner deleting an applet, I want a warning when trying to delete an applet that requires me to confirm that is what I want to do so that I do not by accidentally delete an applet.

**Comment by sergeysemenuta** [comment]
The applet deletion confirmation is implemented and works as expected
https://www.screencast.com/t/AqkuZXIsJU
https://admin-staging.mindlogger.org/
Win 10 Chrome86//Firefox 82
