### ISSUE TITLE
Set Reminder for activity not taken X number of days

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#436]
As a coordinator, I want to remind a user to take an activity after X amount of times have been missed when scheduled 

If a user does not submit responses to an activity after X number of days, we want to send a reminder notification 

Requirements 
- Move Random Notification up and next to "Turn on notifications" 
- Change Checkbox of "Turn on notifications" to an on/off toggle 
- When the "Turn on notifications" is toggled on then "Random Notification" and "Set Reminder" notification checkboxes are shown
- If the coordinator sets both a random and reminder notification then the random notification module is at the top and the reminder notification module is at the bottom 
- Allow the coordinator to set the number of days or hours in a row that a user has not submitted responses for an activity 
- Allow the coordinator to set the time the notification will send as well. 
- After X number of days or hours, send a notification to the user, "This is a reminder to take *activity name*. 
- If the coordinator has set a reminder for 3 days and 8 AM, then on day 4 at 8 AM the user should receive a notification saying "This is a reminder to take *activity name*. 

![Reminder Notification.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/40792d91-0e64-4f07-b757-6146c84f7484)

**Comment by WorldImpex** [comment]
As a coordinator, I want to remind a user to take an activity after X amount of times have been missed when scheduled

**Comment by sergeysemenuta** [comment]
Reminder notifications are not fired on the devices
I've checked in on:
Staging:
ML v.0.15.3
ML v.0.15.2
ML v.0.15.1
On both platforms (iOS/Android)

**Comment by WorldImpex** [comment]
sent reminder on +1 for lookup act to remind in 2 days

**Comment by sergeysemenuta** [comment]
Works as expected on the  admin-new and mobile app
![2021-03-10_10-15-09.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/181666af-7bff-476c-9b02-92574de74040)
api-new
ML v 0.15.15
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
Works as expected on the https://admin-staging.mindlogger.org/ and mobile app
![2021-03-15_9-57-38.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/b7e98cf1-e2ff-4326-9bb9-5eb1d7475191)
![2021-03-15_9-57-38.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6ea90204-6cb9-4a35-b8e9-b7e70e75c40a)
