### ISSUE TITLE
The applet  data is not loaded on the TokenLogger dashboard  after adding a new option to the item  for an existing applet and original options become undefined on the app

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#442]
**Preconditions:**
The Tokenlogger applet is uploaded to the admin panel. 
Several users are members of the applet and took the assessment. 
The data is displayed on the Tokenlogger dashboard
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ as an owner/manager
2. Go to edit The TokenLogger applet
3. Add a new option to the items with the token value and save to the dashboard
4. Navigate to the users page
5. Select a user and navigate to the TokenLogger dashboard
6. Look at the result
7. Observe the token screen on the app

**Actual result:** The applet  data is not loaded on the TokenLogger dashboard  after adding a new option to the item  for an existing applet and original options become undefined on the app
**Video:** https://www.screencast.com/t/Y6BBm2dCbx

**Environment:**
https://admin-staging.mindlogger.org
Win 10 // Chrome Version 85
MindLogger app v 0.13.27
Pixel 4 XL // Android 11
iPhone X // iOS 13.3

**Comment by Matchdev120** [comment]
@jj105 `undefined` issue on mobile app is already fixed but TL dashboard is not fixed yet.

**Comment by sergeysemenuta** [comment]
The issue is fixed on the App and on the Admin panel
![2020-10-27_11-04-58.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/1b3bfb8a-685a-4c8c-8c40-fad9b03d086b)

Environment:
https://admin-staging.mindlogger.org
Win 10 // Chrome Version 85
MindLogger app v 0.13.31
Pixel 4 XL // Android 11
iPhone X // iOS 13.3
