### ISSUE TITLE
The token value option is missing on the  "Edit Item" modal window 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#448]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (e.g. bughunterqa123@gmail.com // 123456)
2. Click the EDIT button on the TokenLogger button
3. Navigate to the  "Edit Item" modal
4. Observe the modal window

**Actual result:** The token value option is missing on the  "Edit Item" modal window 
![2020-10-26_11-33-59.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/d3150f13-0138-4461-bcc9-0a43340b7611)
**Expected result:** The token value option is shown on the  "Edit Item" modal window 

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 //Chrome 85

**Comment by Matchdev120** [comment]
@sergeysemenuta The version of Applet-schema-builder is just updated. Please test it again.

**Comment by sergeysemenuta** [comment]
Fixed on:
https://admin-staging.mindlogger.org/
Win 10 //Chrome 85
![2020-10-26_15-28-34.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9a73d1d0-efae-45b6-a591-82c6dda5324b)
