### ISSUE TITLE
Creating an applet with conditional Response data is not saved in data export

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#450]
Steps to recreate
1. Create an applet with conditional logic 
2. Open new applet on device and submit responses 
3. Navigate to admin panel and export that user's response 
4. See Results

Expected: there is response data stored in the exported file 
Actual: No response data is available. only headers 

wavanauken+5@gmail.com/ abcd123

**Comment by sergeysemenuta** [comment]
The data is exported to the cvs file but it shows incorrect responses and items
![2020-10-30_12-38-48.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/a30ba950-9c51-412f-b062-05e48db262ca)
 CC: @WorldImpex

**Comment by sergeysemenuta** [comment]
The issue is fixed
![2020-11-03_13-05-53.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/cde64b8a-671b-4498-9533-44003dcb1939)
