### ISSUE TITLE
TokenLogger Dashboard does not show for Newly Created Applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#451]
Steps to recreate: 
1. Create a TokenLogger applet (First TokenLogger for Wil) 
2. Take Tokenlogger on device and see the graph there change
3. Navigate to admin panel and open data viz for that user 
4. See Results

Expected: Graph shows the results of the response data 
Actual: The graph just says loading 

wavanauken+4@gmail.com/ abcd123

**Comment by WorldImpex** [comment]
Reproducible 

![ezgif-5-e20ca40feac2.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9f42a61d-38d3-486e-9fba-b74b1ecdb9f9)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
The TokenLogger Dashboard shows up for Newly Created Applet
![2020-11-02_11-43-48.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4030e255-f387-448b-813e-4de6f71a9e29)

https://admin-staging.mindlogger.org/
Win 10 chrome 86
