### ISSUE TITLE
Pending Invitation does not build on admin when in French 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#457]
Steps to recreate: 
1. Create a new invitiation on admin 
2. See pending invitation 

Expected: There is a table with the details on the invitation sent out 
Actual: No table is present 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9091d6b8-c0b0-48b7-8858-61328d3d7516)

**Comment by WorldImpex** [comment]
dupe of #460

**Comment by sergeysemenuta** [comment]
Looks as expected
![2020-10-30_10-27-39.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/924eb462-c669-4a3e-8505-7fb11a9fa1e1)
https://admin-staging.mindlogger.org/
Win 10//Chrome 85
