### ISSUE TITLE
Have "Show Version Changes" off by default

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#463]
On the data viz, have the checkbox unchecked with the bars not showing by default when the user lands on the page 

![Screen Shot 2020-10-28 at 6.39.44 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/0d122212-9f37-4f48-8aab-23a20d3f666f)

**Comment by sergeysemenuta** [comment]
- The "Show Version Changes" checkbox is checked by default.

Video: https://www.screencast.com/t/rgyvoemto
**Expected:** The "Show Version Changes" should be unchecked by default
Checked on:
https://admin-staging.mindlogger.org/
Win 10 //Chrome 86

**Comment by sergeysemenuta** [comment]
The issue is fixed
![2020-11-02_13-28-49.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/57c12c75-f1d5-4a7c-a5ed-14302338d73e)
Checked on:
https://admin-staging.mindlogger.org/
Win 10 //Chrome 86
