### ISSUE TITLE
Configure admin-panel for surveys to require video response

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-admin-OLD-Vue#47]

**Comment by binarybottle** [comment]
@shnizzedy -- Where did this request come from?  When would we require a video response?

**Comment by shnizzedy** [comment]
> @shnizzedy -- Where did this request come from?

@binarybottle I just converted it from a note to an issue to add labels. Here's the whole history of the note/issue:

> @henryrossiter added [Configure admin-panel for surveys to require video response](https://github.com/orgs/ChildMindInstitute/projects/9#card-18569363) to **Sprint 1 🏃🏻‍♀️**
> on Mar 8, 2019, 8:55 AM EST

> @stufreen moved [Configure admin-panel for surveys to require video response](https://github.com/orgs/ChildMindInstitute/projects/9#card-18569363) from **🏃 Current Sprint 🏃** to **❄ Icebox ❄**
> on Jun 6, 2019, 9:56 AM EDT

> @shnizzedy created this issue from a note in [**MindLogger**](https://github.com/orgs/ChildMindInstitute/projects/9#card-18569363) (**❄ Icebox ❄**)
> on Dec 5, 2019, 1:53 PM EST
