### ISSUE TITLE
Show Subscale Scoring Results to Reviewer

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#480]
As a reviewer, I want to see the results of the subscale scores from an applet 

Requirements 
* If an activity contains subscale scoring, then show the scoring in the data visualization for the applet and for each activity 
* If the activity contains a lookup table, then update the scoring to show the results from the lookup table. It is not necessary to show the original score 
* If only the user only took the activity/ applet one time then show a line plot for the applet 
* If the user took the activity/ applet more than one time then show a line chart for the applet with the different scores achieved 
  * The latest total score should be shown. If the user hovers over another plot in the line chart, show the score recorded at that time 
* When the reviewer expands the activity that has a subscale show a graph of the subscales in a bar chart if the activity was only taken once or a line plot if taken multiple times 

![Data Viz with scoring v2 .png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d530a896-4284-4873-883a-3e135f6c1614)

**Comment by devbtech** [comment]
This is deployed on admin-new. Please test on admin new design.

**Comment by sergeysemenuta** [comment]
- Remove the How old are you! How do you describe yourself? form the dashboard(For activities that contain lookup table)
![2020-12-28_18-19-08.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9ad334dc-da55-44b8-8802-1f38d2177121)
Note: The response data for these questions should be shown in the export file only

- Subscale score is incorrect for activities that contain a lookup table uploaded. Reproducible fro slider items, checkboxes, and combination of the slider, checkbox, and slider questions 
![2020-12-28_18-28-41.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/fd135da2-d118-4815-83bc-8f4d57c4625b)

- The frequency is shown as a decimal number
Expected: It should display the integer number
![2020-12-28_18-34-46.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0e3423d6-6831-43ad-9e3f-c8ac79587197)
- The dashboard is not loaded for the second invited user that completed only one activity
![2020-12-28_18-46-26.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9095342e-ae57-4305-ac07-954f4cf8c9ae)

- The dot over the line is not updated according to tho the options taken on the mobile app when the user takes an assessment several times (2,3,4 etc times per day)
Reproducible for radio, checkbox items
https://www.screencast.com/t/9uuhDqvPkw
Test accounts:
zone@ml.com // 123456 - owner
zone1@ml.com // 123456- user
zone2@ml.com // 123456- user
Applet: scoring (applet password: Qwe123!!!)
https://admin-new.mindlogger.org/

**Comment by WorldImpex** [comment]
Account being used: wavanauken+4@gmail.com/ abcd123 | Applet Password: Abcd1234!
1. Response data is not displayed for items within the subscale
![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ba8a8412-aebd-417d-9b7b-6d51b75dbc77)
2. Latest score is not being updated to the latest recorded score and is showing the first subscale/ lookup table score 
3. Subscale window does not size in there is something in the toolbar 
![ezgif-5-fda9bd2f5568.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/920154a6-892e-4818-a6b1-2b7734abe99f)
4. Ensure that dots on the line are shown for every time the activity is submitted. Right now, it looks like only one dot is present

**Comment by WorldImpex** [comment]
The below two were used with owner: wavanauken+4@gmail.com/ abcd123

Users: wavanauken+7@gmail.com/ abcd123 & wavanauken+8@gmail.com/ abcd123

1. An item that is in more than one subscale does not show the response options in each subscale 
![mindlogger-admin (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/adb6fc41-e874-4c84-8c74-a2bf6ceb7ac5)

2. "radio" item does not show response option on the subscale detail page 
![mindlogger-admin (2).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9e1a6fef-a7c0-44c1-89e7-68f9615ed4f2)

**Comment by WorldImpex** [comment]
both have been fixed
