### ISSUE TITLE
The first/last option fields for the slider settings are filed out automatically with values Min/Max after saving the item to the  activity 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#484]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (sankessqa@gmail.com // 123456)
2. Go to the applet builder
3. Create an activity
4. Add item with slider input type (Do not fill in the  First and last option fields)
5. Save the item to the activity 
6. Open the Edit item modal for the  item
7. Observe the form

**Actual result:** The first/last option fields for the slider settings are filed out automatically with values Min/Max after saving the item to the  activity 
**Video:** https://www.screencast.com/t/irzKH3FCKajv
![2020-11-02_10-54-33.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ff1b821b-f854-4241-a278-30817a61f8d7)
**Expected result:** The first/last option fields for the slider settings are not filed out automatically with values Min/Max after saving the item to the activity. The first option ad last option fields should be empty.

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 //Chrome 86

**Comment by natalia-muzyka** [comment]
Ticket for the old applet builder design.
