### ISSUE TITLE
Positive/ Negative Tokens on Graph

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#485]
As a reviewer, I want to see positive and negative behaviors in colors that differentiate themselves so that I can quickly view a chart and make a decision 

Requirements: 
* Negative value option items should show in a range of different colors of red 
* Positive value option items should show in a range of other cool colors

**Comment by sergeysemenuta** [comment]
Looks as expected

- Negative value option items are shown in a range of different colors of red

- Positive value option items are shown in a range of other cool colors
![2020-12-15_14-20-39.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/16f43536-db64-43f7-8517-7ad46c737eb4)
Checked on https://admin-staging.mindlogger.org/, Chrome 86

**Comment by sergeysemenuta** [comment]
Looks as expected.
Rechecked on https://admin-staging.mindlogger.org/, Chrome 86
