### ISSUE TITLE
Accumulation of Tokens on Graph

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#486]
As a review, I want to see the user's total amount of tokens that have been earned on a line plot on top of the original graph 

Requirements
* Show the number of Tokens a user has earned with a line on top of the original graph. 
* Negative tokens should not reduce the number of earned tokens
  * This needs to be fixed in app and on admin panel for data visualization 

![Blank diagram.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/19b62faa-0f15-4df5-bedf-fe8d0aa2b5d4)

**Comment by sergeysemenuta** [comment]
There is no number of Tokens a user has earned with a line on top of the original graph.
![2020-12-15_15-19-06.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/d54a6d8c-5075-4d25-9004-dc5e7da6eef9)
Checked on :https://admin-staging.mindlogger.org/

**Comment by henry-overton** [comment]
I think the changes are not merged  in develop branch yet. guess same for #485 as well.

**Comment by sergeysemenuta** [comment]
- The total amount of tokens that have been earned on a line plot on top of the original graph

- Negative tokens are not reduced the number of earned tokens
![2020-12-16_12-31-07.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/2692a2be-1608-42b7-80f0-4e796f7ba8d7)

Works as expected on the  Admin panel https://admin-staging.mindlogger.org/

 @WorldImpex This feature is not applied on the mobile app v 0.14.25 (245)
![2020-12-16_12-35-52.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/18cfa36c-4a80-419f-976b-a704f64a638f).
 It should be fixed on the  mobile app side as well

**Comment by devbtech** [comment]
Please test on admin new design.

**Comment by sergeysemenuta** [comment]
Works as expected on  https://admin-new.mindlogger.org/#
![2020-12-21_13-15-17.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/10a168b3-895d-4680-80d4-b3cb579c4067)

The total amount of tokens  a user has earned with a line on top still not  displayed on the app side on Data screen
ML v 0 .14.28 (248)
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
![2020-12-21_13-33-51.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0f2e7c20-3543-4b3d-b848-4c472cee4cc4)

**Comment by sergeysemenuta** [comment]
The total amount of tokens from the admin panel doesn't match the total amount on the mobile app
https://www.screencast.com/t/W21V11TlG
Checked on:
https://admin-new.mindlogger.org/
ML v 0.14.38 (258)
iPhone 8 // iOS 14
Pixel 4XL// Android 11

**Comment by sergeysemenuta** [comment]
The issue is still reproducible
The total amount of tokens from the admin panel doesn't match the total amount on the mobile app
On the app, it shows The total amount of tokens earned for the week
![2021-01-08_13-35-55.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/601e2df4-4bb7-4827-ad41-e72352b92b24)
Staging
ML v 0.14.53
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0

**Comment by WorldImpex** [comment]
Checked and on a new app the total shows but the line goes to zero which is not expected. Expected is the accumulation line would say at the total number of tokens the users has until it is increased or decreased (when purchasing tokens) 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/66bcbe41-4c67-47e4-b9f2-7c411391848f)

**Comment by techdev137** [comment]
I think token-accumulation ( mobile ) needs to be tested on new account/applet.

**Comment by sergeysemenuta** [comment]
Works, as expected, Checked on the new account / new applet (crashes@ml.com // 123456)
Staging
ML v0.14.56
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0
![2021-01-12_16-46-29.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/03ed94a9-4ec6-4e28-ab3a-bb08ccf1ff2d)
