### ISSUE TITLE
[Staging].Unable to reset password after clicking the temporary access token link

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#507]
**Steps to reproduce:**
1. Launch the app
2. Click the "Forgot password" link
3. Submit your email address (e.g. ml2testbug@yandex.com // 123456)
4. Check the mailbox and click the temporary access token link
5. Pay attention to the result
**Note:** The same behavior when resetting password via admin panel https://admin-staging.mindlogger.org/
**Video:**https://www.screencast.com/t/xi4QsqiIn
**Actual result:** Unable to reset password after clicking the temporary access token link. The user is navigated  to the web-staging site
**Video:** https://www.screencast.com/t/fQnxCVsr92h
**Expected result:** It should be possible to reset the password after clicking the temporary access token link.
**Environment:**
https://admin-staging.mindlogger.org Chrome/Firefox
ML v 0.14.13

**Comment by henry-overton** [comment]
I am not able to reproduce this issue on staging.

**Comment by sergeysemenuta** [comment]
This issue was fixed on the previous deployments. 
Closing this ticket out
