### ISSUE TITLE
[PROD] Unable to load users Token Data

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#510]
Steps to recreate: 
1. Log into the device on production (wavanauken+11@gmail..com/ abcd123) 
2. Take assessment 
3. Navigate to admin dashboard and login (wavanauken+10@gmail.com/ abcd123) 
4. View users of applet - Applet password; Abcd1234!
5. Try to view graph of user 
6. See results

Expect behavior: The owner, manager, reviewer should see a graph of response data from Tokens
Actual: Nothing is shown when clicking on a specifc user and if you do not click on a user and click on the graph button, a graph is shown

**Comment by Matchdev120** [comment]
@WorldImpex I tried a dozen of times to reproduce this issue on your account (wavanauken+10@gmail.com/ abcd123) but it works on my side. I think you didn't select the user (wavanauken+11@gmail..com/ abcd123) on user table when you`ve tested it.

**Comment by WorldImpex** [comment]
@Matchdev120 I think this must be specific to the computer. I just tried on my mac with a chrome browser and it worked as expected. I've also noticed on a chrome browser that the tab button stops working after some time. Idk if it is related. Do you think this is just a cache issue?

**Comment by Matchdev120** [comment]
@WorldImpex Just tried again and worked as we expected. I think it's just the cache issue. What do you think if we ask Sergey to test if again?

**Comment by WorldImpex** [comment]
@sergeysemenuta Could you look into this on production?

**Comment by sergeysemenuta** [comment]
I was not able to reproduce the issue. It works fine on my side.
Used to wavanauken+10@gmail.com, wavanauken+11@gmail.com accounts Also rechecked on my production accounts. Works as expected as well
![2020-11-17_18-40-01.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0b6eb0a3-595d-4859-a29b-2645db543779)
**Environment:**
https://admin.mindlogger.org/
Win 10 Chrome 86

cc: @WorldImpex
