### ISSUE TITLE
Some elements are displayed in French  on the calendar after logging in to the English version of the site 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#512]
**Steps to reproduce:**
1. Log in to the admin panel in French  https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Select an applet and navigate to the general calendar
3. Log out and log in to the English version 
4. Navigate to the general/individual calendar
5. Look at the page

**Actual result:** Some elements are displayed in French  on the calendar after logging in to the English version of the site 
**Video:** https://www.screencast.com/t/xAhfP9Uym
**Expected result:** All elements should be displayed in English on the calendar

**Environment:**
https://admin-staging.mindlogger.org/ 
Win 10 // Chrome 86

**Comment by natalia-muzyka** [comment]
This ticket is for the old design. A new design localization issues(on calendar) are here:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1243
