### ISSUE TITLE
Remove the "Schedule S", "4days X" options from the calendar filter

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#519]
The options "Schedule S", "4 days X" options are unnecessary. They should be removed from the calendar filter
![2020-11-19_13-46-55.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/622e652a-123f-4b64-9545-1dfa1cb9365a)

**Comment by Eugenia299** [comment]
Works as expected regarding the requirements on https://admin-new.mindlogger.org/
Win 10 // Chrome 87
