### ISSUE TITLE
Loalization.The items are not localized into the French language in the dropdown on the "Data Retention Settings" modal

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#537]
**Steps to reproduce:**
1. Log in to the admin panel in French as an owner/manager https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Select an applet and navigate to the 'users' page
3. Click the 'Paramètres de conservation des données' button
4. Observe the items in the dropdown list

**Actual result:** The items "Days, Weeks, Months, years" are not localized into the French language in the dropdown on the "Data Retention Settings" modal
**Expected result:**  The items "Days, Weeks, Months, years" are shown in the French language in the dropdown on the "Data Retention Settings" modal

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 Chrome 86

**Comment by WorldImpex** [comment]
Jours, Semaines, Mois, Années

**Comment by sergeysemenuta** [comment]
The issue is fixed

![2020-12-29_10-56-30.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5b781cc1-975e-4541-a418-93bd82bcfe2a)
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
