### ISSUE TITLE
The 'Upload Error' pop-up is shown after marking the 'skippable item' option and saving changes to the dashboard

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#539]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Go to edit any applet
3. Navigate to the Edit item modal
4. Mark the 'Skippable Item' option only
5. Save changes to the dashboard
6. Look at the result

**Actual result:** The 'Upload Error' pop-up is shown after marking the 'skippable item' option and saving changes to the dashboard
 **Video:**https://www.screencast.com/t/opL12EnNImvr
**Expected result:**  The 'Upload Received' pop-up is shown after marking the 'skippable item' option and saving changes to the dashboard

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 //Chrome 86

**Comment by sergeysemenuta** [comment]
The issue is reproduced
https://www.screencast.com/t/xWwElFCXsH
I've got  The 'Upload Error' pop-up  
Checked on staging https://admin-staging.mindlogger.org/
Win 10 // Chrome 86

**Comment by sergeysemenuta** [comment]
The issue is fixed partially. It is possible to update only one item with a skippable item but unable to updated several items within an activity.
Nothing happens after clicking the "Save to dashboard" button
**Video:** https://www.screencast.com/t/ylaaJaZ6uK

**Comment by Matchdev120** [comment]
@sergeysemenuta Updating several times works on my side. You should wait several seconds to be updated. Thanks.

**Comment by sergeysemenuta** [comment]
Fixed on https://admin-staging.mindlogger.org/ Win 10 // Chrome 86
