### ISSUE TITLE
Unable to view the  TokenLogger dashboard when the Activity contains different types of items

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#550]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snake ssqa@gmail.com // 123456)
2. Launch the applet builder 
3. Create an applet that contains token values, text box, slider, radio, date range etc. 
4. Create several activities
5. Upload the applet
6. Navigate to the users page
7. Observe the page

**Actual result:** Unable to view the  TokenLogger dashboard when the Activity contains different types of items. The button to view the dashboard is not displayed.
**Video:** https://www.screencast.com/t/ZZfCcbDlgX
**Expected result:** It should be possible to view the TokenLogger dashboard

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 86

**Comment by devbtech** [comment]
Please test on admin new design.

**Comment by sergeysemenuta** [comment]
The issue is fixed on https://admin-new.mindlogger.org/
Win 10 // Chrome 87

https://www.screencast.com/t/VHDj9m2nYr
