### ISSUE TITLE
[Redesign]All roles are assigned to the user after accepting an invitation to be a manager of an applet on the "MANAGERS" tab

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#559]
**Steps to reproduce:**
1. Log in to the  admin panel https://admin-new.mindlogger.org/ as an owner (snakessqa@gmail.com // 123456)
2. Select the TokenLogger Applet
3. Click the "View Users" button
4. Click the  "INVITATION" tab
5. Create an invitation to be a manager of the applet
6. Accept that invitation
7. Check the result on the "MANAGERS" tab

**Actual result:** The 'manager, coordinator, editor, reviewer' roles are shown on the "MANAGERS" tab
![2020-12-08_11-46-41.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ae4f7079-252a-41d4-8b3f-3cc9629ed859)
**Expected result:** Only the 'manager' role should be shown on the the "MANAGERS" tab

**Environment:**
https://admin-new.mindlogger.org/
Win 10 Chrome 85

**Comment by sergeysemenuta** [comment]
The manager of an applet is displayed in REVIEWERS, EDITORS, COORDINATORS  tabs
![2020-12-14_12-10-38.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/50c280fa-c052-491c-a262-fb62511f0538)
**Expected result:** The manager of an applet should be displayed on the 'MANAGERS' tab only

Checked on:
https://admin-new.mindlogger.org/
Win 10 // Chrome 86

**Comment by henry-overton** [comment]
I can not reproduce this issue.

**Comment by sergeysemenuta** [comment]
@prodev1101 Reproducible on my side https://www.screencast.com/t/TCljaZ4BWxK

**Comment by devbtech** [comment]
Please test on admin new design.

**Comment by sergeysemenuta** [comment]
Fixed on :
https://admin-new.mindlogger.org/
![2020-12-21_12-01-53.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/cf0765af-cf72-441b-858b-656a78074845)
