### ISSUE TITLE
[Redesign] The long applet names are gone outside of the buttons on the "View Data" modal window

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#569]
**Steps to reproduce:**
1. Log in to the ML Dashboard https://admin-new.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Select the "USERS" tab
3. Select the "111" user code (user is a member of applets with long names)
4. Click the 'View Data' button
5. Observe the modal window

Actual result: The long applet names are gone outside of the buttons on the "View Data" modal window
![2020-12-09_11-24-38.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5f4977af-6e20-49fe-a911-ec3b5ed213d4)
Expected result: The long applet names are shown within the  buttons on the "View Data" modal window

**Environment:**
https://admin-new.mindlogger.org/
Win 10 // Chrome 86

**Comment by devbtech** [comment]
Please test on admin new design.

**Comment by sergeysemenuta** [comment]
Fixed on:
https://admin-new.mindlogger.org/
Win 10 // Chrome 87
![2020-12-21_11-49-16.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/69e5afb5-b86d-4411-84e7-b9f6df961162)
