### ISSUE TITLE
Refactor to edit DBT & NIMH - Unable to update the applet name/description when editing an applet

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#570]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (e.g. leo@stage.com // 123456)
2. Upload NIMH, DBT, TL applet
3. Edit only Applet name/Description and  save to the dashboard
4. Pay attention to the result
**Actual result:** Unable to update the applet name/description when editing an applet. Upload error is shown
![2020-12-09_12-08-17.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/143f08db-6e0b-465e-aae9-6b9c18f15a03)
**Expected result:** It should be possible to update the applet name and description of an applet
**Note:** Works as expected on applets created via the builder

**Environment:**
Staging
Win 10 chrome 86

**Comment by sergeysemenuta** [comment]
The issue is reproduced.
![2020-12-16_11-08-43.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/787d1992-660c-4b7c-b438-509fe1d40df3)
![2020-12-16_11-11-28.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/aeefeaf7-04ca-41ca-9949-dcfe36e7336b)
![2020-12-16_11-15-43.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3cff993b-ad91-45f6-bf4d-66ccb66cd738)
Reproduced on:
https://admin-staging.mindlogger.org/
https://admin-new.mindlogger.org/
Win 10 // chrome 86

**Comment by WorldImpex** [comment]
Parsing Logic needs to be refactored in order to handle large applets like EMA, DBT per @jj105 & @Matchdev120

**Comment by sergeysemenuta** [comment]
The issue still Reproducible for EMA, DBT applets

EMA:
https://www.screencast.com/t/OIpROjQjXJN
BDT:
https://www.screencast.com/t/pxxL8Hko
Getting 500 error

Checked on:
https://admin-staging.mindlogger.org/
Wi 10 // Chrome 87

**Comment by sergeysemenuta** [comment]
The issue still reproducible
Video:
https://www.screencast.com/t/4nlBbecd
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87

**Comment by sergeysemenuta** [comment]
The issue is not reproduced if the user waits for about 30 seconds before editing 
https://www.screencast.com/t/TzSg48Wotzo

- The issue is reproduced when the user edits the applet immediately and saves changes to the dashboard
https://www.screencast.com/t/s5VnLy58NRq5

cc: @WorldImpex , @jj105

**Comment by jj105** [comment]
@sergeysemenuta -- will you please test this issue on applet builder redesign?

**Comment by sergeysemenuta** [comment]
@jj105  Checked on the https://admin-new.mindlogger.org/
There is a huge delay when navigating to the edit page for DBT /NIMH applet
https://www.screencast.com/t/ntlndUdHr

**Comment by WorldImpex** [comment]
@sergeysemenuta I think we can call this one closed as we will deal with the loading issues on [this ticket](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/772) in the next milestone
