### ISSUE TITLE
[Redesign] The "Refresh Complete" confirmation modal is not shown up after clicking the "YES" button on the 'Refresh response' modal

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#573]
**Preconditions:**
The user is reset his password and sent a request to refresh the response data via a notification on the app
**Steps to reproduce:**
1. Log in to Mindlogger Dashboard https://admin-new.mindlogger.org/ (snakessqa@gmail.com)
2. Select the TL applet and click the 'View Users' button
3. Click the "Refresh Response" button
4. Click the "YES" button
5. Look at the result

**Actual result:** The "Refresh Complete" confirmation modal is not shown up after clicking the "YES" button on the 'Refresh response' modal
**Expected result:** The "Refresh Complete" confirmation modal is shown up after clicking the "YES" button on the 'Refresh response' modal

**Environment:**
https://admin-new.mindlogger.org/
Win 10 chrome 86

**Comment by henry-overton** [comment]
I can not reproduce this issue today.

**Comment by sergeysemenuta** [comment]
It is not reproducible on https://admin-new.mindlogger.org/#
![2020-12-22_12-26-03.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/24243928-4263-4d1d-bffc-1e5231e668d1)
Win 10 //  Chrome 87
