### ISSUE TITLE
[Redesign] The "Refresh request" button is available for the reviewers on the  "USERS" tab

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#574]
**Preconditions:**
Users sent a request to refresh their response data via notifications 
**Steps to reproduce:**
1. Log in to the ML dashboard as a reviewer of TL applet (nick@ml.com // 123456) https://admin-new.mindlogger.org/
2. Switch to the "MLregression" account 
3. Click the "View Users" button 
4. Observe the page 

**Actual result:** The "Refresh request" button is available for the reviewers on the  "Users" tab
![2020-12-10_12-58-54.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6f147dc1-e33d-4ac7-b4de-3690fd3348c2)
**Expected result:** Only an owner/ a manager of the applet should be able to see the  "Refresh request" button and refresh the response data

**Environment:**
https://admin-new.mindlogger.org/
Win 10 //  Chrome 86

**Comment by henry-overton** [comment]
I can not reproduce this issue today.

**Comment by sergeysemenuta** [comment]
The issue is not reproduced anymore
![2020-12-18_10-45-48.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/07d9ff8b-d99a-44a7-81ab-dff9bcc8fc1d)
Closing this ticket out
