### ISSUE TITLE
[Redesign] The "Export user's data " button is available for the coordinator on the users page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#578]
**Steps to reproduce:**
1. Log in as a coordinator (e.g. ml5testbug@yandex.com // 123456) of an applet (e.g. NIMH) https://admin-new.mindlogger.org/
2. Switch to "MLregerssion" account
3. Select the HIMH applet and click the "View Calendar" button
4. Click the black button on the header
5. Click on your email 
6. Observe the buttons in the row

**Actual result:** The "Export user's data " button is available for the coordinator on the users page
**Video:** https://www.screencast.com/t/ygUJ6cCO
**![2020-12-11_13-21-47.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4169885d-46d6-4fdb-9531-1eeaf6892a16)**
**Expected result:** The "Export user's data " button is hidden for the coordinator on the users page

**Environment:**
https://admin-new.mindlogger.org/
Win 10 chrome 86

**Comment by henry-overton** [comment]
I can not reproduce this issue today.

**Comment by sergeysemenuta** [comment]
It is not reproducible anymore
