### ISSUE TITLE
Unable to view the token data on previous versions of the TL applet

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#589]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Create a TokenLogger applet and upload it
3. Log in to the app
4. Take the assessment
5. Edit the applet on admin (add some token value options)
6. Take the assessment on the app
7. Go to TL dashboard and see the data
8. Switch to the previous version of the applet
9. Look at the page

**Actual result:** Unable to view the token data on previous versions of the TL applet. The bars with data are not displayed.
**Video:** https://www.screencast.com/t/5LtBhOwVGDl
**Expected result:**  It should be possible to view the token data on previous versions of the TL applet

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 86

**Comment by henry-overton** [comment]
I can not reproduce this issue

**Comment by sergeysemenuta** [comment]
@prodev1101 
I couldn't reproduce as well on the https://admin-staging.mindlogger.org/
Closing this ticket out
