### ISSUE TITLE
The arrow overlaps the number of Tokens on the TokenLogger graph

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#591]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Select TL applet and navigate to the users page
3. Select a user and navigate to the TL dashboard
4. Observe the TokenLogger graph

**Actual result:** The arrow overlaps the number of Tokens on the TokenLogger graph
![2020-12-16_12-19-32.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3f880ef9-b4fa-4b6a-b3be-7580728e6ae4)
**Expected result:** The arrow doesn't overlap the number of Tokens on the TokenLogger graph
**Environment:**
https://admin-staging.mindlogger.org/
Win 10 chrome 86

**Comment by sergeysemenuta** [comment]
This issue is fixed on  https://admin-staging.mindlogger.org/ but reproduced on https://admin-new.mindlogger.org/#
![2020-12-22_10-40-18.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6f2fc9f6-2c43-4e33-a195-18e9afb799af)

cc: @WorldImpex

**Comment by devbtech** [comment]
@prodev1101 I talked with @jj105 but there's no merging into admin-new regarding this changes. Still this change are only available yet. I am moving this ticket back to Sprint Backlog

**Comment by sergeysemenuta** [comment]
The graph overlaps the arrow
![2021-01-04_13-55-13.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/712e8a60-3529-4c93-ad86-7deba7dace03)
Reproduced on:
https://admin-staging.mindlogger.org/

**Comment by WorldImpex** [comment]
Please remove the arrow @mtg137

**Comment by WorldImpex** [comment]
fixed
