### ISSUE TITLE
[Redesign]Several token screens/charts are shown per applet on the admin panel and app side

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#610]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-new.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Go to the  applet builder
3. Create an applet with several activities that contain token values
4. Invite a user to that applet and accept the invitation
5. Log in to the app (ml2testbug@yandex.com // 123456) and take activities for the newly created applet
6. Check results on the applet dashboard and on the data screen

**Actua result:** Several token screens are shown per applet on the admin and app side
**Video**:https://www.screencast.com/t/MmU6j7sikkx
**Expected result:** Only one token screen/chart should be shown on the admin panel and on the app on the data screen

**Environment:**
https://admin-new.mindlogger.org/
ML v 0.14.29
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3

**Comment by sergeysemenuta** [comment]
The token tab is empty on the admin panel (applet version 1.0.0) :
https://www.screencast.com/t/1W03uUPH
**Note:** The data is visible on the next version of the applet after editing the applet
![2021-01-29_12-31-50.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/db77ddb4-2518-4861-86a6-7e501c4bf6b8)
The token screen is duplicated on the data screen on the app for each activity
![2021-01-29_12-28-24.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/a8f378f3-7e2b-4b8b-9b9b-71e5e2e99db6)

**Account info:**
bughunterqa123@gmail.com // 123456
Applet password:Qwe123!!!
TokenApplet - edited applet
Test TL- the first version of the applet

Checked on:
https://admin-staging.mindlogger.org/
ML v 0.14.76 (298)
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3

**Comment by sergeysemenuta** [comment]
The issue is fixed on the admin panel.

The issue still reproducible on the app
 several duplicated token screens are shown for items and activities
![2021-02-09_13-58-11.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0c50c5a0-f721-40ce-b029-fec84c85e682)
ML v 0.14.77 (299)
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3

**Comment by sergeysemenuta** [comment]
Experiencing this issue again - The token tab is empty on the admin panel (applet version 1.0.0)
https://images.zenhubusercontent.com/189080374/07f1a87a-6cd8-40b6-9457-3fdf367b7404/2021_02_11_12_39_46.mp4

**Comment by natalia-muzyka** [comment]
Still reproducible on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124

**Comment by natalia-muzyka** [comment]
Close due to the updated TL.
