### ISSUE TITLE
[Redesign] The color of scheduled activity cards doesn't match the color in the activity section on the calendar

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#614]
**Steps to reproduce:**
1. Log in to the site https://admin-new.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Select any applet (e.g.EMA)
3. Schedule activities
4. Look at the calendar

**Actual result**:  The color of scheduled activity cards doesn't match the color in the activity section on the calendar
![2020-12-23_15-22-09.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/d87c6352-f952-4562-b6b3-6c82098557b0)
**Expected result:** Each scheduled activity should have a separate color on the calendar

**Environment:**
https://admin-new.mindlogger.org/
Win 10 /Chrome 87

**Comment by sergeysemenuta** [comment]
The issue is fixed partially.

- The color does not update when adding events without saving the schedule. It is updated and looks as expected after saving the schedule and reloading the page
Note: Scheduled events from past days should have white transparency
![2020-12-28_11-06-37.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c8a6a8a0-b24f-4dac-a366-f4188badbb27)

https://www.screencast.com/t/2HwtQ1hNgd2G


Checked on https://admin-new.mindlogger.org/
Win 10 // Chrome 87

**Comment by henry-overton** [comment]
Just fixed and pushed.

**Comment by sergeysemenuta** [comment]
Verified on https://admin-new.mindlogger.org/
![2020-12-29_10-48-31.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/2d1db819-d065-4e9d-9a23-6fdc8ae11f28)
Win 10//  Chrome 87
