### ISSUE TITLE
Update Blank Screen Text 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#634]
"If you've been invited to MindLogger as part of a team, use the people icon at the top right to navigate to that space"

![Screen Shot 2020-12-31 at 6.28.45 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ccbd94fe-3974-4582-ab48-f7c0eebadb67)

**Comment by sergeysemenuta** [comment]
The text is updated.
![2021-01-12_10-41-02.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e8ddac6a-704c-46a6-972c-8e43bfd0131e)
Verified on:
https://admin-staging.mindlogger.org/
Win10 //Chrome 87
