### ISSUE TITLE
Unable to update the applet that contains the images on Slider, radio, checkboxes questions

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#645]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (mikeowner@ml.com // 123456)
2. Go to applet builder and create an applet with uploading images to slider, radio, etc. (Header images, option images)
3. Upload the applet
4. Try to edit that applet and save changes to the dashboard
5. Look at the result

**Actual result:** Unable to update the applet that contains the images on Slider, radio, checkboxes questions. Nothing happens after clicking "SAVE TO DASHBOARD" button
**Video**:https://www.screencast.com/t/R191a9ThMr8Y
**Expected result:** It should be possible to update the applet that contains the images on Slider, radio, checkboxes questions

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87

**Comment by devbtech** [comment]
I figured the problem is only with slider item, for radio and checkbox it works fine. And it wasn't relevant to uploading images at all. This happened without images as well.

**Comment by sergeysemenuta** [comment]
@devbtech 
I've just checked. Unable to add a new radio item? new activity etc to the existing applet

https://www.screencast.com/t/HMxSqz6t0KZ
https://admin-staging.mindlogger.org/

**Comment by WorldImpex** [comment]
Stil reproducible

**Comment by WorldImpex** [comment]
Works as expected. There is an issue with editing a radio button into a checkbox but I have created a separate ticket that does not have to do with image upload https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/179
