### ISSUE TITLE
The popup "Image is added" is not shown up after removing an image and uploading the same image again

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#653]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (mikeowner@ml.com // 123456)
2. Create a new activity in an applet
3. Add the valid header image 
4. Remove the image
5. Add the same image again
6. Look at the result

**Actual result:** The popup "Image is added" is not shown up after removing an image and uploading the same image again
**Video:** https://www.screencast.com/t/ysmlJky7M
**Expected result:** The popup "Image is added" is shown up after removing an image and uploading the same image again

**Environment:**
https://admin-staging.mindlogger.org/
Win 10  //  Chrome 87

**Comment by WorldImpex** [comment]
fixed
