### ISSUE TITLE
Applet Circles should be a blue color

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#664]
![Screen Shot 2021-01-06 at 6.41.34 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e6a52a2a-1c80-409d-9f87-3233f3673fae)

**Comment by sergeysemenuta** [comment]
Verified on:https://admin-staging.mindlogger.org/
![2021-01-08_13-27-02.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/69fbc768-99f1-4b1a-89f6-b3ade429ca75)
