### ISSUE TITLE
Actions have color/ misaligned

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#665]
Update the buttons to not have color and are aligned with the row. 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f776da5a-e3c9-411d-9edc-a6fa364f2514)

**Comment by sergeysemenuta** [comment]
Verified on: https://admin-staging.mindlogger.org/
![2021-01-08_12-57-55.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/09a058ec-1ff8-4b7a-b7a4-6e7a0a267bd1)
