### ISSUE TITLE
Nothing happens after submitting the applet password on the applet password modal

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#667]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (mrn@ml.com//123456)
2. Move applets into the folder
3. Try to access the data wiz dashboard or export the applet data (applet password: Qwe123!!!)
4. Look at the result

**Actual result:** Nothing happens after submitting the applet password on the applet password modal
**Video:** https://www.screencast.com/t/KwEIVnaps
**Expected result:** User should be navigated to the data viz dashboard/ export the users's data after submitting the applet password

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 //Chrome 87

**Comment by WorldImpex** [comment]
fixed
