### ISSUE TITLE
Pinned applets are not moved to the top of the list

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#668]
**Preconditions:**
The applets are in the folder
The user is logged in on the site https://admin-staging.mindlogger.org/ (mrn@ml.com)
Steps to reproduce:
1. Pin the last applet in the list
2. Look at the result

**Actual result:** Pinned applets are not moved to the top of the list
![2021-01-06_15-06-02.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0eae25d4-7ff2-4606-9b6d-a7b339049115)
**Expected result:**  Pinned applets are moved to the top of the list
**Environment:**
https://admin-staging.mindlogger.org/
Win 10 //Crome 87

**Comment by WorldImpex** [comment]
applets no longer have pins so this is being closed
