### ISSUE TITLE
Clicking the "APPLETS" tab shows the MindLogger Welcome page for several seconds

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#669]
Steps to reproduce:
1.Log in to the admin panel https://admin-staging.mindlogger.org/ (mrn@ml.com // 123456)
2. Click the USERS tab
3. Click the APPLETS tab
4. Look at the result
Actual result: Clicking the "APPLETS" tab shows the MindLogger Welcome page for several seconds
https://www.screencast.com/t/vNVwLM26cDxB
Expected result: Clicking the "APPLETS" tab does not show the MindLogger Welcome page

Environment:
https://admin-staging.mindlogger.org/

**Comment by WorldImpex** [comment]
cannot reproduce. This seems very random but I have experienced it before

**Comment by sergeysemenuta** [comment]
@WorldImpex
 It is not reproduced anymore. That issue was reproducible after the first deployment related to the folders functionality

It can be closed
