### ISSUE TITLE
Negative Value Tokens cause Cumulative Value to go UP

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#680]
Steps to recreate: 
1. Take token assessment (wavanauken+11@gmail.com/ abcd123) 
2. Select a negative value token 
3. Check admin dashboard for data visualization 
4. See Results 

Expected: negative value is recorded and shown on token graph but does not affect the cumulative value 
Actual: Cumulative value is increased by a negative token value

![Screen Shot 2021-01-07 at 6.08.25 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/fc2b9695-2f5d-40ec-9a8f-d1644ccfe686)

**Comment by sergeysemenuta** [comment]
- Negative Value tokens cause the Total amount of tokens to go down
https://www.screencast.com/t/mpOvA1lG3j
Expected: Negative token values shouldn't influence the total amount of tokens. Only positive token values should be added to the total earned tokens

- The total amount of tokens are not visible on the data screen on the app after finishing the assessment  several times with negative values

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/2o0Kdxczo
Verified on:
Staging
MindLogger app v 0.14.53
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0
