### ISSUE TITLE
Deleting an applet does not visually work

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#681]
Steps to recreate: 
1. Log into admin-staging
2. Delete an applet 
3. See Results 

Expected: The applet is remove from list 
Actual: Applet appears to not be deleted until you refresh the page

**Comment by sergeysemenuta** [comment]
Verified on: https://admin-staging.mindlogger.org/
https://www.screencast.com/t/0JEVbJeBlT
