### ISSUE TITLE
Applet Search no longer works

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#684]
Steps to recreate: 
1. Log into admin - wavanauken+4@gmail.com/abcd123 
2. Search for an applet 
3. See results 

Expected: applets are only shown with the keywords entered. Change UI of field when entering text into search 
Actual: Nothing happens. Search is too close to tabs and new folder button

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Verified on:
https://admin-staging.mindlogger.org/

https://www.screencast.com/t/nbgjri72
