### ISSUE TITLE
"Latest Score" is spelled incorrectly 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#685]
Update text to show Latest and not Lastest 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6b3a14d9-b9d7-4265-be86-6831ccb6c5e2)

**Comment by sergeysemenuta** [comment]
![2021-01-11_15-03-07.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/df8195cc-b372-43c0-899d-14b564b8edb9)
Verified on:https://admin-staging.mindlogger.org/
Win 10 //Chrome 87

**Comment by sergeysemenuta** [comment]
Reproducible on the  Production environment
https://admin.mindlogger.org/
![2021-01-19_12-22-05.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/f55983e3-7ec9-4b07-aa4d-00c8dea50f1b)
Win 10 //Chrome 87

**Comment by sergeysemenuta** [comment]
Verified on:
https://admin-staging.mindlogger.org/
![2021-01-27_13-27-23.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4f001ad8-4f3e-41b4-8cef-2fe0094a8acd)
