### ISSUE TITLE
Add Logo to admin dashboard 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#688]
Add CMI logo to header right next to MindLogger Logo 

![CMI_white_h_logo.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/da4c9c2d-5824-49bb-b3aa-2750c8d4a323)![mindlogger-admin (2).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/a52633a1-7bc9-449a-8c00-75095b1fd6e1)

**Comment by Matchdev120** [comment]
@WorldImpex I assume that the CMI logo is in https://childmind.org/

**Comment by WorldImpex** [comment]
@Matchdev120 I attached the image to the top of the ticket but it is white image on a translucent background

**Comment by sergeysemenuta** [comment]
The Logo is added
![2021-01-09_10-42-58.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0b666743-0480-424e-8033-b5f7d046ff3f)
https://admin-staging.mindlogger.org/
