### ISSUE TITLE
Mock Data in Production  

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#690]
We need to create mock data in production so our stakeholders can see what the data visualization would look like over 1 month, 6 month or a year 

Please setup on demo@mindlogger.org/ abcd123 | Applet pass: Abcd1234! mock data daily for the last year for DBT Diary card and Healthy Brain Network

**Comment by WorldImpex** [comment]
1.  User does not see a years worth of data
2.  Data vis takes a while to load/ sometimes freezes when trying to view the EMA applet

**Comment by WorldImpex** [comment]
When moving the date range the second time, the graph only shows one month of data

**Comment by sergeysemenuta** [comment]
The data is displayed now
https://www.screencast.com/t/IZgyDT5klrEA
1. The data viz still takes a while to load
Checked on https://admin-staging.mindlogger.org/

**Comment by WorldImpex** [comment]
the account is shown in production now. Next release should make the time range work
