### ISSUE TITLE
TokenPrizes on TokenDashboard

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#694]
If the user spends tokens in-app, the cumulative total of tokens should go down and be down on the Token dashboard 

![Screen Shot 2021-01-10 at 7.23.53 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6b90fdae-4914-4f45-942a-90c14fb5ecfb)

Tokens are not reduced if the user purchases an item from TokenPrizes activity
wavanauken+4@gmail.com/ abcd123 | Applet Pass: Abcd1234!

**Comment by sergeysemenuta** [comment]
If the user spends tokens in-app, the cumulative total of tokens go down and  down on the Token dashboard as well
https://www.screencast.com/t/sQAuLqUg
Checked on:
Staging
Pixel 4XL//Android 11
iPhone XR // iOS 13.0
iPhone 11 Pro Max // iOS 13.5.1
ML v 0.14. 73
