### ISSUE TITLE
Email Template 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#699]
We need to create a template email that will be used for any communications from the MindLogger System 

![ML Email temp (2).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f8297fd6-56ac-4b90-87f4-41f6405d67f1)

1. Please update the emails we have today with the below design
2. All emails should start with Hello *User's First Name*! 
3. All emails should have the same header and footer
Header Image 
![mindlogger-logogram-blue.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8d5cd625-91ae-45de-aa21-3c81ff7664e6)
Footer Image
![1.jpeg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ff463f77-339b-489d-9cbf-b3e083b481fe) 
Footer Text: 
© [Child Mind Institute](https://childmind.org/?form=maindonate&gclid=CjwKCAiAo5qABhBdEiwAOtGmbjsgAEX_UtqPVg5rVCDQ48w3Q5GpTKYr_q7Cf42B0d_6BjhwPHdcixoCCfgQAvD_BwE) MATTER Lab 2021 
4. All emails should end with 
Thanks, 

The MindLogger Team

**Comment by sergeysemenuta** [comment]
Verified:
![2021-03-05_16-01-26.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4ba071ca-609c-450d-b76a-bc4e30151305)
