### ISSUE TITLE
The Applets on the dashboard is not loaded after accepting the invitation to be an owner of the applet

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#700]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Select any applet and transfer the ownership to the user (e.g. bughunterqa123@gmail.com)
4. Check the mailbox and accept the invitation
5. Log in to the admin panel as bughunterqa123@gmail.com // 123456
6. Pay attention to the result

**Actual result:** The data on the dashboard is not loaded after accepting the invitation to be an owner of the applet
**Video:** https://www.screencast.com/t/19MsVv4h
**Expected result:** The user should see the transferred applet and other data on his account

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87

**Comment by WorldImpex** [comment]
@sergeysemenuta Could you recheck this one? @Sshetty2 says he cannot reproduce it

**Comment by sergeysemenuta** [comment]
Rechecked the issue.It is not reproduced anymore.
Closing the issue out
https://admin-staging.mindlogger.org/
Win 10 // Chrome 88
