### ISSUE TITLE
Applet Folders should not be created by Default

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#702]
The user should not have applet folders created by default. Please remove

**Comment by sergeysemenuta** [comment]
The  "Responses", "Template folder..." folders are created by default. They shouldn't be created.
![2021-02-09_17-06-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/826e4ad6-84e3-4ba0-926a-0c238dd6fb5c)
Checked on:
https://admin-staging.mindlogger.org/
Win 10// Chrome 88

**Comment by sergeysemenuta** [comment]
Verified on:
https://admin-staging.mindlogger.org/
Win 10// Chrome 88
![2021-02-17_9-48-32.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/cd7b4d6d-e9f2-4d97-80ae-dc58c639707b)

**Comment by sergeysemenuta** [comment]
Reopening the issue
The "Responses" folder is created by default after taking an assessment by the user
Video:https://www.screencast.com/t/AARW9Cb6rL
https://admin-staging.mindlogger.org/
Win 10// Chrome 88

**Comment by sergeysemenuta** [comment]
The issue is fixed. Checked on the  existing and new accounts
https://admin-new.mindlogger.org/
Win 10 //Chrome 88

**Comment by sergeysemenuta** [comment]
Reopening this issue again.
Templates folder is shown up again after some time
Account : janet@ss.com // 123456
![2021-03-03_18-32-29.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/a3f877e8-68db-479a-8fed-503410552f85)

https://admin-new.mindlogger.org/
Win 10 //Chrome 88

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://admin-new.mindlogger.org/
Win 10 //Chrome 88
