### ISSUE TITLE
Admin Redesign Updates 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#703]
1. When a user hovers over applet, the actions should be shown. If the user selects the applet then the user should be taken to that applet's user page 
2. Add duplicate, delete and transfer ownership to the header icons when a user has made an applet selection 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/692bd56b-6904-47a4-8d44-c7264ef8bd26)
3. Hide user, manager, reviewer, etc tab when there are no roles assigned to users 
4. Remove reset selection functionality 
5. Update pager options to 10, 50, 100, and All 
6. Update text to say "*MRN Number* is a member of this applet's general schedule."
![Screen Shot 2021-01-11 at 1.20.09 PM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/46e5576e-ab84-4d62-8b38-3b7ce185ffc1)
7. Remove Reset Selection option

**Comment by sergeysemenuta** [comment]
1 Verified
2 Verified
4 Verified
5 Verified
6 Verified
7 Verified
![2021-01-27_15-49-52.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c7e9d1f4-4131-4a1e-9f00-f6bd946fa5b8)

https://admin-staging.mindlogger.org/
Chrome 87 // Win 10

Rased a separate issue [753](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/753) for point 3

Closing this ticket out
