### ISSUE TITLE
Timeout should be independent of Timed Activity

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#704]
A timeout and a Timed Activity should be able to be scheduled at the same time

**Comment by sergeysemenuta** [comment]
"Timeout check box" becomes unchecked after marking the "Timed activity" checkbox
**Video:** https://www.screencast.com/t/7xdFuq9pChG
**Note:** On the app side works as expected

Checked on: https://admin-staging.mindlogger.org/

**Comment by sergeysemenuta** [comment]
The issue in the comment above still reproduces
https://www.screencast.com/t/xeSQibXXw
Checked on: https://admin-staging.mindlogger.org/
Win 10 // Chrome 87

**Comment by sergeysemenuta** [comment]
The issue is reproducible

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2021-01-18_10-56-20.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/38256e06-99f4-490d-8697-39ae72bda4ae)
Win 10 // Chrome 87
https://admin-staging.mindlogger.org/
