### ISSUE TITLE
Updates to Calendar 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#706]
1. Remove "Event Details" text and replace with "Activity Access Options" 
2. Calendar in header's tooltip should be "View General Calendar" 
3. The Titles of the calendar are not updated correctly to show general vs individual 
![Screen Shot 2021-01-11 at 1.26.30 PM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5fded9d1-97d9-4b12-aeae-561b7e538cff)

**Comment by sergeysemenuta** [comment]
Looks as expected.
![2021-01-22_13-41-54.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0ef7c645-f7fd-4fb1-aacb-7e6776e96fb2)
Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
