### ISSUE TITLE
Updated Invitation Text 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#724]
1. Hello *user name*! 
2. Add quotes around "Applet Name" 
3. Add below Accept and Decline: 
" If you have any issues joining an applet or creating an account, please [contact us](https://gitreports.com/issue/ChildMindInstitute/MindLogger-bug-reports) and we can help you. 

Thanks,

The MindLogger Team"

**Comment by sergeysemenuta** [comment]
The invitation text is updated.
![2021-01-29_8-25-13.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c0d6313e-5a7f-4f42-8ab4-0cd328ef826d)
