### ISSUE TITLE
Calendar Options Reorg

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#728]
As a coordinator, I want to better understand the options I have when creating a schedule for an applet. 

Requirements
  * Always allow is on by default 
  * If turned off then more options are shown 
  * When turned off then the activity is now only available on the day that is scheduled and the coordinator must schedule days in the future for the activity to show up on the device/ the activity is no longer available in the future unscheduled 
  * Remove Available only on the scheduled day
  * Hide extended past due
  * Timeout = Access ends at 
  * Access Begins at = Start Time 
  * Repeats should default the start date of the tool to the day the user is on (ex: 01/19/2020) 
  * Move notifications to its own tab and update UI 
  * Notification window = Randomize notification 

![Calendar Options.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/10eb574b-713f-4b56-b1a3-e3bf710fd476)

**Comment by WorldImpex** [comment]
1. Always available should be turned on by default 
2. The default end time should be 11:59 PM 
![Screen Shot 2021-03-31 at 5.46.01 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b5ff902c-262e-4391-9c6f-d5a85af97dd4)
3. Schedule is not updated when creating an event

Steps to recreate 
1. Log into admin-staging (wavanauken+11@gmail.com/ abcd123) 
2. Create a general schedule for an applet (timetest)
3. Refresh mobile device 
4. See results 

Expected: 
1. When creating an event same day, the activity is updated to reflect that schedule in the future
![Screen Shot 2021-03-31 at 5.53.51 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9f848386-8293-421b-aa87-0ed61e9a5341)
2. When creating an event a day or more into the future, the event is no longer shown on the device on days it is not scheduled 
![Screen Shot 2021-03-31 at 5.53.12 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/1c1a039b-b661-4b77-b889-241becf19868)

Actual: Nothing happens

**Comment by WorldImpex** [comment]
@sergeysemenuta Please QA, I have on my end but I can't do repeats as I need to QA notifications. I will try to setup repeats later this weekend if Notifications seem to be stable

**Comment by sergeysemenuta** [comment]
Works as expected
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 89
