### ISSUE TITLE
Data Viz Updates

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#729]
1. Remove "Showing data from" text 
2. Show version number on each side of version bar (ex: 0.01 | 0.02) on graphs 
3. Remove "Show Version Changes" on/off checkbox and always show version bars 
4. Show "Version text in line with the drop-down
5. Show summary line in line with the response option lines
6. Update text when Token data is not available to " No token data available for this activity" 
7. Applets that have not collected any data yet from the user should read "No data available to show yet" 
8. If there is only one activity, remove the expand all option

**Comment by sergeysemenuta** [comment]
1. Remove "Showing data from" text- **failed**
 

- "Showing data from" text is shown

![2021-01-21_14-22-58.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/70ea5949-a2af-49c8-8b91-6e33c53dec94)
7.Applets that have not collected any data yet from the user should read "No data available to show yet" - **failed**
![2021-01-21_14-28-34.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/298d66ea-7ccf-431d-b0aa-311075723a0e)
8. If there is only one activity, remove the expand all option - **failed**
![2021-01-21_14-31-45.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4d5e45cd-5060-44b2-a45a-663f5470a328)
3. Remove "Show Version Changes" on/off checkbox and always show version bars- **failed**
![2021-01-21_14-39-35.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5be519cb-8c04-4751-8b52-f128bd0ccb14)

**Comment by binaryExDev** [comment]
@sergeysemenuta My PR is not deployed yet so it would be better to test it after that.

**Comment by sergeysemenuta** [comment]
@binaryExDev Thanks for the update

**Comment by sergeysemenuta** [comment]
Looks as expected.
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
https://www.screencast.com/t/q7hOg9XDi
