### ISSUE TITLE
Unable to Delete Schedule Event for Activity 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#73]
Expected Results: Able to delete an activity that is setup
Actual Results: Unable to delete an activity after it is created 

![mindlogger-admin (3).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/209dcf15-e938-4873-95b9-173527ae99d2)

**Comment by Eden2016** [comment]
I added a couple of buttons to handle the delete feature on a calendar Event but I can’t find how to handle that event once it is emitted using the library `dayspan-vuetify-2`(this is what is being used in the project for the calendar). I didn’t find anywhere where these actions are handled in the project. The branch with the changes is here: https://github.com/ChildMindInstitute/mindlogger-admin/tree/unable-to-delete-event-for-activity-%2373

**Comment by henryrossiter** [comment]
Why was this reopened? I believe it is fixed.

**Comment by WorldImpex** [comment]
@henryrossiter - When you merge always send it to ready for deployment and then it will be moved to QA so the QA person knows to test it. @ProNinoGit120 has some changes he wanted to update so that is why it is in progress again

**Comment by WorldImpex** [comment]
fixed 

![AwesomeScreenshot-2020-1-30-1580395309328](https://user-images.githubusercontent.com/22243307/73459448-e2cacc80-4344-11ea-858a-bb203c104d9b.gif)
