### ISSUE TITLE
[Production] Legacy Accounts with Existing Applets cannot navigate with View Calendar or Users

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#730]
Steps to recreate: 
1. Log into legacy account on production (wavanauken+1@gmail.com/ abcd123) 
2. Try to view the users or calendar for an applet 
3. See Results 

Expected: Any applet that is checked will navigate 
Actual: Nothing happens sometimes clicking those buttons 

![mindlogger-admin.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c1bdfbd7-02e9-41e0-851e-0fadb9eb100d)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/fbrTKt1sO
Checked the wavanauken+1@gmail.com account, newowners@prod.com
https://admin.mindlogger.org/
Win 10 // Chrome 87
