### ISSUE TITLE
Unable to access the applet builder on some accounts

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#744]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/
_Accounts:_ 
snakessqa@gmail.com // 123456
mrn@ml.com // 123456
garry@ml.com // 123456
2. Go to the applet builder
3. Look at the result

**Actual result:** Unable to access the applet builder on some accounts. the empty page is shown with the text For more information on ReproNim, please visit the official <a href='https://github.com/ReproNim/reproschema'>Github</a> repository.
![2021-01-25_12-30-33.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/be8fc96e-049c-4225-833d-706df6fd7528)
**Expected result:** It should be possible to navigate to the applet builder

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87

**Comment by WorldImpex** [comment]
When accessing applet builder I did the below steps and then the button disappeared: 
1. Logged into snakessqa@gmail.com
2. Clicked the + button and selected the applet builder
3. Saw code and refreshed my screen. Then the builder was shown. 
4. Went back to homepage 
5. Dashboard was gone

**Comment by sergeysemenuta** [comment]
The issue is fixed
https://admin-staging.mindlogger.org/
Chrome 88 // Win 10
