### ISSUE TITLE
Public Link that does not require a login

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#751]
As a coordinator, I want to invite a user and not require the user to create an account so that I can collect response data from users without them needing an account 

Requirements
Based on the implementation of [843](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/843), we need to enhance their feature. By default, their feature will require the user to create an account to accept the invitation. 
Requirements
- We need to create a toggled option on admin that does not require the user to create an account. 
- The applet + activities should show on webapp and not require a user to sign in to action the applet/ activities 
- Users that are already signed into an account and action an activity should still be processed the same way a user without an account is processed 
- The original implementation creates a 'fake/ auto generated' Secret ID. We would continue using that component with this feature 
- Data still needs to be securely transferred and stored between mobile, webapp and admin panel

**Comment by natalia-muzyka** [comment]
The issues for the public link that doesn't require a login:

1) The blank page is displayed for the logged-in user after opening the public link
https://www.screencast.com/t/EYNzXdWRCV
Question: The expected result is that the user is automatically logged out after opening the public link?

2) Data aren't displayed on the admin panel after completing the assessment (already [reported](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-website/78))

3) The blank page is displayed for the non-authorized user after an attempt to get access to the deleted public link 
https://www.screencast.com/t/ZcsSWj5E

**Comment by WorldImpex** [comment]
1. Land user on applet detail page (that shows activities)
3. Show Error "This assessment is no longer accepting respondents."

**Comment by natalia-muzyka** [comment]
1) The applet detail page is displayed and the user is still authorized. After completing the activity and submitting responses the user's data aren't shown on the admin panel side. 
As I understand the user shouldn't be authorized after opening this link and complete the activity as a not logged-in user.
https://www.screencast.com/t/dEln3DJuSzl

3) Still reproducible. The blank page is displayed for logged-in and not logged-in users after an attempt to get access to the deleted public link:
https://www.screencast.com/t/PnYpBOICm

**New issues:**

4) The blank page is displayed after opening the activity via the public link(that doesn't require log in) by a non-logged in user:
https://www.screencast.com/t/tcSvvo90Kj

https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
geria2.test@gmail.com	// McgzF127
Windows 10 // Chrome 92.0.4515.107 
Applet: webapp test(1)
Applet password	Qwe123!!!

**Comment by jj105** [comment]
@natalia-muzyka regarding 1), I had discussion with @WorldImpex - if user clicks public link then he won't be auto-logout but his response will be saved under scope of **Fake** user for that applet

I'll fix it and create a PR

**Comment by natalia-muzyka** [comment]
**Fixed:**
Non-logged in user is able to take an assessment with the "Response Data Identifier". Data are stored on the admin panel under the auto-generated Fake user. 
https://www.screencast.com/t/U7ohThWJe

After an attempt to get access to the deleted public link the "This assessment is no longer accepting respondents." message is shown for logged-in and non-logged-in user.
https://www.screencast.com/t/LS8hvepXGhh

**Still reproducible:**
Logged-in user: The applet detail page is displayed and the user is still authorized (as expected). 
After completing the activity and submitting responses the user's data aren't shown on the admin panel side (under the scope of Fake user).
https://www.screencast.com/t/FcLlqwPFqyK

https://admin-staging.mindlogger.org/
geria2.test@gmail.com	// McgzF127
applet: webapp sync / text input (user secret id)
Applet password:	Qwe123!!!

**Comment by WorldImpex** [comment]
@jj105 Instead of using "fake", please change it to "Guest Account Submission"

**Comment by natalia-muzyka** [comment]
**Fixed:**
After completing the activity and submitting responses the logged-in user's data aren't shown on the admin panel side (under the scope of Fake user).
Additional info: Data from the logged-in users are collected together under the "Guest Account Submission" account but couldn't be filtered (expected behavior, discussed with Wil)
video: https://www.screencast.com/t/uYIA4kj6

applet / activity: 
ml sync test / activity without secret user id

**Reproducible issue:**
Data from non-logged-in user aren't displayed on the DataViz after taking an assessment with a secret user id (though the response time is displayed on the "Guest Account Submission" account). 
Not reproducible for logged-in users.
Reproduces only if this is the first response in this activity (there are no responses from logged-in users)
Not reproducible for an activity that doesn't contain user secret id item.

Activity with user secret id (non-logged in user):
video: https://www.screencast.com/t/7ULrwTt1S

Activity without user secret id (non-logged in user):
https://www.screencast.com/t/7ULrwTt1S

applet / activity: 
ml sync test / activity with user id

https://admin-staging.mindlogger.org/
account:
johndoeregress@protonmail.com	// 12345678
applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
New issues:
[The secret id selector [object object] is displayed on DataViz after submitting the response from webapp via public link that doesn't require a log in]
(https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1177)
[The "Guest Account Submission" data are missing in the exported csv #1178
](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1178)

Other than that functionality works as expected and follows the requirements.

Verified on:
Win 10 // Chrome 92.0.4515.107

**Comment by natalia-muzyka** [comment]
The issues above are fixed.
The "public link" functionality works as expected and follows the requirements.
