### ISSUE TITLE
The "USERS/EDITORS/COORDINATORS" tabs are not hidden when there are no roles assigned to users

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#753]
**Preconditions:**
There are no users/user roles  assigned to an applet
**Steps to reproduce:**
1. Log in to the admin panel https://admin.mindlogger.org/ (hide@ml.com // 123456)
2. Observe the tabs 

**Actual result:** The "USERS/EDITORS/COORDINATORS" tabs are not hidden when there are no roles assigned to users
Video:https://www.screencast.com/t/J4qGn9Ph
**Expected result:** The "USERS/EDITORS/COORDINATORS" tabs are hidden when there are no roles assigned to users

**Environment:**
Staging
https://admin-staging.mindlogger.org/
Win 10 //  Chrome 87

**Comment by WorldImpex** [comment]
@binaryExDev The applet tab is being hidden. Could you unhide that one?

**Comment by binaryExDev** [comment]
@WorldImpex Ok, I'll fix it.

**Comment by sergeysemenuta** [comment]
The issue is fixed partially. It's hidden on the main dashboard but tabs are not hidden after navigating to the particular applet dashboard.
video: https://www.screencast.com/t/z4FOoafRmWdj
![2021-02-09_14-17-16.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0979327c-f0d5-48e0-ad3a-b157418080ae)

**Comment by sergeysemenuta** [comment]
The issue is fixed partially.
The users, coordinators, reviewers, editors tabs are not shown up after assigning these roles (reviewer/user/coordinator/editor) within the applet dashboard.
![2021-02-12_12-35-49.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/73153ceb-d69d-4d2a-81bf-5d29794fe204)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 88
