### ISSUE TITLE
Activies on Calendar do not show on Day/Week

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#77]
Expected Results: When user inputs activities on month screen of the calendar, the show up on the other filtered tabs (day, week)
Actual Results: Activites do not show on day or week filter 

 ![ezgif-7-f16afe6c1afd.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/abdc8c1f-fd46-4213-975e-81889fa104a4)

**Comment by WorldImpex** [comment]
Might be related to https://github.com/ChildMindInstitute/mindlogger-app/issues/625#issuecomment-573172730 as save might be my issue @shnizzedy Can you try creating a new notification and saving it?

**Comment by shnizzedy** [comment]
@WorldImpex I can create notifications, but only for one applet per database at the moment: 

> For me it seems like it's always the activities from first applet (ie, the one farthest to the left on the "applet" step) that are available to edit on the "schedule" step regardless of which applet is selected

_Originally posted by @shnizzedy in https://github.com/ChildMindInstitute/mindlogger-admin/issues/71#issuecomment-573194785_
