### ISSUE TITLE
Assign users to Reviewers in a list

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#771]
As a manager, I want to assign a group of users to a reviewer so that I can more quickly set up an account. 

Requirements 
* During Invitation creation and editing a reviewer's permissions, there should be an option to select from a list 
* Allow the reviewer to still use the text entry field in list view 
* Allow the reviewer to select one or more users at a time in list view 
* Allow the reviewer to select all for a reviewer as well
** If select all is deselected then the manager should be able to remove all users from the reviwer's account 

![Reviewer Select All.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4f122121-f626-4f72-b246-643ec8ac2c3f)

**Comment by sergeysemenuta** [comment]
Works as expected according to Requirements. Checked the owner, manager, coordinator roles with assigning users to the reviewer and updating organizer roles.

Video:https://www.screencast.com/t/3g2a0UiRVNrd
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90
