### ISSUE TITLE
Pressing the "Enter" key on the "Add Header Image" doesn't open the filing system

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#789]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Go to the applet builder
3. Select the input type (e.g. drawing)
4. Fill in the form
5. Tab to the "Add Header Image" box 
6. Tab to the "YOUR COMPUTER" button
7. Press the 'Enter' key from the keyboard
8. Look at the result

**Actual result:** Pressing the "Enter" key on the "Add Header Image" doesn't open the filing system
![2021-02-10_13-46-12.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/56bd5f5b-7260-4bcc-9124-f832d354715b)
**Expected result:** Pressing the "Enter" key on the "Add Header Image"  opens the filing system

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrom 88

**Comment by WorldImpex** [comment]
Reproducible on new design?

**Comment by sergeysemenuta** [comment]
@WorldImpex 
Reproducible on the new design as well
https://www.screencast.com/t/fut4E9A3JR
https://admin-new.mindlogger.org/

**Comment by sergeysemenuta** [comment]
The issue still reproduces
https://admin-new.mindlogger.org/    Chrome 88
![2021-03-01_11-29-51.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/95c8e441-004e-4698-920d-b7edd324337a)

**Comment by sergeysemenuta** [comment]
The issue is fixed
https://admin-new.mindlogger.org/ Chrome 88
