### ISSUE TITLE
[ PROD ] Unable to save Individual Schedules - Healthy Brain Network (NIMH Content) Applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#791]
Steps to recreate
1. Log into admin 
2. Set an individual schedule for a user (activity + a start time) 
3. See Results 

Expected: Saves correctly 
Actual: Shows a 500 error

If I clear the schedule and try again, 500 error is removed and event posts as expected

![Screen Shot 2021-02-10 at 5.57.23 PM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ff837a47-137a-40d2-ada4-19765d00c181)

**Comment by jj105** [comment]
@WorldImpex @sergeysemenuta 

Here's detailed step to reproduce issue which is discovered after checking error log file in the server.

1 - log in admin panel and select any applet
2 - create event card with start time, and turn on notification option.
3 - insert "start notification at" field
4 - click "+" button to insert one more notification, but leave "start notification at" for second notification as empty.
5 - click save button.
6 - 500 error is shown.

I was able to reproduce it on staging and production admin panel.

**Comment by jj105** [comment]
![2](https://user-images.githubusercontent.com/49569908/107602376-ebc9cb80-6c31-11eb-8175-fc5a450a858e.png)
![1](https://user-images.githubusercontent.com/49569908/107602378-ecfaf880-6c31-11eb-80dd-e003308e2988.png)

**Comment by sergeysemenuta** [comment]
Reproduced this issue as well.
Here is an old issue might be related to the current one [227](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/227)

**Comment by hotavocado** [comment]
I'm not convinced this is what caused the problem. For the past week RAs and I have added individual schedules to over 10 users following the exact same steps: https://docs.google.com/document/d/1FGBETbMleEyOWA4l97TXr5ArB0ZOtKqBXYxbjff7gkc/edit?usp=sharing

Yesterday evening, we started to encounter this problem, but only in the HBN EMA applet. I tried saving individual schedules in other applets and it worked fine. 

I contacted Wil about this and we started to experiment. Wil found we could get around this error after first adding a schedule, clicking save button, getting the 500 error, clearing the schedule, setting a schedule the second time, and it will save properly. 

After this, the RA and I attempted to clear and add individual schedule a second time. The RA was doing it for user 9916, I was doing it for user 11514. Both individual schedules saved, no 500 error.

However after I did this, I went back on the admin panel and **every individual schedule we set for users in the past was cleared**.  The only users that had individual schedules were the ones we just set (users 9916 and 11514). This is a very scary problem, hopefully we can get to the bottom of this. 
![Screen Shot 2021-02-10 at 6 25 42 PM](https://user-images.githubusercontent.com/24463939/107634486-92649b00-6c37-11eb-8236-abd6d14fc33c.png)

As a temporary solution, I have put individual schedules on pause and am using general schedule for all participants. They will no longer have custom start and end dates, but we communicate those dates to them during the onboarding.

**Comment by hotavocado** [comment]
To recap: right now I can go in the HBN EMA applet and add an individual schedule to any user, it will save without problems. This issue is no longer reproducible. 

However, all the individual schedules we set for different users were cleared all at once. This is the real problem.

**Comment by WorldImpex** [comment]
@hotavocado 
1. All schedules for the EMA applet were cleared when the clear button was actioned. That is why all schedules are gone now 
2. If 1 individual schedule has an empty notification then all individual schedules experience this 500 error. So at some point in creating a schedule a RA by accidentally went to add a second notification but left it blank. This caused a 500 error and all other individual schedules inherited the problem. 

Let me know if you still disagree or have any follow up

**Comment by hotavocado** [comment]
@WorldImpex 

Awesome, I've confirmed both from my end. It looks like the issue I'm concerned about then is that individual schedules are cleared from all users when someone clears the individual schedule for any one user. This definitely shouldn't be the intended behavior! Would you be able to make a ticket for that?

**Comment by WorldImpex** [comment]
Yup all set - https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/281
