### ISSUE TITLE
[Applet Builder Redesign] Unable to remove 'Conditionals' from an existing applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#792]
**Preconditions:**
The applet with conditional logic is uploaded to the dashboard
**Steps to reproduce:**
1.Log in to the https://admin-new.mindlogger.org/ (rick@ss.com // 123456)
2. Select the "Conditional Logic" applet
3. Click the "Conditional Logic" button
4. Delete "Conditionals"
5. And save changes to the dashboard
6. Look at the result

**Actual result:** Unable to remove 'Conditionals' from an existing applet. Conditionals are not removed.
**Video:** https://www.screencast.com/t/tZyPh1rYXd
**Expected result:** User should see the popup about successfully updated applet after saving to the dashboard and conditionals should be removed
**Environment:**
https://admin-new.mindlogger.org/
https://api-new.mindlogger.org/api/v1
Chrome 88 // Win 10

**Comment by sergeysemenuta** [comment]
@WorldImpex This issue had been mentioned here [281](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/281)

**Comment by sergeysemenuta** [comment]
Still can't delete conditionals
https://www.screencast.com/t/JhosI4VJXbg
Upload error pop-up is shown
![2021-03-03_13-36-03.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5df3b202-5e6f-4bd7-bcda-59ea78df0a26)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/WkactlrcHk
Environment:
https://admin-new.mindlogger.org/
Chrome 88 // Win 10
