### ISSUE TITLE
Shuffle Button Hidden when Creating an Activity

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#80]
Expected Behavior: User can see the option to use the shuffle button 
Actual Behavior: The shuffle button does not have anything around it to let the user know what its function is 

![mindlogger-admin (10).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/06353d98-868e-4fad-bcd4-7d4078bc1256)

**Comment by henryrossiter** [comment]
This is a unique situation. The shuffle switch renders as expected in development environments but disappears when the project is built for production.

**Comment by WorldImpex** [comment]
This is just a development tool as pointed out by @henryrossiter

**Comment by henryrossiter** [comment]
@WorldImpex This should still be open- the shuffle switch is still not visible in production environments. I commented above just to document what I had learned so far!
