### ISSUE TITLE
Reduce Background line thickness

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#809]
Reduce the background line thickness of the graph and color them grey and increase the plot like thickness

![Screen Shot 2021-02-15 at 5.16.18 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b8b02cf8-86d3-4eb4-9185-9460b5c0601f)

**Comment by sergeysemenuta** [comment]
The background line thickness is reduced
![2021-02-18_14-18-53.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0cd73974-f96b-4fa4-bfcd-b4ec99123837)
Verified on:
https://admin-staging.mindlogger.org/
