### ISSUE TITLE
Applet title and description not parsing correctly

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#81]
![Screen Shot 2020-01-13 at 12 02 04 PM](https://user-images.githubusercontent.com/24463939/72275960-f7952980-35fc-11ea-9ca7-1a11bc710232.png)

**Comment by shnizzedy** [comment]
duplicate of https://github.com/ChildMindInstitute/mindlogger-app/issues/648

**Comment by WorldImpex** [comment]
completed in 648
