### ISSUE TITLE
Text does not make sense for applet 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#82]
Expected Results: Text displayed would describe the applet presently available
Actual Results: The text does not give the user any direction as to what it is 

![mindlogger-admin](https://user-images.githubusercontent.com/22243307/72103063-6705d300-32f6-11ea-81cf-5e4217527abc.png)

**Comment by hotavocado** [comment]
![Screen Shot 2020-01-13 at 1 25 48 PM](https://user-images.githubusercontent.com/24463939/72281374-688e0e80-3608-11ea-823f-5bac3eaa9301.png)

~It looks likes applets posted before this issue (https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/270) got resolved are still parsing fine.~

Nevermind, looks like it was just the cache.

![Screen Shot 2020-01-13 at 1 55 54 PM](https://user-images.githubusercontent.com/24463939/72283292-75146600-360c-11ea-8a19-2fc19681c254.png)
