### ISSUE TITLE
The applet version is updated automatically without editing an applet after navigating to the edit applet page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#820]
**Steps to reproduce**:
1. Log in to the admin panel
2. Upload the DBT or any other applet from Git-Hub
3. Go to edit this applet
4. Wait for about 30 seconds
5. Check the applet version

**Actual result:** The applet version is updated automatically without editing an applet after navigating to the edit applet page
**Note:** This issue is actual for the applets uploaded from the Git-Hub as DBT, NIMH etc
**Video:** https://www.screencast.com/t/kAdjHvIBYu
**Expected result:** The applet version is not changed automatically without editing an applet after navigating to the edit applet page
**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 88

**Comment by jj105** [comment]
@sergeysemenuta  -- will you please test this one on applet builder redesign?
the bugfix is included there.

**Comment by sergeysemenuta** [comment]
The issue is reproduced on the https://admin-new.mindlogger.org/ site as well
After navigating to the edit applet the version shows (0.0.2) it should show (0.0.1)
https://www.screencast.com/t/Wtp6pjEbkz

**Comment by WorldImpex** [comment]
@sergeysemenuta Per @jj105 , the feature here is that a newly uploaded applet from github does a version increase because we have to convert it form github to use the applet builder so that is why the 'ghost' version change happens without actually saving. I think this is a feature, would you agree?

**Comment by sergeysemenuta** [comment]
@jj105 If the info above is true we can close this issue.
