### ISSUE TITLE
Update Blank Admin Dashboard screen Text

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#831]
Welcome to MindLogger!
This is your own space to create and manage your own applets.
Let's get started by creating a new applet or uploading one.
	CLICK HERE
If you've been invited to MindLogger as part of a team, the people icon at the top right will take you to the team's applets.

**Comment by sergeysemenuta** [comment]
The blank admin dashboard is updated.
![2021-03-02_13-42-55.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/79f7b3dd-0001-4d61-a847-7791736a6b37)
https://admin-new.mindlogger.org/
Win 10 // Chrome 88
