### ISSUE TITLE
Add graph for 'time' responses to data viz dashboard (Affects current pilot study)

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#840]
Currently time responses cannot be viewed on the data viz dashboard. In the current pilot, clinicians need to be able to view the 'time' responses of patients using the app.

Create a line graph like the one for slider response, the y axis will be time in HH:MM. Higher = later, lower = earlier.
y axis auto-adjusts to range of values
x axis will be date the assessment was completed (exactly like the slider response graph)

![image (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/310f7317-c69b-4bc9-b7cb-1c809a680393)

**Comment by sergeysemenuta** [comment]
Works as expected for DBT EMA applet

![2021-03-29_13-09-17.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/fb541eec-f896-4b73-bd90-835743d67965)

- It doesn't work for applet created via builder:

The graph and responses  are not shown for time range items
![2021-03-29_14-00-02.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3c91ca8d-d162-40f8-ba7a-683b29d5dc1d)
The UI of the graph is overlapped when changing the date range
![2021-03-29_18-13-38.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/21e61c1f-ad91-4a8e-9892-6f188a2c379f)
https://admin-staging.mindlogger.org/
Win 10 // Chrome 89

**Comment by WorldImpex** [comment]
Works as expected for time widget 

I do not think time range is scope for this ticket
