### ISSUE TITLE
Reverse y axis for slider response graph in data viz dashboard (Affects current pilot study)

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#841]
In the current slider response graph in the admin panel, lower numbers are higher on the y axis and higher numbers are lower. A clinician pointed out that this was confusing.
<img width="1058" alt="Screen Shot 2021-03-04 at 5 28 07 PM" src="https://user-images.githubusercontent.com/24463939/110039379-1e398680-7d0f-11eb-8b17-bcf46d31693f.png">

Can we reverse the y axis, so that movement in the line plot intuitively maps on to increase/decrease in the value of a response?

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2021-03-15_10-51-28.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/959f5f48-ff4b-4612-91fc-53063875fffc)
https://admin-staging.mindlogger.org/
Win 10 // Chrome 88
