### ISSUE TITLE
Users can invite themselves to an applet ('open invite link')

### ISSUE THREAD

**Issue by BarrySunderland** [ChildMindInstitute/mindlogger-admin-OLD-Vue#843]
To avoid the need to create invitations for each individual user (example for citizen science), a simple 'self sign-up page' could be added that allows logged-in users to input their email address & name, and invite themselves to an applet.

Would like to get maintainers thoughts on the proposed implementation below & answers to questions at the bottom. If the implementation is reasonably clear and agreeable, I can start working on a Pull Request.

**suggested implementation:**
1. use the existing  api endpoint used in the [_getAppletInvitation_ ](https://github.com/ChildMindInstitute/mindlogger-admin/blob/12c783d02a35f83665331c1da3febf8e76a60d5c/src/Components/Utils/api/api.vue#L311) method:

2. make a new sign-up user form component (similar to [CreateUserForm.vue](https://github.com/ChildMindInstitute/mindlogger-admin/blob/master/src/Components/Authentication/CreateUserForm.vue)) 

_fields provided by users:_
  - firstName  
  - lastName   
  - email  
  - lang (default to en)
  
_autofilled fields (not visible to user)_
  - role=user
  - MRN (generate a random guid)
  - token (created after signing in)  

3. new vue router url  (or url that accepts a query param)
for example:  
  ```js 
  {
  path: "/applet/:appletId/signup",
  name: "SelfSignUp",
  component: SelfSignUp,
  meta: {
    requiresAuth: true,
}
```
If users are not already logged in or do not have an account, the latest version of the admin repo already has a redirect to the login in page with a next url (so users will be brought to this new applet self sign-up page after log in).

**nice-to-have features:**
4. header on the sign up page that displays name of survey
5. button or field in admin panel that displays the invite url
6. possibly some backend setting for admins to decide if an applet accepts open invites (but applet id's are already a very long uid so this could possibly be added later)

**questions** 
Q1. should the new sign up form exist in the admin site or the web.mindlogger site?
Q2.  if creating adding the form to the frontend, will the web.mindlogger token be valid for the _getAppletInvitation_ method?

**Comment by binarybottle** [comment]
Thank you, @BarrySunderland! This is a much-anticipated feature that would make citizen science projects possible through MindLogger, so I am excited to see a start on this. To answer your 1st question, I think that web.mindlogger makes more sense.  @WorldImpex -- Do you see any drawbacks to this approach? Can Barry get a start on this?

**Comment by WorldImpex** [comment]
Thanks for putting this together @BarrySunderland 

Over the next 1-2 months, we will be rebuilding our webapp in react so this component would need to be built using that library. This will be a brand new build so I think it might be best to wait until the basics are set up. The public link should be a webapp invitation. It would make more sense to handle all invitation-related functions for a user in the same experience. Especially if the user is to then take the assessment from a browser.

I would also say that is a must-have to allow the admin to turn on/ off this public URL for security purposes. When turned on, the URL can be copied and distributed outside of MindLogger. If we do not have a way to turn this off then bad actors can potentially spam any applet

I think the original approach to this feature was to create some wireframes. Do you have that to share? I think it would be best to visually understand how a user on admin and a user on webapp would process through this workflow. The below are just questions off the top of my head but as you go through the journeys I am 100% sure other situations arise that will need to be solved

What admin users are allowed to create this invitation? 
What happens when the URL is turned off? Do the users that have already joined the applet get to stay on as users? What does the screen show to a user that has not 'accepted' the invitation? 

In terms of your development approach, @binarybottle  would you like to use development time to have one of the team members review this approach? I cannot from an engineering perspective comment on if this will work but I think there needs to be a deeper dive on UX/UI and how this functions.

**Comment by BarrySunderland** [comment]
Thanks for your thoughts and some context around developments.

I've made some new wireframes to better show the intention. https://whimsical.com/mindlogger-self-invite-feature-7nNV6vKKrHdan3fYWYBDAH  (let me know on slack if you'd like edit/comment access)

For you questions, I would suggest the approaches below:

> I would also say that is a must-have to allow the admin to turn on/ off this public URL for security purposes

For this reason I think it would be good to use a guid in the url that is separate to the appletId. Then it can be easily revoked.

> What admin users are allowed to create this invitation?

Owner only is enough for now.

> What does the screen show to a user that has not 'accepted' the invitation?<  

the process after creating the invite would be the same, so whatever screen is currently shown if a user declines an invite

> What happens when the URL is turned off? Do the users that have already joined the applet get to stay on as users?<  

Already joined users and pending invites stay valid. Admin panel already has ability to remove individual users if needed.


@binarybottle we are just trying to create a simple first round implementation, but of course let me know if you would do anything differently.

**Comment by WorldImpex** [comment]
@BarrySunderland 
1. Is there a concern to be able to identify the data once it is received? In the current flow, we will not have a way to identify the user. I assume that is okay but I just wanted to point that out. So we would just need to systematically create secret user IDs to identify each response data collected. 
2. What admin users are allowed to create this invitation?
Owner only is enough for now. - I think this makes sense for a manager to have control of as well 
3. Declined invitation looks like the below  
![mindlogger-web.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/dddd65f3-0002-4b3a-9c99-5bb168451543)

**Comment by BarrySunderland** [comment]
>In the current flow, we will not have a way to identify the user.

Sorry I don't quite understand why they would not be identified. If inputting the MRN in the invite form of the admin panel identifies users' response data, then automatically generating an ID for this MRN field should still link the users to the response data to this ID, right? 

Other than that it seems like we're pretty aligned? but that we'll have to wait until the new web development in React starts up.

**Comment by WorldImpex** [comment]
Yes but you will not know that the full name created in the user's form is associated with the automatic MRN since we do not connect that to the response data. This allows us to store the data de-identifiable

**Comment by WorldImpex** [comment]
@BarrySunderland  I would also suggest that a user without an account should have a separate experience where we collect account information at the same time we set the user up for the applet. It is an awkward experience to signup and then signup again. 

Also, what would we be collecting name and email address for on a user that is signed in?

**Comment by BarrySunderland** [comment]
> Yes but you will not know that the full name created in the user's form is associated with the automatic MRN

I think just tracking the pseudonymized identifier created by the auto MRN is fine for now. 

>Also, what would we be collecting name and email address for on a user that is signed in?

I was just replicating the existing endpoint but that's true. I think personally I would keep the email input field as it would probably be a more familiar user experience. (as opposed to just 'click this button to sign up'). Happy to do which ever you think is best.

Arno suggested to create a temporary standalone implementation, which would allow testing and help with explanation.
I'll let you know when I have something to show.

**Comment by BarrySunderland** [comment]
Just an update for anyone following this.

I tried adding creating a new invitation by using the web and posting to the inviteUser api endpoint (/api/v1/applet/{{appletId}}/inviteUser?) using the users own auth token and email etc, but this is not allowed (quite sensibly).
```
{
    "message": "You don't have enough permission to invite other user to specified role",
    "type": "access"
}
```

<img src="https://user-images.githubusercontent.com/45671832/114015726-541bde80-986a-11eb-8b9c-dfb3d644a908.png" height='500px'/>

1.  As Wil said, we would need a boolean field in the database for each applet where admins can allow/deny open invites. 
Then the inviteUser endpoint [see here](https://github.com/ChildMindInstitute/mindlogger-backend/blob/daa2eed6712d271579d782c1b4479d912b411a5b/girderformindlogger/api/v1/applet.py#L1397 ) could be modified to include an if statement to accommodate this behavior.

2. Is there some way to get the title of an applet from the id number? As far as I can see this needs admin permissions aswell. If not we'd have to do something like using this openInvite setting to modify the getApplet request to display some info about the applet.

Any hints are welcome.

**Comment by natalia-muzyka** [comment]
Users can invite themselves to an applet via generated on admin panel public link.
The existing invitation form is used. 
After accepting the invitation the applet is added to an account and displayed on the webapp side and mobile app.
Data are collected on the admin panel under the auto-generated user scope:
https://www.screencast.com/t/CeSiOK72X
