### ISSUE TITLE
Upload Email does not reflect new design 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#845]
Based on this [ticket](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/699), any MindLogger email should be branded in the new style

**Comment by sergeysemenuta** [comment]
The upload email is updated to the new design
![2021-03-11_10-33-02.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/cd83cd0a-0b4a-4272-9c2f-860183797f46)
