### ISSUE TITLE
Add frequency line plots for Token Items (Affects current pilot study)

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#846]
Clinicians who are using TokenLogger assign a token values to behaviors. The 'Token' tab of the data viz dashboard show the number of tokens earned each day broken down by behavior, but clinicians also wish to track the frequency of these behaviors over time.

**Fig1** Our current dashboard shows the daily frequency of choices in the 'Responses' tab when you hover the mouse over the data point.
<img width="1091" alt="Screen Shot 2021-03-10 at 6 48 28 PM" src="https://user-images.githubusercontent.com/24463939/110720712-10877380-81dd-11eb-9d96-0aa7c9e9ce61.png">

**Fig2** The clinicians would like to see this information in a line plot. For example:
<img width="400" alt="Screen Shot 2021-03-10 at 7 52 36 PM" src="https://user-images.githubusercontent.com/24463939/110721041-aa4f2080-81dd-11eb-9bcc-b752f465274d.png">

Request: Add a new tab called "Frequency" to data viz dashboard which include lineplots that show the daily frequency for each choice.

Requirements: 
1. show 1 line plot per choice
2. the x-axis will work the same way as the plots in the 'Response' and 'Token' tabs
3. make sure the range of the Y axis is the same for every choice in the item
4. No aesthetic requirements, choose something that looks nice
5. Make sure long choices are fully displayed (see #847)

Nice to have:
1. Color the points differently for each choice

Scope:
**This tab will only display graphs for token items, just like the 'Token' tab.**

**Comment by WorldImpex** [comment]
TL Dashboards do not show on admin 

Steps to recreate
1. Log into admin-staging in incognitio mode (wavanauken+11@gmail.com/abcd123) Check dashboard (Abcd1234!) 
2. Look at all tabs
3. See Results

Expected: Data is shown 
Actual: No data is shown on the screen 


![2021-04-02.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/7f183ea2-bb45-4845-aa1a-d6d57313249d)

**Comment by sergeysemenuta** [comment]
The "FREQUENCY" tab is available for the applets that do not have token values. 

Expected:  The "FREQUENCY" tab should be hidden for the applets that do not have token values.

**Comment by sergeysemenuta** [comment]
- [REQUENCY tab]The graphs are not shown up on my old existing applets and on the new applets created via the applet builder
![2021-04-08_14-25-25.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4436ccf8-f4b7-428e-a8fa-182c1503330d)

- The "FREQUENCY" tab is available for the applets that do not have token values.

Works as expected on new git hub applets
![2021-04-08_14-27-16.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/df12ddc6-c10a-4588-8c0a-059c104514e2)

New account: hero@qa.com // 123456
Applets password;Qwe123!!!
https://admin-staging.mindlogger.org/

**Comment by sergeysemenuta** [comment]
Graphs are shown only for the checkbox options but for the radio options, they are not shown up.
![2021-04-09_12-15-27.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e0496d0c-dc69-4b1b-9d7d-5fbc68b53f92)

Checked on :
https://admin-staging.mindlogger.org/

**Comment by sergeysemenuta** [comment]
The issues are fixed
![2021-04-12_17-38-44.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/64351a68-90e2-4f88-80f4-a74885381c93)
Staging
ML v 0.16.6
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11
