### ISSUE TITLE
Display choices fully in the 'Response' tab (Affects current pilot study)

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#847]
Choices are hidden after going over a character limit. 
<img width="1060" alt="Screen Shot 2021-03-10 at 8 04 51 PM" src="https://user-images.githubusercontent.com/24463939/110724131-331c8b00-81e3-11eb-95af-de44433e2a3f.png">

Request: Display these choices fully by wrapping the text

**Comment by sergeysemenuta** [comment]
The issue is fixed.
The tooltips are shown up after hovering on options text
![2021-03-17_17-59-51.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4bf9d85a-f58e-423e-9b33-3f77b346dbc0)
https://admin-staging.mindlogger.org/
Win 10 //  Chrome 88
