### ISSUE TITLE
Change "+ New Applet" to Configure an Applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#849]
![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/a8c75fa5-bd28-42f6-961c-28c89786d6ca)

**Comment by sergeysemenuta** [comment]
Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 88
![2021-03-12_10-57-23.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c2fee4e5-bedb-4274-bb2e-7f43424338c0)
