### ISSUE TITLE
Data Vis Updates

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#854]
* Make response options graphs a light grey 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f6f267ec-3378-4134-9dfa-f375154a6060)
* Make lines between dots on a graph thicker 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/615a5b82-247d-4f31-a650-06d95e276b7f)
* Show the month once for the range of data and only numbers at each horizontal line 
![Blank diagram.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/376e8089-97cd-4c7d-9693-defda9a77042)
* 2 months or more show weekly date range on data visualization for dates but show all data points over the week 
* At one year, show date range monthly with data points for all time

**Comment by sergeysemenuta** [comment]
It is updated and looks as expected
Video:https://www.screencast.com/t/l8smHprjFV
https://admin-staging.mindlogger.org/
Chrome 89
