### ISSUE TITLE
Git-hub applet. Updating the Skippable Item option on the  TokenLogger applet adds "False' tooltips to each response option

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#863]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqqa@gmail.com // 123456
2. Upload an applet https://raw.githubusercontent.com/ChildMindInstitute/TokenLogger_applet/master/protocols/TokenLogger/TokenLogger_schema
3. Take an assessment on the app
3. Go to edit this applet and uncheck the Skippable Item option on the item screen and save
4. Go to edit current options
5. Look at the markdown editor

**Actual result**: Updating the Skippable Item option on the  TokenLogger applet adds "False' tooltips to each response option
**Video:** https://www.screencast.com/t/1zw35X78Br
**Expected result:** When navigating to edit   'TokenLogger' applet the Skippable Item option should be disabled by default and "False' tooltips should not be added to each response option after Updating the Skippable Item option.

**Environment:**
https://admin-staging.mindlogger.org/

**Comment by natalia-muzyka** [comment]
Reproduces after changing the token values to negative as well.
https://admin.mindlogger.org/
Win 10 // Chrome 91.0.4472.124 
ML v0.16.35 (staging, prod)
iPhone XR // iOS 14.3	
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0	
iPhone 6 Plus  // iOS 12.3.1

**Comment by natalia-muzyka** [comment]
TL protocol is not going to be supported anymore.
Close the ticket.
