### ISSUE TITLE
Update Email Text for Resetting Password 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#869]
Update the body of the email to 

A password reset has been requested. Please use [this link](hyperlinkedURL.com) to reset your password. Please be aware that if you update your password, the data that has been previously recorded will be deleted. 

If you did not initiate this password reset, you can ignore this email. The link provided expires 15 minutes after it was requested.

If you have had any issues joining an applet or creating an account, please write us and we can help you.

Thanks,

The Mindlogger Team

**Comment by sergeysemenuta** [comment]
The Email text is updated 
![2021-04-06_10-29-59.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/990eae02-fe85-4030-9981-6317458c7885)
Verified on:
staging
