### ISSUE TITLE
Random issue. Sometimes the latest score is wrong on the Data viz/Data export file

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#875]
**Steps to reproduce:**
1. Log in to the app  kai@ss.com // 123456
2. Select the subscales applet and take an  activity
3. Check the results on the data viz dashboard for the user https://admin-staging.mindlogger.org/ (owner: logan@ss.com // 123456 applet password: Qwe123!!!)
 Actual results:  Sometimes the latest score is wrong on the Data viz/Data export file. The responses column shows 'Oblect 'text instead of the number of responses. It calculates  the wrong subscale score which is "0"
![2021-03-23_17-31-25.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/b6757ba4-5a74-4e5c-8474-7606218e0bf9)
Expected result:  The calculation for the latest score should be correct for subscales on the Data viz/Data export file

Environment:
 https://admin-staging.mindlogger.org/ (Win 10 //Chrome 89)

**Comment by WorldImpex** [comment]
There is a problem with subscale and final score so I am not going to test this one yet

**Comment by sergeysemenuta** [comment]
This issue is no longer reproducible
Checked on:
Staging
ML v 0.16.4
iPhone X // iOS 13.3
Pixel 4XL//Android 11
