### ISSUE TITLE
[PROD] Exports not working 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#879]
Steps to recreate 
1. Log into an account (wavanauken@gmail.com/ abcd123)
2. Select an applet and hit export (Abcd123)
3. See results 

Expected: A file is generated with response data 
Actual: Nothing happens

**Comment by sergeysemenuta** [comment]
Export works on staging
Checked for the owner, manager, and reviewer roles
https://www.screencast.com/t/Fnniiln4D
https://admin-staging.mindlogger.org/
Win 10 Chrome 89
