### ISSUE TITLE
[PROD] Coordinators Cannot Create an Invitation 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#885]
Steps to recreate 
1. Log in as a coordinator to an account in production 
2. Click the applet the user is a coordinator of 
3. See Results 

Expected: The invitation tab is available for the user. Managers can see the invitation tab but cannot action it 
Actual: invitation tab is hidden

**Comment by sergeysemenuta** [comment]
Rechecked in staging. The coordinator is able to create invitations
Video: https://www.screencast.com/t/ddVp6mL9bT
https://admin-staging.mindlogger.org/
Win 10 //  Chrome 89

**Comment by WorldImpex** [comment]
Managers now cannot 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/03c3308a-b753-4741-a14b-2432321af219)

**Comment by hotavocado** [comment]
I was able to reproduce this issue:

This happens only when a coordinator is switched to a manager role.

1. owner invites user1 as 'coordinator'
2. user1 can send invites fine
3. owner now edits user1 role, replaces coordinator with 'manager'
4. user1 has all manager privileges, like being able to see other managers and edit applet. however, when sending an invite, they receive this error:
![Screen Shot 2021-03-31 at 3 17 23 PM](https://user-images.githubusercontent.com/24463939/113199506-3086e180-9235-11eb-8178-c114487b0044.png)

This behavior is also observed:
5. owner deletes user1 account from applet
6. owner sends user1 a new invite as 'manager'
7. user1 accepts invite and can now send invites successfully

**Comment by WorldImpex** [comment]
works as expected on prod
