### ISSUE TITLE
Show header image on data visualization 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#890]
If there is a header image available, show it above the question
If there is not a header image available, then do not show or leave a large white space 

The scope of this ticket is for radio button, checkbox, slider and textbox items 

![Screen Shot 2021-03-25 at 11.13.14 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/75e36d91-e8c6-46c0-953d-522ab6afbc66)

**Comment by sergeysemenuta** [comment]
Works as expected.
![2021-05-11_12-33-11.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c5420323-7300-424a-827b-265631d17021)
https://admin-staging.mindlogger.org/
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
