### ISSUE TITLE
Export file does not match the document for the HBN EMA

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#892]
Actual result: Export file for EMA shows this template :
![2021-03-30_15-12-24.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/b84eec08-61ed-4fd6-9574-c4fe75c9ffcc)
Expected result: The data should be displayed in the CSV file and looks like in this doc https://docs.google.com/spreadsheets/d/1OAAogjIvOA-sdFX7DI4s6Jr8ciScaiwioK0tEzfxglM/edit

Environment:
https://admin-staging.mindlogger.org/

**Comment by WorldImpex** [comment]
Mike confirms that this is sufficient
