### ISSUE TITLE
Deleting Applets in Folders does not visually remove them

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#896]
Steps to recreate
1. Log into admin-staging (wavanauken+11@gmail.com/ abcd123) 
2. Create or upload an applet
3. Place it in a folder 
4. Delete the applet within the folder 
5. Delete the folder 
6. See results 

Expected: Applets are removed and the folder can be deleted 
Actual: Applet functions are removed but visually the applet is still there and the folder shows an error that it cannot be deleted unless the applets are deleted or removed 

If you move the applets outside of the folder then the folder can be delete but the applets without functionality are still on the dashboard

**Comment by sergeysemenuta** [comment]
The folders are not removed from the dashboard
Video:https://www.screencast.com/t/WkDokuZZJG4

The issue is still reproducible

https://admin-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by sergeysemenuta** [comment]
Fixed for new folders But the old folders are not removed
Account: snakessqa@gmail.com // 123456
https://www.screencast.com/t/JtSdV9B5
Expected: All folders should be deleted as well

https://admin-staging.mindlogger.org/
Win 10 //Chrome 90

**Comment by Matchdev120** [comment]
@sergeysemenuta I looked into the old folders in your account.
Those folders contain hidden applets and damaged by the old deleting functionality.

If you want, I will remove the damaged folders by code.

**Comment by WorldImpex** [comment]
@Matchdev120  Please remove the old damaged folders for @sergeysemenuta

**Comment by Matchdev120** [comment]
@sergeysemenuta I removed the damaged folders in your account (snakessqa@gmail.com // 123456)

**Comment by sergeysemenuta** [comment]
Verified on my account. Works as expected
https://admin-staging.mindlogger.org/
Chrome Version 90.0.4430.212
