### ISSUE TITLE
The Title of the Calendar is misleading 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#897]
Please see the video. The calendar should show General but it shows as an individual 

![mindlogger-admin.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/12f60973-f6aa-41e6-9cb6-0da36949647e)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2021-04-09_11-46-24.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/8d25a135-ec4e-49dd-90c3-f5f2e1195445)
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 89
