### ISSUE TITLE
Remove black lines between dots - Radio Button

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#918]
Please remove the black line between dots on a radio button. 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/80d9f91d-0778-49e4-9700-bac488970bf5)

**Comment by sergeysemenuta** [comment]
The lines are no longer available
![2021-04-23_14-53-27.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6e7ae04f-b3c2-4d66-a263-c1b5c41593ad)

Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90
