### ISSUE TITLE
Compliance Dots show up outside of the Final Score Graph

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#919]
Steps to recreate
1. Log into mobile device to take subscale final activity (wavanauken+11@gmail.com/ abcd123) 
2. Take assessment 
3. Log into admin with the same account to check the dashboard 
4. Open Dashboard and see results 

Expected: Only the time range selected shows data 
Actual: Data is shown outside of the visualization 

![Screen Shot 2021-04-13 at 5.35.07 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c0844066-dd2f-43dc-9c3b-2522b2a1095d)

**Comment by sergeysemenuta** [comment]
Looks as expected on my account.
![2021-04-23_14-37-54.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/2d8e3fe4-d93c-45b6-8c33-c0c25fa3b00c)
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90
