### ISSUE TITLE
The digits are specified by default in the Min/ Max label on the stacked slider items on the admin/app side

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#932]
Steps to reproduce:
1. Log in to the applet builder https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Create an activity and add the stacked slider item
3. Do not fill in Min/Max label fields
4. Upload the applet
5. Log in to the app  and look at the stacked screen 
6. Go to edit the newly uploaded applet and look at the labels fields

**Actual result:** The digits are specified by default in the Min/ Max label on the stacked slider items on the admin/app side
![2021-04-21_10-26-36.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9fa8256f-8f13-494c-8f92-3e6fb6b92511)
![2021-04-21_10-25-09.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/752db96f-6cb1-42d1-91ba-6f3348fdc2a2)
**Expected result:** The labels Min/Max are specified by default in the Min/ Max label on the stacked slider items on the admin/app side

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90
ML v 0.16.15
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11

**Comment by natalia-muzyka** [comment]
Reproducible on:
ML v0.16.31(staging)
iPhone XR // iOS 14.3	
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0

**Comment by natalia-muzyka** [comment]
Not reproducible anymore:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/330833a4-7327-4df8-bc40-4f9fc794327c)

https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
