### ISSUE TITLE
There are two bars are shown on the tokens chart on the Data Viz Dashboard

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#934]
**Preconditions:**
The applet is uploaded to the dashboard that contains token values for radio and checkbox items on different screens
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ bughunterqa123@gmail.com // 123456
2. Select the "Token Applet" and navigate to the data viz dashboard (Applet password: Qwe123!!!)
4. Select the "TOKEN" tab
5. Look at the chart

**Actual result:**  There are two bars are shown on the tokens chart on the Data Viz Dashboard. 1st for checkbox items. 2nd for radio items
![2021-04-21_13-33-41.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/644cc730-b287-45fe-b8c4-065ef83b6243)
**Expected result:** One bar that contains cumulative from radio and checkboxes is shown within the applet 

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by natalia-muzyka** [comment]
Still reproducible
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124

**Comment by natalia-muzyka** [comment]
Close due to the updated TL.
