### ISSUE TITLE
The globe icon is missing on the admin dashboard

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#948]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Hover mouse over the applet
4. Observe the panel with buttons

**Actual result:** The globe icon is missing on the admin dashboard
![2021-04-28_15-45-18.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ba6bfb29-646a-4dff-939f-0f395f190797)
Expected result: The globe icon is shown on the admin dashboard  for the owner and manager role

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by WorldImpex** [comment]
works as expected
