### ISSUE TITLE
The "Browse Applet Library" is missing in the "Configure an applet" list

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#949]
Steps to reproduce:
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Click the "CONFIGURE AN APPLET" button
3. Look at the list

Actual result: The "Browse Applet Library" is missing in the "Configure an applet" list
![2021-04-28_15-49-43.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/b565c859-440e-4a24-8ecb-5e9099cdb024)
Expected result: The "Browse Applet Library" is shown in the "Configure an applet" list
Environment: 
https://admin-staging.mindlogger.org/
Chrome 90// Win 10

**Comment by WorldImpex** [comment]
fixed
