### ISSUE TITLE
[Applet Library] The confirmation message is missing after clicking the trash can on the basket view page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#951]
**Steps to reproduce:**
1. Log in to the applet library https://library-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Add applet to the basket
3. Navigate to the basket
6. Click the trash can
7. Look at the result

**Actual result:** The confirmation message is missing after clicking the trash can on the basket
https://www.screencast.com/t/xhDddZN9Vu3i
**Expected result:** The confirmation message "Are you sure you want to delete " Applet Name from your basket? " is shown after clicking the trash can on the basket

**Environment:**
Staging
https://library-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by sergeysemenuta** [comment]
The confirmation pop up is added, But this popup needs to be updated closer to the MindLonger style as on  the admin staging site
![2021-04-29_10-29-03.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c460959d-b137-4948-b391-c8c93bbf2674)
Environment:
Staging
https://library-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by sergeysemenuta** [comment]
It is Updated but horizontal scrolling bar is Shown at the Bottom of the popup
Please, remove the scrolling bar
![2021-04-30_16-40-40.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/74aab4c0-7a45-4940-92c7-9c5e2d5478e8)
https://library-staging.mindlogger.org/
Desktop// Win 10 //Chrome 90

**Comment by binaryExDev** [comment]
@sergeysemenuta This is what I can see the confirmation dialog.
Please test it again on admin-staging and let me know. ![Screen Shot 2021-05-02 at 12.30.45 PM.png](https://images.zenhubusercontent.com/5fc8d89138215d1055c6d606/32bf5243-19ad-4b3c-8f3a-5ba9e3f6403d)

**Comment by WorldImpex** [comment]
Works as expected 

![Screen Shot 2021-05-03 at 6.19.08 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/de2c7b94-7ccb-48dd-897c-75617337a048)
