### ISSUE TITLE
The applet detail page is empty for the non-logged in users

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#955]
Steps to reproduce:
1. Open the site https://library-staging.mindlogger.org/
2. Click the information"i" button on the applet card
3. Look at the result

Actual result: The applet detail page is empty for the non-logged in users
![2021-04-29_13-44-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c71f9374-c4fd-41ab-9ab9-b87bc4ac8cef)
Expected result: The content should be displayed on The applet detail page  for the non-logged in users

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by WorldImpex** [comment]
![Screen Shot 2021-05-05 at 5.49.20 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b9b74a52-0dde-4b51-8bb6-2e8197d0d78d)

Fixed
