### ISSUE TITLE
[Applet Library]The search without keywords doesn't work 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#956]
**Steps to reproduce:**
1. Log in to the admin panel and share the applet with the library without specifying keywords
https://admin-staging.mindlogger.org/ snakessqa@gmail.com
2. Open the  applet library https://library-staging.mindlogger.org/
3. Specify the applet name, description, activity name, and item question into the search field
4. Look at the result

Actual result: The search without keywords doesn't work. 
Video:https://www.screencast.com/t/e3bWKdVEgS0i
Expected result: The search without keywords should work 
Environment:
https://library-staging.mindlogger.org/
Win 10 Chrome 90

**Comment by WorldImpex** [comment]
1. Made the bolding of the letters thicker/ more noticeable 
![mindlogger-library.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5c9e6fa4-f92b-43b4-a9c1-66a8448e58df)

2. Questions and response options should be included in the keyword search. Bold the Item level question or response option and expand the section the question/ response option is in to show the bolding 
![Screen Shot 2021-05-10 at 4.57.21 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b011db0b-e4fc-4a2a-a92b-13e37efd3c4b)

**Comment by binaryExDev** [comment]
@WorldImpex Would you make sure a couple of things?

 - Regarding the search functionality, you said that we don't need to have the item level and just applet and activity.
"I just talked to Arno and he said we do not need to go to the item level just applet and activity"

 - We're currently using a package called DataTree to display the applet/activity/item data. It means that there's no way to build the keyword in response options and questions. To fix this issue, we should build the DataTree component manually.

**Comment by WorldImpex** [comment]
@binaryExDev 

1. Yes we are not allowing the user to select items or response options to put in the basket. We should still show search results based on keywords in any part of the content related to an applet 
2. How long to implement? Why can it not search questions or response options?

**Comment by binaryExDev** [comment]
@WorldImpex I can build the search functionality with response options and questions but the questions and response options couldn't be bold inside the package.

To have it bold, we should rebuild the package manually and it would take two days I guess.

**Comment by WorldImpex** [comment]
@binaryExDev Please update it so it works as expected

**Comment by sergeysemenuta** [comment]
Works as expected
https://www.screencast.com/t/b66AMQEPS

Checked on:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
