### ISSUE TITLE
The Category/Sub-category/Keywords: fields are not displayed on the share applet details modal 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#957]
Steps to reproduce:
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Hover over any applet and click the globe icon
3. Turn on the toggle button  and 'PUBLUSH'
4. Close the modal window
5. Repeat step 2,3 on other applets (do not reload the page)
5. Take a look at the  share applet Details modal 

Actual result: The Category/Sub-category/Keywords: fields are not displayed on the share applet Details modal 
![2021-04-29_14-37-23.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/2da965c2-497d-4feb-ae54-7189a5b6be2c)
Expected result: The Category/Sub-category/Keywords: fields are displayed on the share applet Details modal. The user should be able to see those fields in order to publish several applets one by one without reloading the page

Environment:
Win 10 // Chrome 90
https://admin-staging.mindlogger.org/

**Comment by WorldImpex** [comment]
![Screen Shot 2021-05-03 at 6.13.32 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c86c0c7d-431d-4f93-bb15-094dfb571739)

Works as expected
