### ISSUE TITLE
It is possible to share the applet with the same applet name to the Library

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#958]
Steps to reproduce:
1. Log in to the admin panel as an owner A create the Applet "TEST"
2. Publish it to the Library
3. Log in as another owner B create the Applet "TEST"
4. Hover over the Applet "TEST" switch on the toggle button
5. In the new name field enter: TEST
6. And PUBLISH it
7. Look at the applet Library

Actual result: It is possible to share the applet with the same applet name to the Library
https://www.screencast.com/t/txFRiTNu7
![2021-04-29_15-20-53.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/be98d52c-4994-4c22-8544-79edbb184348)
Expected result: It is possible to share the applet with the same applet name to the Library. The validation message should be shown after entering the applet name that had been already published in the library

Environment:
https://admin-staging.mindlogger.org/
https://library-staging.mindlogger.org/

**Comment by WorldImpex** [comment]
Works as expected 

![Screen Shot 2021-05-03 at 6.12.07 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b8e952ce-7ba0-4f5a-a12b-25cbca9e9387)
