### ISSUE TITLE
The tooltip is missing  after hovering over the basket  icon

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#959]
Steps to reproduce:
1. Open the site and log in https://library-staging.mindlogger.org/  snakessqa@gmail.com // 123456
2. Click the "i" button on the applet card
3. Hove mouse over the basket  icon
4. Look  at the result
Actual result: The tooltip is missing  after hovering over the basket  icon
![2021-04-29_15-36-01.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/11ae5342-54ad-4390-b7b4-0eecd2169827)
Expected result: The tooltip is shown after hovering over the basket  icon

Note: Tooltips should be displayed for the Informational (i) icon / add to basket as well

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by WorldImpex** [comment]
No tooltip is shown

**Comment by binaryExDev** [comment]
@WorldImpex 

![Screen Shot 2021-05-05 at 6.46.09 AM.png](https://images.zenhubusercontent.com/5fc8d89138215d1055c6d606/93d9773e-0ffa-4a49-988c-74de7700ee77)

**Comment by WorldImpex** [comment]
Yes please @binaryExDev

**Comment by WorldImpex** [comment]
These should say "Add to Basket" 

![Screen Shot 2021-05-10 at 5.06.11 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/1bf330a1-4c5d-45da-ab0a-1bc578ddc066)

![Screen Shot 2021-05-10 at 5.07.59 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f160d4ef-28d0-4b07-828c-3dea4aa1abf4)

Also, I cannot test the item detail page icon as it is blocked by #350

**Comment by binaryExDev** [comment]
@WorldImpex 
 - On second image, it is not 'Add to basket' button.

 - Would you explain the second comment?
"Also, I cannot text the item detail page icon"

**Comment by WorldImpex** [comment]
@binaryExDev 
1. Righ both of those buttons should be Add to cart. That is what the user will be doing on either page/ action the button performs 
2. Sorry spell check changed it - It should be test and I updated it

**Comment by sergeysemenuta** [comment]
The tooltips are added
![2021-05-12_15-14-05.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c58da221-d06b-44ee-ac76-a2d66d6ce382)
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
