### ISSUE TITLE
The Category and Sub-Category fields are not required  on the applet details share modal

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#960]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Click the globe icon over the applet panel
3. Switch on the toggle button
4. Click the 'PUBLISH' button
5. Look at the result on the applet library

**Actual result**: The Category and Sub-Category fields are not required  on the applet details share modal
![2021-04-29_16-43-07.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4b5bec67-eec4-4adb-8fcd-e7a143c4c05a)
**Expected result:** The Category and Sub-Category fields  should be required  on the applet details share modal

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by WorldImpex** [comment]
fixed and works as expected
