### ISSUE TITLE
The basket button is missing in the header 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#961]
Steps to reproduce:
1. Open the site https://library-staging.mindlogger.org/
2. Look at the header

Actual result: The basket button is missing  in the header 
![2021-04-29_16-54-00.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5f2b1b2e-e4fe-4b90-8629-0c5d5f4107c6)
Expected result:  The basket button is shown in the header  next to the Login button
Environment:
https://library-staging.mindlogger.org/
Win 10 / / Chrome

**Comment by binaryExDev** [comment]
@WorldImpex @sergeysemenuta I've a couple of questions.

 - what should be displayed on the basket?
 - what should happen after tapping on the basket?

**Comment by WorldImpex** [comment]
@binaryExDev 

- The location of the basket button is correct on the search page. It is missing on the other pages in the header
- As any type of option is added to it, the number should increase by 1 
- It would be a good to show possibly a little shake of the basket if the incremental increase is too small to see

**Comment by binaryExDev** [comment]
@WorldImpex The basket content is till not clear.

Let's say there's one public applet.

EMA Applet
 - Morning Activity
   * Item1
   * Item2
   * Item3
 - Night Activity
   * Item4
   * Item5

**Cases**
User selected 3 items (item1, item2, item4) - Is the basket number 3 (item1, item2, item4)?

User selected one more item (item3) - Is the basket number 2(Morning Activity, item4)?

User selected one more item (item5) - Is the basket number 1(EMA applet)?

-------------------------------------------

I currently displayed only number of applets regardless of items/activities.

So even though one of items or activities is selected in the applet, the applet is calculated on the basket.

Please let me know the correct one we are targeting now.

**Comment by WorldImpex** [comment]
@binaryExDev We should still only be able to select an applet or activities. The below is correct but right now the basket does not change when adding something to it 

I currently displayed only number of applets regardless of items/activities.

So even though one of items or activities is selected in the applet, the applet is calculated on the basket.

**Comment by WorldImpex** [comment]
Reproducible

**Comment by binaryExDev** [comment]
@WorldImpex 
"We should still only be able to select an applet or activities. The below is correct but right now the basket does not change when adding something to it

I currently displayed only number of applets regardless of items/activities.

So even though one of items or activities is selected in the applet, the applet is calculated on the basket."

I rechecked this comment and it works on my side.

Please add an applet and the number will be increased.

**Comment by WorldImpex** [comment]
@binaryExDev The basket icon is missing from the details page 

![image](https://user-images.githubusercontent.com/22243307/117654581-eeba5680-b163-11eb-84e6-982edbfecad4.png)

**Comment by sergeysemenuta** [comment]
The basket icon is displayed on the the details page
https://www.screencast.com/t/GzAnIf9NFsV
Checked on:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
