### ISSUE TITLE
The basket counter is not functioned after adding items, activities to the basket

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#962]
Steps to reproduce:
1. Open the site/log in https://library-staging.mindlogger.org/
2. Select checkboxes on applet cards and click the add to cart icons
4. Look at the basket counter

Actual result: The basket counter is not functioned after adding items, activities to the basket
Video: https://www.screencast.com/t/TCZCbUegcWe
Expected result: The basket counter is increased  after adding items, activities to the basket and decreased after removing them from the basket
Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by WorldImpex** [comment]
User cannot click on basket anymore.

**Comment by binaryExDev** [comment]
@WorldImpex User cannot click on basket before login.

**Comment by WorldImpex** [comment]
Login should be triggered when the user tries to check out. Not when they try to view the basket @binaryExDev

**Comment by WorldImpex** [comment]
Deleting an item from the basket does not work.

**Comment by sergeysemenuta** [comment]
-Deleting an applet works as expected
-The basket is clickable
-The counter is increased after adding an activity or applet and  decreased after removing an activity

https://www.screencast.com/t/I0ultjCsb
Win 10 //   Chrome Version 90.0.4430.212
