### ISSUE TITLE
[Checkout]The user is navigated to the blank page after trying to send an applet or content  to the applet builder

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#963]
**Preconditions:** 
The user is logged in to the applet Library
The applets in the basket
Steps to reproduce:
1. Mark the checkbox on the  applet card
2. Click the "ADD TO APPLET BUILDER" button
3. Select the account and click 'add'>add to the new or existing applet ad click add again
4. See the result

**Actual result:** The user is navigated to the blank page after trying to send an applet or content  to the applet builder
**Video:** https://www.screencast.com/t/ZgUUMmLTN2
**Requirements:**  [85](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/85)
**Expected result:** The user is navigated to the applet builder and corresponding content should be available

**Environment:**
https://library-staging.mindlogger.org/
Win 10 //  Chrome 90

**Comment by WorldImpex** [comment]
reproducible

**Comment by WorldImpex** [comment]
Still reproducible

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Verified on:
https://library-staging.mindlogger.org/
Win 10 //  Chrome Version 90.0.4430.212
