### ISSUE TITLE
[Staging] Unable to upload media files from the computer on  the admin staging site

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#964]
**Steps to reproduce:**
1. Log in to the admin panel  https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Edit any applet or go to the applet builder
3. Try to upload video, images, audio file to the items from the filing system
4. Look at the result

Actual result: Unable to upload media files from the computer on admin staging site. "The popup 'Something Went wrong "is shown. The eternal loading spinner is shown when uploading audio//video files from the computer via markdown editor
Video: https://www.screencast.com/t/AaYvoxkCl7Zr
Expected result: It should be possible to upload media files successfully.

Environment:
https://admin-staging.mindlogger.org/
Win 10//  Chrome 90

**Comment by WorldImpex** [comment]
Works as expected
