### ISSUE TITLE
The deleted applet from the admin panel is available in the applet library

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#965]
Steps to reproduce:
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Choose any applet and publish it to the library
3. Delete that applet from the admin panel
4. Check the applet library  https://library-staging.mindlogger.org/

Actual result: The deleted applet from the admin panel is available in the applet library
Video:https://www.screencast.com/t/lV26lmMxde
Expected result: The deleted applet from the admin panel is not available in the applet library It should be removed from the library as well

Environment:
https://library-staging.mindlogger.org/

Win 10  // Chrome 90

**Comment by WorldImpex** [comment]
works as expected
