### ISSUE TITLE
[Applet Library]The validation message is missing after clicking the add to basket button without selecting activities/items from the applet detail page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#966]
**Preconditions:**
The user is  logged in and on Applet detail page
**Steps to reproduce:**
1. Click the add to basket button
2. Do not mark checkboxes on activities or items
3. Click the add to basket button
4. Look at the result

**Actual result:** The validation message is missing after clicking the add to basket button without selecting activities/items from the applet detail page applet is add to the basket
**Video:**https://www.screencast.com/t/O9GpbIxyNMs
**Expected result**: The appropriate validation message is shown after clicking the add to basket button without selecting activities/items from the applet detail page. The applet should not be added to the basket without selecting activities/items 

**Environment:**
https://library-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by WorldImpex** [comment]
Basket is not in the header on the applet detail page and there is no validation that you have added an activity still

**Comment by binaryExDev** [comment]
@WorldImpex 
Is this issue (#961) what you're talking now? I can see validation works on library-staging.mindlogger.org/#/appletDetail
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/961

**Comment by WorldImpex** [comment]
Yes to both @binaryExDev

**Comment by WorldImpex** [comment]
Icon is greyed out until a selection is made
