### ISSUE TITLE
Cannot click on time in calendar module

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#970]
Steps to recreate
1. Log into admin (wavanauken+1@gmail.com/ abcd123) 
2. Create a general schedule for an applet 
3. Try to set a start and stop time 
4. See Results 

Expected: The fields are clickable 
Actual: Fields can only be actioned when using tab 

![mindlogger-admin.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/792cc505-8a61-476c-bc9c-f007235c6dd7)

**Comment by Matchdev120** [comment]
@WorldImpex Just tested this issue on your account but it works as expected.

**Comment by WorldImpex** [comment]
works on another computer as expected
