### ISSUE TITLE
Media Export is still only a CSV

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#973]
Steps to recreate 
1. Take assessment on device (FOR CS/ wavanauken+1@gmail.com/ abcd123) 
2. Log into admin staging (wavanauken+1@gmail.com/ abcd123) 
3. Navigate to FOR CS applet 
4. Export the user data 
5. See Results 

Expected: A zip file is downloaded with media data 
Actual: Only a CSV is received

**Comment by sergeysemenuta** [comment]
The issue is reproducible. Only  CSV file is downloaded
Expected: The CSV and  zip file are downloaded with media data
Checked on:
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by sergeysemenuta** [comment]
The issue is reproducible. Only CSV file is downloaded
https://www.screencast.com/t/U6M6srpgn2oR
Checked on:
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 91)

**Comment by natalia-muzyka** [comment]
**Not reproduced**
A zip file is downloaded with media data
https://www.screencast.com/t/9afkpls9SDxj

Environment
Account: snakessqa@gmail.com
https://admin-staging.mindlogger.org/
Win 10 // Chrome Version 91
ML v 0.16.25 (Staging environments)
iPhone XR // iOS 14.3
Samsung Galaxy S7 Edge // Android 8.1
