### ISSUE TITLE
Reviewer Notes are not shown to other roles

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#975]
Steps to recreate
1. Log into a manager account and leave a comment on a user's responses (wavanauken+3@gmail.com/ abcd123 - LOOKUP applet)
2. Log into a reviewer's account and check comments (wavanauken+4@gmail.com/ abcd123)
3. See Results 

Expected: Owners, managers and reviewers see each other's notes 
Actual: The notes created by one account are not shown to the other accounts that have access

**Comment by WorldImpex** [comment]
Works as expected but when reviewing another user's notes, the textbox line is still clickable. It shouldn't be 

![\fads.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/fd6260a1-10a3-444a-9f32-eb49e588dd9b)

**Comment by sergeysemenuta** [comment]
Works as expected.
Checked on:
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
