### ISSUE TITLE
Notes should be in Descending Order/ Show Time Stamp 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#983]
Notes should start from the latest note to the oldest note. If the user hoovers over the time the note was written show a timestamp with date and time. 

![Screen Shot 2021-05-10 at 4.28.09 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/45ccc210-0e09-4404-bd2b-5bed859b6b4f)

**Comment by sergeysemenuta** [comment]
Works as expected.
Checked on:
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
