### ISSUE TITLE
The vertical scroll bar is shown up after entering the data into the Login form

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#986]
**Steps to reproduce:**
1. Open the site https://library-staging.mindlogger.org/
2. Add applet or an activity to the basket
3. Navigate to the basket
4. Click the 'ADD TO APPLET BUILDER' button
5. Start entering the data into the "Login form"
6. Look at the result

**Actual result:** The vertical scroll bar is shown up after entering the data into the Login form and the page is flickering
![2021-05-11_10-32-40.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e54ded43-4b92-4316-bc06-891c6f75c621)
**Expected result:** The vertical scroll bar is not shown up after entering the data into the Login form and the page is not flickering
**Note:** The horizontal scroll bar should not be shown as well
**Environment:**
https://library-staging.mindlogger.org/
Win 10 // Chrome Version 90.0.4430.212

**Comment by binaryExDev** [comment]
@WorldImpex Would you let me know your laptop resolution?
On my mac, I can't see the vertical scrollbar.

**Comment by sergeysemenuta** [comment]
@binaryExDev  Desktop 1920*1080

**Comment by binaryExDev** [comment]
@sergeysemenuta I tested it on the same desktop but it doesn't happen on my end.

Would you test it on the new version?

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
