### ISSUE TITLE
The ASSESSMENT, REVIEWED  tabs do not have content within the 'REVIEW' tab

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#987]
Preconditions:
-Users have taken the assessments for the Mental Health applet
-Owners and reviewer have left comments in the notes tab
Steps to reproduce:
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com (Owner)
2. Select the applet 'Mental Health'
4. Choose a user and view the data (applet password: Qwe123!!!)
5. Select the "REVIEW" tab
6. Click the Assessment or Reviewed tabs
7. Look at the result

Actual result: The ASSESSMENT, REVIEWED  tabs do not have content within the 'REVIEW' tab
Video:https://www.screencast.com/t/N2OxxH941r
![2021-05-11_13-32-39.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e860c9b9-98c8-4d58-b5a7-f2772b0de4a0)
Expected result: The ASSESSMENT, REVIEWED  tabs should show the  content related to it
Environment:
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by WorldImpex** [comment]
Not in scope for #888
