### ISSUE TITLE
The applet with long applet description  and multiple keywords brakes the layout of the applet library

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#991]
Steps to reproduce:
1. Log in to the site https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Publish an applet that have long Activiti name and add multiple keywords
4. Open the library https://library-staging.mindlogger.org/#/?lang=en_US
5. Look at the result

Actual result: The applet with long applet description  and multiple keywords  break  the layout of the applet library
![2021-05-12_14-22-53.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0a09eea9-e2f6-4de6-bd5b-00d00ee9c50b)
![2021-05-12_14-32-53.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3261e111-890e-46ce-9317-845865e3dccf)
Expected result: The applet with long applet description  and multiple keywords  do not  break  the layout of the applet library

Environment:
Win 10 // Chrome Version 90.0.4430.212 (Official Build) (64-bit)
https://library-staging.mindlogger.org/

**Comment by natalia-muzyka** [comment]
The issue is still reproducible for screen sizes:
1366×768
1536×864
1440×900
1280×720
1600×900
1280×800

Attachment: 
https://www.screencast.com/t/wSLHLutavnR
Environment:
https://library-staging.mindlogger.org/
Win 10 x64 // Chrome 91.0.4472.101

**Comment by natalia-muzyka** [comment]
Not reproduced
https://www.screencast.com/t/VvJevXNjhQz

Environment:
https://library-staging.mindlogger.org/
Win 10 x64 // Chrome 91.0.4472.101
