### ISSUE TITLE
[Applet library]The blank page is shown for the authorized user

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#997]
1. Open the site https://library-staging.mindlogger.org/
2. Log in  as snakessqa@gmail.com // 123456
3. See the result

Actual result: The blank page is shown for the authorized user
Expected result: The  User should see the content in the Library after logging in

Note: The issue is reproducible only for this account snakessqa@gmail.com // 123456

Environment:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by binaryExDev** [comment]
@sergeysemenuta Please test on new06@test.org/abcd1234

But the issue might occur again on your account/

I had a discussion with Ihor and he said that the issue was in schema compatibility and someone published and used applets created from api-dev.

New applet schema is deployed on api-dev.

**Comment by sergeysemenuta** [comment]
@binaryExDev It is not reproducible on this account  new06@test.org/abcd1234

Reproduced on:
snakessqa@gmail.com // 123456
jack@ml.com // 123456

https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by sergeysemenuta** [comment]
I created totally new account lary@ml.com // 123456. This issue is reproducible .
![2021-05-19_10-39-55.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/bd0f5135-d783-40f1-8e74-ea46f66808b4)

https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by sergeysemenuta** [comment]
I'm still experiencing the  blank screen for some time when logging in or navigating between pages on the library
Video: https://www.screencast.com/t/GZYJPJAx9
Expected result: The pages should be loaded immediately without blank screens

Checked on:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by sergeysemenuta** [comment]
@jj105 
The blank page is not displayed but  there is a poor performance of loading applets in the library & pagination updating
Please, see the video: 
https://www.screencast.com/t/vqetaXGOR

Checked on:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

cc: @WorldImpex

**Comment by natalia-muzyka** [comment]
All described issues are fixed
1. After logging in the applet library main page is displayed
snakessqa@gmail.com // 123456
jack@ml.com // 123456
2. Applets are loading fast and pagination displayed according to the applets quantity
https://www.screencast.com/t/tv2Rgbumlnb

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.77
